### ISSUE TITLE
[Feature Request]: Petition to use guoyww/AnimateDiff fork instead of animatediff-cli

### ISSUE THREAD

**Issue by Rorutop** [s9roll7/animatediff-cli-prompt-travel#1]
I don't think I like the "bat activation" implementation, there are more better than using animatediff-cli. Using the guoyww's fork will make it more usable especially on google colab (EX. Linaqruf's AnimateDiff notebook).

You can choose that original fork, but there are more recommended choices 
- https://github.com/talesofai/AnimateDiff (forked repo, can do initImage)
- https://github.com/dajes/AnimateDiff/ (fork repo, longer video duration)

I know you don't know about google colab stuff, you probably have to try one to understand them.

**Comment by s9roll7** [comment]
The original animatediff relies on too many old libraries and is not suitable for modification...

**Comment by Rorutop** [comment]
Well then that was disappointing, no use then. I still think the idea of smoothly mid changing ai animation scenes had VERY BIG potential.

**Comment by s9roll7** [comment]
94a5812
