### ISSUE TITLE
QUESTION about controlnet

### ISSUE THREAD

**Issue by alanhuang67** [s9roll7/animatediff-cli-prompt-travel#103]
Hello,

take canny as an example, can I use one pictures for canny, and this picture will effect for all frame creation?

thanks!

**Comment by s9roll7** [comment]
https://github.com/s9roll7/animatediff-cli-prompt-travel/issues/6
https://github.com/s9roll7/animatediff-cli-prompt-travel/issues/16
https://github.com/s9roll7/animatediff-cli-prompt-travel/issues/29
