### ISSUE TITLE
Sir, can you supply the prompt and other parameters/steps needed for reproducing ip_ref.mp4? 

### ISSUE THREAD

**Issue by frk2021** [s9roll7/animatediff-cli-prompt-travel#104]
[ip_ref.mp4](https://user-images.githubusercontent.com/118420657/265760409-d9d300a9-1107-4a3b-a1f1-3245b49dde10.mp4)

Thank you so much!

**Comment by s9roll7** [comment]
Unfortunately, I don't have one.
I have a habit of editing previously used json files when I make new videos...

**Comment by frk2021** [comment]
Thank you, sir!
I also found this same Lora together with this check point (https://civitai.com/models/18116?modelVersionId=97394). I tried to produce the similar video but failed. Here is my output. Can you give me a hand on how to produce better quality video?
Thank you so much for your great work.

My prompt:
https://github.com/zhengger/animatediff-cli-prompt-travel/blob/main/config/prompts/001-IP_LoRAs_kusanagi_motoko.json

My output:

https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/143593233/4e8fad1e-759c-461f-82c7-0b57f2a8a512

**Comment by s9roll7** [comment]
I've never seen that model.
In the case of animatediff, not all models give good quality results.
You should use this one.
https://civitai.com/models/24149/mistoonanime

**Comment by frk2021** [comment]
Ok, I'll try it.
Many thanks, Sir!

**Comment by zhengger** [comment]
I switched to [mistoonanime](https://civitai.com/models/24149/mistoonanime). Here is the new output. How to tune the fingers and others details so that can be more like ip_ref.mp4? Currently, I only used embeddings and Lora.


https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/2143234/f5d14d1c-fd67-44df-9eb7-291c86e8a297

**Comment by s9roll7** [comment]
Maybe you're outputting at 256x384?
You can't go for quality at this size.
If you want quality, you should go to 512x768.

**Comment by frk2021** [comment]
Yes. I used another computer to generate the video. It's surprising. 
Thank you so much, Sir!

![00012-1491041022](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/143593233/5634c598-c5b8-4d80-b152-58f75f9a5277)
