### ISSUE TITLE
Is there any parameter that can adjust style strength like the strength parameter do in img2img?

### ISSUE THREAD

**Issue by junnikokuki** [s9roll7/animatediff-cli-prompt-travel#107]
Same model, same prompt and n-prompt, same steps, the img2img in diffusers I use is 0.5, but in the video stylizing, it is over-styled.

**Comment by s9roll7** [comment]
https://github.com/s9roll7/animatediff-cli-prompt-travel/issues/6
https://github.com/s9roll7/animatediff-cli-prompt-travel/issues/16
https://github.com/s9roll7/animatediff-cli-prompt-travel/issues/29
