### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Gg811218** [s9roll7/animatediff-cli-prompt-travel#108]
![21](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/144506146/e871a9d8-e116-4c61-9a41-cad989250ab2)
[2023-10-14T00-08-46-sample-xxmix.zip](https://github.com/s9roll7/animatediff-cli-prompt-travel/files/12895542/2023-10-14T00-08-46-sample-xxmix.zip)

**Comment by s9roll7** [comment]
The first time you run it, it should have git cloned ProPainter into the path "src\animatediff\repo\ProPainter",
If you get that error, it doesn't seem to be working.
Remove "ProPainter" directory in the "src\animatediff\repo\ProPainter" directory and then run it, will that fix it?

**Comment by Gg811218** [comment]
Remove "ProPainter" directory  It will not be fixed ，Can I manually download this file to fix? How do I download and install?

**Comment by s9roll7** [comment]
https://github.com/sczhou/ProPainter/archive/refs/heads/main.zip

**Comment by Gg811218** [comment]
It worked  thanks
