### ISSUE TITLE
Controlnet seg preprocessor detect map result is different from webui extension

### ISSUE THREAD

**Issue by toyxyz** [s9roll7/animatediff-cli-prompt-travel#11]
The Detect Map image detected by the preprocessor on the controlnet seg differs from that obtained as a result of the webui controlnet extension. The image of webui has a fixed color for each object, but the image of prompt travel is blinking and not fixed.

Webui extension result
![ezgif com-gif-maker (1)](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/8006000/83ccbe47-bf59-4ec0-b4c9-592ba9c4ad1b)

Generated AnimateDiff video
![01_27748780903300_masterpiece_best-quality_no-humans_blue-sky_white-cloud_outdoors](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/8006000/e8c9fc77-eba8-4cdd-a0a8-d51088bc668a)

animatediff-cli-prompt-travel  result
![ezgif com-gif-maker](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/8006000/85d145a2-95fb-4d2f-b621-b121bd851b74)

Generated AnimateDiff video
![00_24834798825700_masterpiece_best-quality_1girl_solo_blonde-hair_blue-eyes](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/8006000/adce7094-3dae-492b-bf76-35ba1e1209bb)

json config
![image](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/8006000/f497ae93-a9fb-4af1-ae79-1568180edb5d)

**Comment by s9roll7** [comment]
SAM was provided as a preprocessor for seg in controlnet_aux, so I'm using that.
https://github.com/facebookresearch/segment-anything

**Comment by s9roll7** [comment]
As for the different labeled colors, I guess it's okay because it doesn't seem to have any effect as far as the output results are concerned.

**Comment by toyxyz** [comment]
As far as I know, the Seg controlnet model is trained with matching objects for each color. If there is a prompt that matches the color entered (e.g. person -150, 5, 61), ControlNet focuses the prompt on the location of that color, otherwise it simply separates the boundary. 

Color list : https://docs.google.com/spreadsheets/d/1se8YEtb2detS7OuPE86fXGyD269pMycAWe2mtKUj2W8/edit#gid=0
![image](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/8006000/a8d9d053-62de-4969-8924-09ebabf196f4)


> As for the different labeled colors, I guess it's okay because it doesn't seem to have any effect as far as the output results are concerned.

**Comment by s9roll7** [comment]
35c3aae

**Comment by toyxyz** [comment]
> [35c3aae](https://github.com/s9roll7/animatediff-cli-prompt-travel/commit/35c3aaebb8f3421c50f70fcb61e734ab058598c9)

It works perfectly. thanks!

![image](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/8006000/92d663fc-939b-4d06-9d07-57b16ded1af2)

![image](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/8006000/d2629b92-c519-4843-9e50-a29b57ef9154)
![00_30309496704100_masterpiece_best-quality_street_no-humans_city_building](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/8006000/2bf160f6-d2ea-49be-b3aa-1ab0296c621d)
