### ISSUE TITLE
Hello, why can’t my LORAS be loaded correctly?

### ISSUE THREAD

**Issue by shenshen246** [s9roll7/animatediff-cli-prompt-travel#113]
Hello, why can’t my LORAS be loaded correctly?

"n_prompt": [
        " nsfw,lowres,bad anatomy,bad hands,text,error,missing fingers,extra digit,fewer digits,cropped,worst quality,low quality,normal quality,jpeg artifacts,signature,watermark,username,blurry,bad feet,easynegative(worst quality:2),(low quality:2),(normal quality:2),lowres,normal quality,skin spots,acnes,skin blemishes,age spot,(ugly:1.33),(duplicate:1.33),(morbid:1.21),(mutilated:1.21),(tranny:1.33),mutated hands,(poorly drawn hands:1.5),blurry,(bad anatomy:1.21),(bad proportions:1.33),extra limbs,(disfigured:1.33),(missing arms:1.33),(extra legs:1.33),(fused fingers:1.61),(too many fingers:1.61),(unclear eyes:1.33),lowers,bad hands,missing fingers,extra digit,bad hands,missing fingers,(((extra arms and legs))),():1.2,(EasyNegative):1.2,bad-hands-5,bad_pictures,badhandv4,negative_hand-neg,ng_deepnegative_v1_75t,nevus,freckles"
    ],
    "lora_map": {
        "share/Lora/CGgufeng3.0.safetensors": 1.0,
        "share/Lora/add_detail.safetensors": 1.0
    },
    "ip_adapter_map": {
        "enable": true,
        "input_image_dir": "ip_adapter_image/test",
        "save_input_image": true,
        "resized_to_square": false,
        "scale": 0.45,
        "is_plus_face": true,
        "is_plus": true
    },
    "controlnet_map": {
        "input_image_dir": "..\\stylize\\2023-10-15T21-03-44-sample-cggufeng4.0-2.8d\\00_controlnet_image",
        "max_samples_on_vram": 200,
        "max_models_on_vram": 3,
        "save_detectmap": true,
        "preprocess_on_gpu": true,
        "is_loop": false,
        "controlnet_tile": {
            "enable":  false,
            "use_preprocessor": true,
            "guess_mode": false,
            "controlnet_conditioning_scale": 1.0,
            "control_guidance_start": 0.0,
            "control_guidance_end": 1.0,
            "control_scale_list": []

**Comment by shenshen246** [comment]
PS F:\diff\animatediff-cli-prompt-travel-main> animatediff stylize generate stylize\2023-10-15T21-03-44-sample-cggufeng4.0-2.8d -L 32
Error in sitecustomize; set PYTHONVERBOSE for traceback:
NameError: name 'os' is not defined
05:00:26 INFO     Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.                           utils.py:148
         INFO     NumExpr defaulting to 8 threads.                                                                                           utils.py:160
         INFO     Using generation config: stylize\2023-10-15T21-03-44-sample-cggufeng4.0-2.8d\prompt.json                                     cli.py:288
05:00:27 INFO     is_v2=True                                                                                                                  util.py:323
         INFO     Using base model: runwayml\stable-diffusion-v1-5                                                                             cli.py:306
         INFO     Will save outputs to ./stylize\2023-10-15T21-03-44-sample-cggufeng4.0-2.8d\2023-10-16T05-00-27-sample-xxmix9realistic_v40.   cli.py:314
Preprocessing images (controlnet_openpose)   0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/128  [ 0:00:00 < -:--:-- , ? it/s ]2023-10-16 05:00:29.0090648 [W:onnxruntime:, session_state.cc:1136 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-10-16 05:00:29.0138082 [W:onnxruntime:, session_state.cc:1138 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
Preprocessing images (controlnet_openpose)  24% ━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31/128  [ 0:00:14 < 0:00:06 , 18 it/s ]
Saving Preprocessed images (controlnet_openpose)  75% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━ 24/32  [ 0:00:00 < 0:00:01 , 128 it/s ]
Preprocessing images (ip_adapter)  24% ━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31/128  [ 0:00:00 < 0:00:02 , 70 it/s ]
Saving Preprocessed images (ip_adapter)  53% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17/32  [ 0:00:00 < -:--:-- , ? it/s ]
05:00:43 INFO     Checking motion module...                                                                                               generate.py:281
         INFO     Loading tokenizer...                                                                                                    generate.py:295
         INFO     Loading text encoder...                                                                                                 generate.py:297
05:00:44 INFO     Loading VAE...                                                                                                          generate.py:299
         INFO     Loading UNet...                                                                                                         generate.py:301
05:00:50 INFO     Loaded 453.20928M-parameter motion module                                                                                   unet.py:578
         INFO     Using scheduler "euler_a" (EulerAncestralDiscreteScheduler)                                                             generate.py:313
         INFO     Loading weights from F:\diff\animatediff-cli-prompt-travel-main\data\models\sd\xxmix9realistic_v40..safetensors         generate.py:318
05:00:53 INFO     Merging weights into UNet...                                                                                            generate.py:335
         INFO     Creating AnimationPipeline...                                                                                           generate.py:362
         INFO     Loading 4 TI embeddings...                                                                                                    ti.py:105
05:00:54 INFO     Loaded 4 embeddings, 0 existing, 0 failed                                                                                     ti.py:122
         INFO     Available embeddings: badhandv4, bad_pictures, negative_hand-neg, ng_deepnegative_v1_75t                                      ti.py:123
05:00:55 INFO     loading c='controlnet_openpose' model                                                                                   generate.py:391
         INFO     Sending pipeline to device "cuda"                                                                                        pipeline.py:22
05:00:56 INFO     Selected data types: unet_dtype=torch.float16, tenc_dtype=torch.float16, vae_dtype=torch.bfloat16                          device.py:90
         INFO     Using channels_last memory format for UNet and VAE                                                                        device.py:111
05:01:02 INFO     Saving prompt config to output directory                                                                                     cli.py:367
         INFO     Initialization complete!                                                                                                     cli.py:375
         INFO     Generating 1 animations                                                                                                      cli.py:376
         INFO     Running generation 1 of 1                                                                                                    cli.py:386
         INFO     Generation seed: 1801980918                                                                                                  cli.py:392
Token indices sequence length is longer than the specified maximum sequence length for this model (142 > 77). Running this sequence through the model will result in indexing errors
05:01:07 WARNING  Prompt was truncated. Try to shorten the prompt or increase max_embeddings_multiples                        lpw_stable_diffusion.py:166

**Comment by shenshen246** [comment]
Could you please help me take a look? Thanks

**Comment by s9roll7** [comment]
```
  "lora_map": {             # "PATH_TO_LORA" : STRENGTH format
    "share/Lora/muffet_v2.safetensors" : 1.0,                     # Specify lora as a path relative to /animatediff-cli/data
    "share/Lora/add_detail.safetensors" : 1.0                     # Lora support is limited. Not all formats can be used!!!
  },
```

F:\diff\animatediff-cli-prompt-travel-main\data\share\Lora\CGgufeng3.0.safetensors
Are you sure lora is placed here?

**Comment by shenshen246** [comment]
> ```
>   "lora_map": {             # "PATH_TO_LORA" : STRENGTH format
>     "share/Lora/muffet_v2.safetensors" : 1.0,                     # Specify lora as a path relative to /animatediff-cli/data
>     "share/Lora/add_detail.safetensors" : 1.0                     # Lora support is limited. Not all formats can be used!!!
>   },
> ```
> 
> F:\diff\animatediff-cli-prompt-travel-main\data\share\Lora\CGgufeng3.0.safetensors 你确定lora放在这里吗？

Thank you, solved

**Comment by shenshen246** [comment]
> ```
>   "lora_map": {             # "PATH_TO_LORA" : STRENGTH format
>     "share/Lora/muffet_v2.safetensors" : 1.0,                     # Specify lora as a path relative to /animatediff-cli/data
>     "share/Lora/add_detail.safetensors" : 1.0                     # Lora support is limited. Not all formats can be used!!!
>   },
> ```
> 
> F:\diff\animatediff-cli-prompt-travel-main\data\share\Lora\CGgufeng3.0.safetensors 你确定lora放在这里吗？

But a new problem has arisen. There seems to be a problem when loading LORA.

create LoRA network
create LoRA network from weights
create LoRA for Text Encoder: 72 modules.
skipped lora_unet_down_blocks_0_resnets_0_time_emb_proj (not found in modules_dim)
skipped lora_unet_down_blocks_0_resnets_1_time_emb_proj (not found in modules_dim)
skipped lora_unet_down_blocks_1_resnets_0_time_emb_proj (not found in modules_dim)
skipped lora_unet_down_blocks_1_resnets_1_time_emb_proj (not found in modules_dim)
skipped lora_unet_down_blocks_2_resnets_0_time_emb_proj (not found in modules_dim)
skipped lora_unet_down_blocks_2_resnets_1_time_emb_proj (not found in modules_dim)
skipped lora_unet_down_blocks_3_resnets_0_time_emb_proj (not found in modules_dim)
skipped lora_unet_down_blocks_3_resnets_1_time_emb_proj (not found in modules_dim)
skipped lora_unet_up_blocks_0_resnets_0_time_emb_proj (not found in modules_dim)
skipped lora_unet_up_blocks_0_resnets_1_time_emb_proj (not found in modules_dim)
skipped lora_unet_up_blocks_0_resnets_2_time_emb_proj (not found in modules_dim)
skipped lora_unet_up_blocks_1_resnets_0_time_emb_proj (not found in modules_dim)
skipped lora_unet_up_blocks_1_resnets_1_time_emb_proj (not found in modules_dim)
skipped lora_unet_up_blocks_1_resnets_2_time_emb_proj (not found in modules_dim)
skipped lora_unet_up_blocks_2_resnets_0_time_emb_proj (not found in modules_dim)
skipped lora_unet_up_blocks_2_resnets_1_time_emb_proj (not found in modules_dim)
skipped lora_unet_up_blocks_2_resnets_2_time_emb_proj (not found in modules_dim)
skipped lora_unet_up_blocks_3_resnets_0_time_emb_proj (not found in modules_dim)
skipped lora_unet_up_blocks_3_resnets_1_time_emb_proj (not found in modules_dim)
skipped lora_unet_up_blocks_3_resnets_2_time_emb_proj (not found in modules_dim)
skipped lora_unet_mid_block_resnets_0_time_emb_proj (not found in modules_dim)
skipped lora_unet_mid_block_resnets_1_time_emb_proj (not found in modules_dim)
create LoRA for U-Net: 192 modules.
skipped 22 modules because of missing weight.
load LoRA network weights
merge LoRA weights to original weights
100%|███████████████████████████████████████████████████████████████████████████████| 264/264 [00:01<00:00, 210.67it/s]
weights are merged
01:16:58 INFO     Loading lora                                                                           generate.py:357
                  F:\diff\animatediff-cli-prompt-travel-main\data\models\sd\add_detail.safetensors
         INFO     alpha = 0.6                                                                            generate.py:358
create LoRA network
create LoRA network from weights
create LoRA for Text Encoder: 72 modules.
skipped lora_unet_down_blocks_0_resnets_0_time_emb_proj (not found in modules_dim)
skipped lora_unet_down_blocks_0_resnets_1_time_emb_proj (not found in modules_dim)
skipped lora_unet_down_blocks_1_resnets_0_time_emb_proj (not found in modules_dim)
skipped lora_unet_down_blocks_1_resnets_1_time_emb_proj (not found in modules_dim)
skipped lora_unet_down_blocks_2_resnets_0_time_emb_proj (not found in modules_dim)
skipped lora_unet_down_blocks_2_resnets_1_time_emb_proj (not found in modules_dim)
skipped lora_unet_down_blocks_3_resnets_0_time_emb_proj (not found in modules_dim)
skipped lora_unet_down_blocks_3_resnets_1_time_emb_proj (not found in modules_dim)
skipped lora_unet_up_blocks_0_resnets_0_time_emb_proj (not found in modules_dim)
skipped lora_unet_up_blocks_0_resnets_1_time_emb_proj (not found in modules_dim)
skipped lora_unet_up_blocks_0_resnets_2_time_emb_proj (not found in modules_dim)
skipped lora_unet_up_blocks_1_resnets_0_time_emb_proj (not found in modules_dim)
skipped lora_unet_up_blocks_1_resnets_1_time_emb_proj (not found in modules_dim)
skipped lora_unet_up_blocks_1_resnets_2_time_emb_proj (not found in modules_dim)
skipped lora_unet_up_blocks_2_resnets_0_time_emb_proj (not found in modules_dim)
skipped lora_unet_up_blocks_2_resnets_1_time_emb_proj (not found in modules_dim)
skipped lora_unet_up_blocks_2_resnets_2_time_emb_proj (not found in modules_dim)
skipped lora_unet_up_blocks_3_resnets_0_time_emb_proj (not found in modules_dim)
skipped lora_unet_up_blocks_3_resnets_1_time_emb_proj (not found in modules_dim)
skipped lora_unet_up_blocks_3_resnets_2_time_emb_proj (not found in modules_dim)
skipped lora_unet_mid_block_resnets_0_time_emb_proj (not found in modules_dim)
skipped lora_unet_mid_block_resnets_1_time_emb_proj (not found in modules_dim)
create LoRA for U-Net: 192 modules.
skipped 22 modules because of missing weight.
load LoRA network weights
merge LoRA weights to original weights

**Comment by s9roll7** [comment]
That log is confusing, but never mind.
It's normal.
