### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by qigaode** [s9roll7/animatediff-cli-prompt-travel#117]
![image](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/43092977/2825d6a2-8c68-45b4-b21e-5a3795663c68)

Setting "ip_adapter_map" to false will not cause this problem.

**Comment by s9roll7** [comment]
Rename to "frame_number.png"
e.g.). 0000.png
