### ISSUE TITLE
Adding ip-adapter_sd15_light.bin

### ISSUE THREAD

**Issue by darkcurrent** [s9roll7/animatediff-cli-prompt-travel#118]
I think adding [ip-adapter_sd15_light.bin](https://huggingface.co/h94/IP-Adapter/blob/main/models/ip-adapter_sd15_light.bin) is very important for most applications. Could you add one more elif statement for the new adapter?

https://github.com/s9roll7/animatediff-cli-prompt-travel/blob/9d0e1334f8dafbf928298e10a25643d8a66ba20f/src/animatediff/pipelines/animation.py#L1866

**Comment by s9roll7** [comment]
[7d63018](https://github.com/s9roll7/animatediff-cli-prompt-travel/commit/7d630185280193e1c6493f255f627d8b10a5b2ab)
