### ISSUE TITLE
Suggestion: More stats needed after Running generation

### ISSUE THREAD

**Issue by SoftologyPro** [s9roll7/animatediff-cli-prompt-travel#121]
Any chance you can put some extra stats between the 
`Running generation 1 of 1`
end and the
`Saving frames to`
step?
The more frames you generate and the larger the size the longer the delay with no stats occurs there.
For example I am running an HD movie.  The running generation took 24 hours to do 5600 frames but since then the GPU is at 100% for 17 hours more.  What is happening?  Another simple progress bar there would really help.
Edit: it just crashed with OOM.  Any chance of detecting that before I spend 42 hours of GPU time and electricity would help too.
Is that possible?

**Comment by s9roll7** [comment]
The latest update includes memory-related improvements and speed improvements in certain settings.
It should be less likely to cause OOM.

**Comment by SoftologyPro** [comment]
My main request was for the stats though.
When doing larger/longer movies it really needs stats between the 2 parts I showed in my original post.
