### ISSUE TITLE
Suggestion: Save frames as it goes, rather than all at the end

### ISSUE THREAD

**Issue by SoftologyPro** [s9roll7/animatediff-cli-prompt-travel#122]
How it works now is to generate all frames into memory, then save them all to disk, then combine into the output.
Could it be changed to save frames as it goes?  This gives 2 advantages;
1. User can see what the output looks like and abort if the results are not good.
2. If an OOM memory crash occurs then the frames up to that point are saved.  Although changing it to save as it goes will n ot use as much memory because it does not keep the frames all in VRAM as it runs.

**Comment by s9roll7** [comment]
#35

**Comment by JCBrouwer** [comment]
We _can_ actually save approximate intermediate frames with a little elbow grease.

AnimateDiff was trained with the [epsilon diffusion objective](https://github.com/guoyww/AnimateDiff/blob/main/train.py#L369) so the UNet is predicting the noise that was added to the data.

That means that the [`noise_pred` variable here](https://github.com/s9roll7/animatediff-cli-prompt-travel/blob/main/src/animatediff/pipelines/animation.py#L2496) can be subtracted from `latents` (just before the scheduler step) to get what the UNet currently predicts to be the correct latent.

If we decode these latents with the VAE we have a preview of the video!

It will slow down overall sampling time quite significantly to do this often, but can be very worth it for drafting long videos.

**Comment by SoftologyPro** [comment]
It would be great if possible.  My main request I get from users who are trying it in Visions of Chaos is for some way to see progress.  Even if it was much slower, the user could turn it on, let it get past the first 20 frames or so, check the results and only then if it looked good they can turn off preview frames and run again faster.
