### ISSUE TITLE
controlnet_ref is not available in this configuration

### ISSUE THREAD

**Issue by edwinzeng2005** [s9roll7/animatediff-cli-prompt-travel#129]
Previously, I was able to get tile-resample with reference-only working.
Now it gave an error instead.

ValueError: controlnet_ref is not available in this configuration. unet_batch_size=1 < 2

Traceback:
> 
│ /opt/conda/lib/python3.10/site-packages/animatediff/cli.py:392 in generate                       
│                                                                                                  
│    389 │   │   │   logger.info(f"Generation seed: {seed}")                                       
│    390 │   │   │                                                                                 
│    391 │   │   │                                                                                 
│ ❱  392 │   │   │   output = run_inference(                                                       
│    393 │   │   │   │   pipeline=g_pipeline,                                                      
│    394 │   │   │   │   n_prompt=n_prompt,                                                        
│    395 │   │   │   │   seed=seed,                                                                
│                                                                                                  
│ /opt/conda/lib/python3.10/site-packages/animatediff/generate.py:1133 in run_inference            
│                                                                                                  
│   1130 │   logger.info(f"{len( region_list )=}")                                                 
│   1131 #    logger.info(f"{region_list=}")                                                       
│   1132 │                                                                                         
│ ❱ 1133 │   pipeline_output = pipeline(                                                           
│   1134 │   │   negative_prompt=n_prompt,                                                         
│   1135 │   │   num_inference_steps=steps,                                                        
│   1136 │   │   guidance_scale=guidance_scale,                                                    
│                                                                                                  
│ /opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py:115 in decorate_context       
│                                                                                                  
│   112 │   @functools.wraps(func)                                                                 
│   113 │   def decorate_context(*args, **kwargs):                                                 
│   114 │   │   with ctx_factory():                                                                
│ ❱ 115 │   │   │   return func(*args, **kwargs)                                                   
│   116 │                                                                                          
│   117 │   return decorate_context                                                                
│   118                                                                                            
│                                                                                                  
│ /opt/conda/lib/python3.10/site-packages/animatediff/pipelines/animation.py:2313 in __call__      
│                                                                                                  
│   2310 │   │                                                                                     
│   2311 │   │   if controlnet_ref_map is not None:                                                
│   2312 │   │   │   if unet_batch_size < prompt_encoder.get_condi_size():                         
│ ❱ 2313 │   │   │   │   raise ValueError(f"controlnet_ref is not available in this configuration

**Comment by s9roll7** [comment]
In the latest version, unet_batch_size has been added to reduce VRAM consumption, but with the default of 1, controlnet_ref is not available.
It is recommended to use the ip adapter instead of controlnet_ref.

unet_batch_size=1 < 2

In this case, setting unet_batch_size=2 will restore the previous behavior, but will also restore the vram consumption.


```
{
    "name": "sample",
    "path": "share\\Stable-diffusion\\mistoonAnime_v20.safetensors",
    "vae_path": "",
    "motion_module": "models\\motion-module\\mm_sd_v15_v2.ckpt",
    "compile": false,
    "tensor_interpolation_slerp": true,
    "seed": [
        341774366206100
    ],
    "scheduler": "k_dpmpp_sde",
    "steps": 20,
    "guidance_scale": 10.0,
    "unet_batch_size": 1,        # <--------------
    "clip_skip": 2,

```
