### ISSUE TITLE
An error occurs when creating more than one video using a preprocessor.

### ISSUE THREAD

**Issue by toyxyz** [s9roll7/animatediff-cli-prompt-travel#13]
An error occurs when creating more than one video using a preprocessor.
I tested 2 types of line art_anime and soft edge. 1 video saves normally, no error occurs, but raising -r to 2 or higher results in an error.\
Images processed by the preprocessor are also saved normally.

![image](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/8006000/9c3e0949-999b-45e0-ad8b-5a237726f746)
![image](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/8006000/ca58822e-73da-464c-b51c-f661ed13993b)
![image](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/8006000/a3ef458b-9a4d-4fd0-ab96-fe0b59c1b71f)

Preprocessing images (controlnet_lineart_anime)   0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/2  [ 0:00:00 < -:--:-- , ? it/s ]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\toyxy\animatediff-cli-prompt-travel\src\animatediff\cli.py:363 in generate              │
│                                                                                                  │
│   360 │   │   │   │   if int(k) < length:                                                        │
│   361 │   │   │   │   │   prompt_map[int(k)]=model_config.prompt_map[k]                          │
│   362 │   │   │                                                                                  │
│ ❱ 363 │   │   │   output = run_inference(                                                        │
│   364 │   │   │   │   pipeline=pipeline,                                                         │
│   365 │   │   │   │   prompt="this is dummy string",                                             │
│   366 │   │   │   │   n_prompt=n_prompt,                                                         │
│                                                                                                  │
│ C:\Users\toyxy\animatediff-cli-prompt-travel\src\animatediff\generate.py:472 in run_inference    │
│                                                                                                  │
│   469 │   │   │   │   │   │   │   if frame_no < duration:                                        │
│   470 │   │   │   │   │   │   │   │   if frame_no not in controlnet_image_map:                   │
│   471 │   │   │   │   │   │   │   │   │   controlnet_image_map[frame_no] = {}                    │
│ ❱ 472 │   │   │   │   │   │   │   │   controlnet_image_map[frame_no][c] = get_preprocessed_img   │
│   473 │   │   │   │   │   │   │   │   processed = True                                           │
│   474 │   │   │                                                                                  │
│   475 │   │   │   if save_detectmap and processed:                                               │
│                                                                                                  │
│ C:\Users\toyxy\animatediff-cli-prompt-travel\src\animatediff\generate.py:172 in                  │
│ get_preprocessed_img                                                                             │
│                                                                                                  │
│   169 │   if type_str in ( "controlnet_tile", "controlnet_ip2p", "controlnet_inpaint"):          │
│   170 │   │   return img                                                                         │
│   171 │   else:                                                                                  │
│ ❱ 172 │   │   return get_preprocessor(type_str, device_str)(img) if use_preprocessor else img    │
│   173                                                                                            │
│   174                                                                                            │
│   175                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: 'NoneType' object is not callable

**Comment by s9roll7** [comment]
7d0ecb0
