### ISSUE TITLE
Question about region_prompt

### ISSUE THREAD

**Issue by alanhuang67** [s9roll7/animatediff-cli-prompt-travel#133]
Hi,

in the region_map setup, how can I understand and use the setting below? for example, if I setup a man dancing with mask, and it seems like the background will be impact by initial images background, is thie one I can ignore the orgional background and re-create the background base on the root prompt (the top one)? thanks!

    "background":{
      "is_init_img" : false,
      "hint" : "background's condition refers to the one in root"
    }

**Comment by s9roll7** [comment]
The hint mean the following
```
  "prompt_fixed_ratio": 0.5,         <----------------- background setting
  "head_prompt": "(style of studio ghibli:1.2), (masterpiece, best quality)",         <----------------- background setting
  "prompt_map": {         <----------------- background setting
    "0":  "town, outdoors,"
  },
  "tail_prompt": "",         <----------------- background setting
  "n_prompt": [
    "(worst quality:2), (bad quality:2), (normal quality:2), lowers, bad anatomy, bad hands, (multiple views),"
  ],
  "lora_map": {
  },
  "motion_lora_map": {
  },
  "ip_adapter_map": {                    <----------------- background setting
      "enable": true,
      "input_image_dir": "ip_adapter_image/cyberpunk",
      "prompt_fixed_ratio": 0.5,
      "save_input_image": true,
      "resized_to_square": false,
      "scale": 0.5,
      "is_plus_face": false,
      "is_plus": true,
      "is_light": false
  },
```



```
  "region_map" : {
    "0":{                            <---------------  region 0 setting
      "enable": true,
      "crop_generation_rate": 0.1,
      "mask_dir" : "mask/area0",
      "save_mask": true,
      "is_init_img" : false,
      "condition":{
        "prompt_fixed_ratio": 1.0,
        "head_prompt": "",
        "prompt_map": {
          "0": "((standing)),1girl, upper body,",
          "8": "((smile)),1girl, upper body,",
          "16": "(((arms_up))),1girl, upper body, ",
          "24": "(((waving ))),1girl, upper body"
        },
        "tail_prompt": "(style of studio ghibli:1.2), (masterpiece, best quality)",
        "ip_adapter_map": {
          "enable": true,
          "input_image_dir": "ip_adapter_image/girl",
          "prompt_fixed_ratio": 0.5,
          "save_input_image": true,
          "resized_to_square": false
        }
      }
    },
    "1":{                          <---------------  region 1 setting
      "enable": true,
      "crop_generation_rate": 0.1,
      "mask_dir" : "mask/area1",
      "save_mask": true,
      "is_init_img" : false,
      "condition":{
        "prompt_fixed_ratio": 0.5,
        "head_prompt": "((car)),(style of studio ghibli:1.2), (masterpiece, best quality)",
        "prompt_map": {
          "0": "street, road,no human"
        },
        "tail_prompt": "",
        "ip_adapter_map": {
          "enable": true,
          "input_image_dir": "ip_adapter_image/cyberpunk",
          "prompt_fixed_ratio": 0.5,
          "save_input_image": true,
          "resized_to_square": false
        }
      }
    },
    "background":{
      "is_init_img" : false,
      "hint" : "background's condition refers to the one in root"
    }
  },
```

> if I setup a man dancing with mask, and it seems like the background will be impact by initial images background

If you disable img2img, it will not be affected.
```
  "img2img_map":{
    "enable": false,
    "init_img_dir" : "init_imgs/sample1",
    "save_init_image": true,
    "denoising_strength" : 0.7
  },
```

**Comment by alanhuang67** [comment]
Thans so much for this, I reall love this project!
May I understand that if I want to have clear background(totally base on prompt), I can set the init image as the man dance and green background?(generate by mask commend?

**Comment by s9roll7** [comment]
> Thans so much for this, I reall love this project! May I understand that if I want to have clear background(totally base on prompt), I can set the init image as the man dance and green background?(generate by mask commend?

I think you should get only the dance motion using controlnet_openpose and disable img2img.

> @s9roll7 one more question, is it possible to have 1 lora only affect to region without affect background?

Although it is not completely possible, it may be possible to control it to some extent by inserting a trigger word only in a specific region.
It is better to use ip_adapter because it can be set completely by region.

**Comment by s9roll7** [comment]
background prompt text ... ((aura)), effects, power
region 0 prompt text ... ChunLi, etc
lora ... ChunLi_v1.safetensors
ip_adapter_map input image for background
![00000000](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/118420657/67aaf008-ec77-4087-8678-ae4afb1e7bee)
ip_adapter_map input image for region 0
![00000000](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/118420657/6a22a634-3923-4e3a-822e-d35edec76a19)

region 0 mask
<div><video controls src="https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/118420657/6bf456ad-05c6-42cf-a183-34d918b989ee" muted="false"></video></div>
<br>

src / img2img denoising_strength 0.5 / img2img denoising_strength 0.75

<div><video controls src="https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/118420657/2e726e74-c16e-4024-a6e0-d7181c0132b1" muted="false"></video></div>
<br>

**Comment by alanhuang67** [comment]
LOOKS COOL! Thanks I'll try!!!

**Comment by alanhuang67** [comment]
may I gess the above image still have  img2img enabled but set an ip-adapter image with higher denoising_strength 0.75?
in above case if there is no img2img setting and only openpose/ip-adapter enabled, what will happened?
@s9roll7

**Comment by xizaoqu** [comment]
> LOOKS COOL! Thanks I'll try!!!

super cool!
