### ISSUE TITLE
img2img only works at specific frames

### ISSUE THREAD

**Issue by 333caowei** [s9roll7/animatediff-cli-prompt-travel#135]
conf file is as below:

{
  "name": "game1",
  "path": "models/sd/awportrait_v12.safetensors",
  "motion_module": "models/motion-module/mm_sd_v15_v2.ckpt",
  "compile": false,
  "seed": [
    10788741199826055000, 6520604954829637000, 6519455744612556000,
    16372571278361864000
  ],
  "scheduler": "dpmpp_2m_sde",
  "steps": 25,
  "guidance_scale": 7,
  "clip_skip": 2,
  "prompt_fixed_ratio": 0.5,
  "head_prompt": "masterpiece, best quality",
  "prompt_map": {
    "0":   "a girl holding a big strawberry",
    "5":   "a girl holding a big strawberry",
    "10":   "a girl holding a big strawberry",
    "15":  "a girl holding a big strawberry",
    "20":   "a girl holding a big strawberry",
    "25":   "a girl holding a big strawberry",
    "30":  "a girl holding a big strawberry",
    "35":   "a girl holding a big strawberry",
    "40":   "a girl holding a big strawberry"
  },
  "tail_prompt": "",
  "n_prompt": [
    "worst quality, low quality, cropped, lowres, text, jpeg artifacts, multiple view"
  ],
  "motion_lora_map": {
  },
  "img2img_map":{
    "enable": true,
    "init_img_dir" : "init_imgs/mytest",
    "save_init_image": true,
    "denoising_strength" : 0.3
  },
    "output":{
    "format" : "gif",
    "fps" : 8,
    "encode_param":{
      "crf": 10
    }
  }
}

I put 10 same files in init_imgs/mytest:
![00347-2553730904-one green strawberry and one large juicy strawberry,this is the biggest strawberry a beautiful young lady can hold,in the style](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/4569055/8fc99773-519b-4936-b448-8824eb63f02a)
<img width="206" alt="image" src="https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/4569055/8ad8e4d7-f4aa-42e4-a125-5b288e17c358">

the output of model is：
![00_10788741199826055000_masterpiece_best-quality_a-girl-holding-a-big-stra](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/4569055/71301742-92c6-4801-b93b-7402b1960674)

I find only specific frames is related to the img2img image, the other frames shows like noise, Am I doing something wrong?
<img width="867" alt="image" src="https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/4569055/b59e4013-8848-471d-9c39-daa698cf189f">

**Comment by s9roll7** [comment]
Thanks for the report.
This is a spec.
The img2img is implemented for v2v, so it is assumed that all frames are supplied.
I think what you are trying to do can be achieved with controlnet_tile
