### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by alanhuang67** [s9roll7/animatediff-cli-prompt-travel#137]
Hi, I got some error after update, message below, do you know anything happened?

         INFO     Loading weights from                                                                   generate.py:368
                  D:\animatediff-cli-prompt-travel\data\models\sd\link\Stable-diffusion\SD1.5_anime\mist
                  oonAnime_v20.safetensors
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\animatediff-cli-prompt-travel\venv\lib\site-packages\urllib3\connection.py:174 in _new_conn   │
│                                                                                                  │
│   171 │   │   │   extra_kw["socket_options"] = self.socket_options                               │
│   172 │   │                                                                                      │
│   173 │   │   try:                                                                               │
│ ❱ 174 │   │   │   conn = connection.create_connection(                                           │
│   175 │   │   │   │   (self._dns_host, self.port), self.timeout, **extra_kw                      │
│   176 │   │   │   )                                                                              │
│   177                                                                                            │
│                                                                                                  │
│ D:\animatediff-cli-prompt-travel\venv\lib\site-packages\urllib3\util\connection.py:72 in         │
│ create_connection                                                                                │
│                                                                                                  │
│    69 │   │   │   LocationParseError(u"'%s', label empty or too long" % host), None              │
│    70 │   │   )                                                                                  │
│    71 │                                                                                          │
│ ❱  72 │   for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):                 │
│    73 │   │   af, socktype, proto, canonname, sa = res                                           │
│    74 │   │   sock = None                                                                        │
│    75 │   │   try:                                                                               │
│                                                                                                  │
│ C:\Users\Alan\AppData\Local\Programs\Python\Python310\lib\socket.py:955 in getaddrinfo           │
│                                                                                                  │
│   952 │   # We override this function since we want to translate the numeric family              │
│   953 │   # and socket type values to enum constants.                                            │
│   954 │   addrlist = []                                                                          │
│ ❱ 955 │   for res in _socket.getaddrinfo(host, port, family, type, proto, flags):                │
│   956 │   │   af, socktype, proto, canonname, sa = res                                           │
│   957 │   │   addrlist.append((_intenum_converter(af, AddressFamily),                            │
│   958 │   │   │   │   │   │    _intenum_converter(socktype, SocketKind),                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
gaierror: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\animatediff-cli-prompt-travel\venv\lib\site-packages\urllib3\connectionpool.py:703 in urlopen │
│                                                                                                  │
│    700 │   │   │   │   self._prepare_proxy(conn)                                                 │
│    701 │   │   │                                                                                 │
│    702 │   │   │   # Make the request on the httplib connection object.                          │
│ ❱  703 │   │   │   httplib_response = self._make_request(                                        │
│    704 │   │   │   │   conn,                                                                     │
│    705 │   │   │   │   method,                                                                   │
│    706 │   │   │   │   url,                                                                      │
│                                                                                                  │
│ D:\animatediff-cli-prompt-travel\venv\lib\site-packages\urllib3\connectionpool.py:386 in         │
│ _make_request                                                                                    │
│                                                                                                  │
│    383 │   │                                                                                     │
│    384 │   │   # Trigger any extra validation we need to do.                                     │
│    385 │   │   try:                                                                              │
│ ❱  386 │   │   │   self._validate_conn(conn)                                                     │
│    387 │   │   except (SocketTimeout, BaseSSLError) as e:                                        │
│    388 │   │   │   # Py2 raises this as a BaseSSLError, Py3 raises it as socket timeout.         │
│    389 │   │   │   self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)               │
│                                                                                                  │
│ D:\animatediff-cli-prompt-travel\venv\lib\site-packages\urllib3\connectionpool.py:1042 in        │
│ _validate_conn                                                                                   │
│                                                                                                  │
│   1039 │   │                                                                                     │
│   1040 │   │   # Force connect early to allow us to validate the connection.                     │
│   1041 │   │   if not getattr(conn, "sock", None):  # AppEngine might not have  `.sock`          │
│ ❱ 1042 │   │   │   conn.connect()                                                                │
│   1043 │   │                                                                                     │
│   1044 │   │   if not conn.is_verified:                                                          │
│   1045 │   │   │   warnings.warn(                                                                │
│                                                                                                  │
│ D:\animatediff-cli-prompt-travel\venv\lib\site-packages\urllib3\connection.py:358 in connect     │
│                                                                                                  │
│   355 │                                                                                          │
│   356 │   def connect(self):                                                                     │
│   357 │   │   # Add certificate verification                                                     │
│ ❱ 358 │   │   self.sock = conn = self._new_conn()                                                │
│   359 │   │   hostname = self.host                                                               │
│   360 │   │   tls_in_tls = False                                                                 │
│   361                                                                                            │
│                                                                                                  │
│ D:\animatediff-cli-prompt-travel\venv\lib\site-packages\urllib3\connection.py:186 in _new_conn   │
│                                                                                                  │
│   183 │   │   │   )                                                                              │
│   184 │   │                                                                                      │
│   185 │   │   except SocketError as e:                                                           │
│ ❱ 186 │   │   │   raise NewConnectionError(                                                      │
│   187 │   │   │   │   self, "Failed to establish a new connection: %s" % e                       │
│   188 │   │   │   )                                                                              │
│   189                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001713386BCA0>: Failed to establish a new
connection: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\animatediff-cli-prompt-travel\venv\lib\site-packages\requests\adapters.py:489 in send         │
│                                                                                                  │
│   486 │   │                                                                                      │
│   487 │   │   try:                                                                               │
│   488 │   │   │   if not chunked:                                                                │
│ ❱ 489 │   │   │   │   resp = conn.urlopen(                                                       │
│   490 │   │   │   │   │   method=request.method,                                                 │
│   491 │   │   │   │   │   url=url,                                                               │
│   492 │   │   │   │   │   body=request.body,                                                     │
│                                                                                                  │
│ D:\animatediff-cli-prompt-travel\venv\lib\site-packages\urllib3\connectionpool.py:787 in urlopen │
│                                                                                                  │
│    784 │   │   │   elif isinstance(e, (SocketError, HTTPException)):                             │
│    785 │   │   │   │   e = ProtocolError("Connection aborted.", e)                               │
│    786 │   │   │                                                                                 │
│ ❱  787 │   │   │   retries = retries.increment(                                                  │
│    788 │   │   │   │   method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]           │
│    789 │   │   │   )                                                                             │
│    790 │   │   │   retries.sleep()                                                               │
│                                                                                                  │
│ D:\animatediff-cli-prompt-travel\venv\lib\site-packages\urllib3\util\retry.py:592 in increment   │
│                                                                                                  │
│   589 │   │   )                                                                                  │
│   590 │   │                                                                                      │
│   591 │   │   if new_retry.is_exhausted():                                                       │
│ ❱ 592 │   │   │   raise MaxRetryError(_pool, url, error or ResponseError(cause))                 │
│   593 │   │                                                                                      │
│   594 │   │   log.debug("Incremented Retry for (url='%s'): %r", url, new_retry)                  │
│   595                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url:
/CompVis/stable-diffusion/main/configs/stable-diffusion/v1-inference.yaml (Caused by
NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001713386BCA0>: Failed to establish a new
connection: [Errno 11002] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\animatediff-cli-prompt-travel\src\animatediff\cli.py:326 in generate                          │
│                                                                                                  │
│    323 │   global g_pipeline                                                                     │
│    324 │   global last_model_path                                                                │
│    325 │   if g_pipeline is None or last_model_path != model_config.path.resolve():              │
│ ❱  326 │   │   g_pipeline = create_pipeline(                                                     │
│    327 │   │   │   base_model=base_model_path,                                                   │
│    328 │   │   │   model_config=model_config,                                                    │
│    329 │   │   │   infer_config=infer_config,                                                    │
│                                                                                                  │
│ D:\animatediff-cli-prompt-travel\src\animatediff\generate.py:371 in create_pipeline              │
│                                                                                                  │
│    368 │   │   logger.info(f"Loading weights from {model_path}")                                 │
│    369 │   │   if model_path.is_file():                                                          │
│    370 │   │   │   logger.debug("Loading from single checkpoint file")                           │
│ ❱  371 │   │   │   unet_state_dict, tenc_state_dict, vae_state_dict = get_checkpoint_weights(mo  │
│    372 │   │   elif model_path.is_dir():                                                         │
│    373 │   │   │   logger.debug("Loading from Diffusers model directory")                        │
│    374 │   │   │   temp_pipeline = StableDiffusionPipeline.from_pretrained(model_path)           │
│                                                                                                  │
│ D:\animatediff-cli-prompt-travel\src\animatediff\utils\model.py:139 in get_checkpoint_weights    │
│                                                                                                  │
│   136                                                                                            │
│   137 def get_checkpoint_weights(checkpoint: Path):                                              │
│   138 │   temp_pipeline: StableDiffusionPipeline                                                 │
│ ❱ 139 │   temp_pipeline, _ = checkpoint_to_pipeline(checkpoint, save=False)                      │
│   140 │   unet_state_dict = temp_pipeline.unet.state_dict()                                      │
│   141 │   tenc_state_dict = temp_pipeline.text_encoder.state_dict()                              │
│   142 │   vae_state_dict = temp_pipeline.vae.state_dict()                                        │
│                                                                                                  │
│ D:\animatediff-cli-prompt-travel\src\animatediff\utils\model.py:124 in checkpoint_to_pipeline    │
│                                                                                                  │
│   121 │   if target_dir is None:                                                                 │
│   122 │   │   target_dir = pipeline_dir.joinpath(checkpoint.stem)                                │
│   123 │                                                                                          │
│ ❱ 124 │   pipeline = StableDiffusionPipeline.from_single_file(                                   │
│   125 │   │   pretrained_model_link_or_path=str(checkpoint.absolute()),                          │
│   126 │   │   local_files_only=True,                                                             │
│   127 │   │   load_safety_checker=False,                                                         │
│                                                                                                  │
│ D:\animatediff-cli-prompt-travel\venv\lib\site-packages\diffusers\loaders.py:1471 in             │
│ from_single_file                                                                                 │
│                                                                                                  │
│   1468 │   │   │   │   force_download=force_download,                                            │
│   1469 │   │   │   )                                                                             │
│   1470 │   │                                                                                     │
│ ❱ 1471 │   │   pipe = download_from_original_stable_diffusion_ckpt(                              │
│   1472 │   │   │   pretrained_model_link_or_path,                                                │
│   1473 │   │   │   pipeline_class=cls,                                                           │
│   1474 │   │   │   model_type=model_type,                                                        │
│                                                                                                  │
│ D:\animatediff-cli-prompt-travel\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\con │
│ vert_from_ckpt.py:1234 in download_from_original_stable_diffusion_ckpt                           │
│                                                                                                  │
│   1231 │   │   │   # only refiner xl has embedder and one text embedders                         │
│   1232 │   │   │   config_url = "https://raw.githubusercontent.com/Stability-AI/generative-mode  │
│   1233 │   │                                                                                     │
│ ❱ 1234 │   │   original_config_file = BytesIO(requests.get(config_url).content)                  │
│   1235 │                                                                                         │
│   1236 │   original_config = OmegaConf.load(original_config_file)                                │
│   1237                                                                                           │
│                                                                                                  │
│ D:\animatediff-cli-prompt-travel\venv\lib\site-packages\requests\api.py:73 in get                │
│                                                                                                  │
│    70 │   :rtype: requests.Response                                                              │
│    71 │   """                                                                                    │
│    72 │                                                                                          │
│ ❱  73 │   return request("get", url, params=params, **kwargs)                                    │
│    74                                                                                            │
│    75                                                                                            │
│    76 def options(url, **kwargs):                                                                │
│                                                                                                  │
│ D:\animatediff-cli-prompt-travel\venv\lib\site-packages\requests\api.py:59 in request            │
│                                                                                                  │
│    56 │   # avoid leaving sockets open which can trigger a ResourceWarning in some               │
│    57 │   # cases, and look like a memory leak in others.                                        │
│    58 │   with sessions.Session() as session:                                                    │
│ ❱  59 │   │   return session.request(method=method, url=url, **kwargs)                           │
│    60                                                                                            │
│    61                                                                                            │
│    62 def get(url, params=None, **kwargs):                                                       │
│                                                                                                  │
│ D:\animatediff-cli-prompt-travel\venv\lib\site-packages\requests\sessions.py:587 in request      │
│                                                                                                  │
│   584 │   │   │   "allow_redirects": allow_redirects,                                            │
│   585 │   │   }                                                                                  │
│   586 │   │   send_kwargs.update(settings)                                                       │
│ ❱ 587 │   │   resp = self.send(prep, **send_kwargs)                                              │
│   588 │   │                                                                                      │
│   589 │   │   return resp                                                                        │
│   590                                                                                            │
│                                                                                                  │
│ D:\animatediff-cli-prompt-travel\venv\lib\site-packages\requests\sessions.py:701 in send         │
│                                                                                                  │
│   698 │   │   start = preferred_clock()                                                          │
│   699 │   │                                                                                      │
│   700 │   │   # Send the request                                                                 │
│ ❱ 701 │   │   r = adapter.send(request, **kwargs)                                                │
│   702 │   │                                                                                      │
│   703 │   │   # Total elapsed time of the request (approximately)                                │
│   704 │   │   elapsed = preferred_clock() - start                                                │
│                                                                                                  │
│ D:\animatediff-cli-prompt-travel\venv\lib\site-packages\requests\adapters.py:565 in send         │
│                                                                                                  │
│   562 │   │   │   │   # This branch is for urllib3 v1.22 and later.                              │
│   563 │   │   │   │   raise SSLError(e, request=request)                                         │
│   564 │   │   │                                                                                  │
│ ❱ 565 │   │   │   raise ConnectionError(e, request=request)                                      │
│   566 │   │                                                                                      │
│   567 │   │   except ClosedPoolError as e:                                                       │
│   568 │   │   │   raise ConnectionError(e, request=request)                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url:
/CompVis/stable-diffusion/main/configs/stable-diffusion/v1-inference.yaml (Caused by
NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001713386BCA0>: Failed to establish a new
connection: [Errno 11002] getaddrinfo failed'))

**Comment by s9roll7** [comment]
Maybe it's a network issue that will be resolved after some time.

**Comment by alanhuang67** [comment]
YES! it looks like have this error when I did't conntect the VPN...
