### ISSUE TITLE
Issue in import

### ISSUE THREAD

**Issue by JohjiYamada** [s9roll7/animatediff-cli-prompt-travel#140]
I just got following error when i do below command

animatediff stylize create-config /storage/animatediff/animatediff-cli-prompt-travel/data/video/dance11.mp4 --fps 16

/usr/local/lib/python3.10/dist-packages/flax/struct.py:136: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
  jax.tree_util.register_keypaths(data_clz, keypaths)
/usr/local/lib/python3.10/dist-packages/flax/struct.py:136: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
  jax.tree_util.register_keypaths(data_clz, keypaths)
/usr/local/lib/python3.10/dist-packages/flax/struct.py:136: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
  jax.tree_util.register_keypaths(data_clz, keypaths)
/usr/local/lib/python3.10/dist-packages/flax/struct.py:136: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
  jax.tree_util.register_keypaths(data_clz, keypaths)
Traceback (most recent call last):
  File "/usr/local/bin/animatediff", line 5, in <module>
    from animatediff.cli import cli
  File "/storage/animatediff/animatediff-cli-prompt-travel/src/animatediff/cli.py", line 15, in <module>
    from animatediff.generate import (controlnet_preprocess, create_pipeline,
  File "/storage/animatediff/animatediff-cli-prompt-travel/src/animatediff/generate.py", line 30, in <module>
    from animatediff.models.clip import CLIPSkipTextModel
  File "/storage/animatediff/animatediff-cli-prompt-travel/src/animatediff/models/clip.py", line 7, in <module>
    from transformers.models.clip.modeling_clip import (
ImportError: cannot import name '_expand_mask' from 'transformers.models.clip.modeling_clip' (/usr/local/lib/python3.10/dist-packages/transformers/models/clip/modeling_clip.py)

Please provide me if u have any idea to solve this?

thanks

**Comment by s9roll7** [comment]
Can you try this?
`pip install transformers==4.31.0`

**Comment by s9roll7** [comment]
It appears that the refactoring in Transformer 4.35.0, released a few hours ago, was the cause.

**Comment by JohjiYamada** [comment]
thanks for quick reply and solution.
wow it's so quick.
Now I just confirmed the code working with latest commit.

thanks for keeping it real!

**Comment by Cuppinono** [comment]
> Can you try this? `pip install transformers==4.31.0`

yes, dut it does not work
