### ISSUE TITLE
Question: Difficulty Controlling Specific Video Clip Durations in long Videos 

### ISSUE THREAD

**Issue by hylarucoder** [s9roll7/animatediff-cli-prompt-travel#145]
> I have tried for a long time to control every clip, but it's been challenging. I want to create a 50-second video. How can I only make adjustments to certain clips? For instance, I would like to control the duration of 5-7 seconds while keeping the others unchanged.

e.g: i want to make a videos like this, when i finetune the first 10s, but i have to run the whole workflow every time, even i've finetune the first 10s, is there a way to rerun only subclip?

https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/5625783/f8d001e9-2465-4238-8931-092c3764c808

Could you give me some advises? Thanks

**Comment by hylarucoder** [comment]
Or Is there a simple way to do image transitions while keeping the start and end images unchanged (pix level unchange)? (Pardon my poor English, I hope I expressed myself clearly.)

<img width="462" alt="image" src="https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/5625783/afd9b609-cf82-4956-bb6f-b40f14ac4003">

<img width="453" alt="image" src="https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/5625783/b8afdbdc-c765-4bca-b1e5-3fde8a996ebe">

**Comment by s9roll7** [comment]
I think it's difficult.
In animatediff, every frame depends on the content of nearby frames.
