### ISSUE TITLE
can not run offline?

### ISSUE THREAD

**Issue by cheezecrisp** [s9roll7/animatediff-cli-prompt-travel#15]
Every time I run this program it tries to connect to 'raw.githubusercontent.com'.
Don't know if it's a problem with my settings or if it's just the way the program is.
Sometimes connection fails and error printed as "ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url:
/CompVis/stable-diffusion/main/configs/stable-diffusion/v1-inference.yaml (Caused by
NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F8CD5B4CA0>: Failed to establish a new
connection: [Errno 11004] getaddrinfo failed'))"

**Comment by s9roll7** [comment]
I don't think it can be done in an offline, as the model is automatically downloaded as appropriate.

**Comment by cheezecrisp** [comment]
> I don't think it can be done in an offline, as the model is automatically downloaded as appropriate.

Yes, running at the fisrt time it downloads models, but I have run many times the program still need network connection, it's wierd.
