### ISSUE TITLE
How project code runs？

### ISSUE THREAD

**Issue by fu-jianhua** [s9roll7/animatediff-cli-prompt-travel#151]
The project is opened and used through the cmd command line, but I don't understand where the code started running internally.
Is animatediff generate XX and Python generate XX the same?
Can I run the py file directly to execute without using the command line？

**Comment by s9roll7** [comment]
https://typer.tiangolo.com/tutorial/commands/

**Comment by fu-jianhua** [comment]
But why does the command line start with animatediff instead of Python？

**Comment by s9roll7** [comment]
`where animatediff`
https://packaging.python.org/en/latest/tutorials/packaging-projects/
