### ISSUE TITLE
diffusers 0.22.x released, some features may useful

### ISSUE THREAD

**Issue by junnikokuki** [s9roll7/animatediff-cli-prompt-travel#153]
https://github.com/huggingface/diffusers/releases

I wonder LCM can accelerate how much the generation.
Also PEFT is useful for multi lora I think.

**Comment by Cubey42** [comment]
to follow up on this; https://github.com/intellerce/controlanimate seems to suggest its a 10x increase in inference.

**Comment by s9roll7** [comment]
> to follow up on this; https://github.com/intellerce/controlanimate seems to suggest its a 10x increase in inference.

LCM is only available at dedicated checkpoints, right?
Maybe the existing controlnet model is not available either.
I'm wondering if we should support this.

**Comment by hylarucoder** [comment]
@s9roll7 LCM looks like a plugin compatible with Checkpoint/LoRA/Controlnet.

After incorporating LCM into my comfyui animatediff workflow, it functions exceptionally well. The process was straightforward, involving the addition of just two nodes and an adjustment to the sampler node.

Still, LCM may look lack of details in 5 steps

<img width="1387" alt="image" src="https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/5625783/ff212ee2-4185-45f5-96e8-402d3441fcc0">

You Can find my workflow here, https://github.com/hylarucoder/comfyui-workflow/tree/main/animatediff

Link: https://huggingface.co/latent-consistency/lcm-lora-sdv1-5

<img width="551" alt="image" src="https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/5625783/e856a983-ee8e-47f2-882b-e565aafd4670">

> > to follow up on this; [intellerce/controlanimate](https://github.com/intellerce/controlanimate) seems to suggest its a 10x increase in inference.
> 
> LCM is only available at dedicated checkpoints, right? Maybe the existing controlnet model is not available either. I'm wondering if we should support this.

**Comment by deeplearn-art** [comment]
>  I'm wondering if we should support this.

Absolutely! Controlanimate now has support for LCM Lora which works with any SD1.5/XL derived model and is compatible with controlnets, loras etc 

https://huggingface.co/latent-consistency/lcm-lora-sdv1-5

**Comment by s9roll7** [comment]
7f3ca02

**Comment by hylarucoder** [comment]
@s9roll7 that's huge, thx sooooo much
