### ISSUE TITLE
Motion Loras

### ISSUE THREAD

**Issue by tnil25** [s9roll7/animatediff-cli-prompt-travel#154]
Are Motion Loras still supported? Tried using one and it doesnt seem to apply to the output.

 "motion_lora_map": {
    "data/models/motion_lora/v2_lora_ZoomIn.ckpt": 1.0
  },

**Comment by s9roll7** [comment]
```
"motion_lora_map": {
"models/motion_lora/v2_lora_ZoomIn.ckpt": 1.0
},
```
Maybe this will work.

**Comment by tnil25** [comment]
hmmm, I don't think so. in the previous repo I didn't need to include data/ in the lora path. But in the new repo, when I didn't include data/ the console spat out a file missing error. Regular Loras work with data/ in the path, motion loras seem to not? I dont get a file missing error, it just doesnt seem like it effects the output anymore.

**Comment by s9roll7** [comment]
> Regular Loras work with data/ in the path,

This was a bug. It has been fixed in the latest version.

**Comment by tnil25** [comment]
Ok, when updating to the latest version, whats the best way to do it? Do I need to do a full clean install or is there a way to just update my current repo?

Have you by any chance tested motion loras? I feel like if they were in the wrong path I would get a console error which I dont, just no effect on the output.

**Comment by s9roll7** [comment]
https://github.com/s9roll7/animatediff-cli-prompt-travel/issues/147#issuecomment-1803526039

**Comment by tnil25** [comment]
Did a fresh install and its working great. Thank you!
