### ISSUE TITLE
OutOfMemory error during stylize

### ISSUE THREAD

**Issue by tnil25** [s9roll7/animatediff-cli-prompt-travel#158]
Any reason I could be getting an OutOfMemory error all of a sudden? Im using create region and it worked yesterday, but doing the same process for the same file again today gives me this error. Even when adding -lo to the command. This error sais I have more free vram then reserved.

OutOfMemoryError: CUDA out of memory. Tried to allocate 252.00 MiB (GPU 0; 11.99 GiB total capacity; 2.75 GiB already
allocated; 5.24 GiB free; 4.48 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting
max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Press any key to continue . . .

**Comment by tnil25** [comment]
UPDATE.

Closing all background apps seems to make the error going away, however I dont think they were using that much vram.

**Comment by s9roll7** [comment]
That's just not enough vram actually.
