### ISSUE TITLE
Questions about control_scale_list!

### ISSUE THREAD

**Issue by toyxyz** [s9roll7/animatediff-cli-prompt-travel#16]
What I understand is as follows. "control_scale_list" is a parameter that adjusts the effect of the input controlnet image frame on each adjacent frame. If the list is [0.5, 0.4], the controlnet image inserted in frame 5 has a scale of 0.5 in frames 4 and 6, and a scale of 0.4 in frames 3 and 7. 

And the two parameters are calculated as follows. 

control_scale_list * controlnet_conditioning_scale = Result scale

Therefore, if the scale is 0, all scale lists are also 0. Is my understanding correct?

![image](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/8006000/c737e483-2ebc-4d6e-9e3f-7082bdbaff82)

And I wonder if the control scale list also affects between the first frame 0 and the last frame. I used controlnet tiles, placed 2 images on frame 0 and 15, then created 16 frames of video at "control_scale_list":[1.0]. In frames 0 and 1, the image entered in 0 was almost duplicated, but in the case of frame 15, the first frame, 0, was clearly influenced, so the front and back views were mixed.

![image](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/8006000/4157ab9d-26bb-4f04-8af6-68c26c0b2388)

Next I changed the controlnet 0 image to 2. Controlnet image 2 affects frames 1, 2, and 3, and controlnet image 15 affects frames 0, 14, and 15. is this intended? If so, I think it would be nice if an option was added to disable the scale list from looping. thanks!

![image](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/8006000/af2a47f7-c340-4f61-9a0e-4a7a85693bbf)

**Comment by s9roll7** [comment]
> What I understand is as follows. "control_scale_list" is a parameter that adjusts the effect of the input controlnet image frame on each adjacent frame. If the list is [0.5, 0.4], the controlnet image inserted in frame 5 has a scale of 0.5 in frames 4 and 6, and a scale of 0.4 in frames 3 and 7.
> 
> And the two parameters are calculated as follows.
> 
> control_scale_list * controlnet_conditioning_scale = Result scale
> 
> Therefore, if the scale is 0, all scale lists are also 0. Is my understanding correct?
If it's not buggy, it should be.

The frames are ring-shaped.
The first frame and the last frame are adjacent to each other.
If you don't do anything special, you should get a  looping video (unless context and length are equally short)

>  If so, I think it would be nice if an option was added to disable the scale list from looping. thanks!
Yes, it would be better to have it.

**Comment by s9roll7** [comment]
469e761

```
  "controlnet_map": {       # config for controlnet(for generation)

    "is_loop": true,                # Whether controlnet effects consider loop

```

**Comment by toyxyz** [comment]
> [469e761](https://github.com/s9roll7/animatediff-cli-prompt-travel/commit/469e761b47398cc1be97d2163704a7600a1aad73)
> 
> ```
>   "controlnet_map": {       # config for controlnet(for generation)
> 
>     "is_loop": true,                # Whether controlnet effects consider loop
> ```

It works perfectly! thank you!
![00_42178172268000_masterpiece_best-quality_change-the-time-to-evening_1girl_solo_blonde-hair](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/8006000/1dfae6fb-b0f0-44d6-b5e6-5c4cae8c3c9d)
![image](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/8006000/22e4f878-f00c-4440-bae9-64d6aa8837f6)

![image](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/8006000/dba90b6f-2995-469a-be34-6a097b2f1ad0)
