### ISSUE TITLE
background region

### ISSUE THREAD

**Issue by tnil25** [s9roll7/animatediff-cli-prompt-travel#160]
How exactly is the background region defined?

Lets say I have a mask for a person in region 0. Does background region come from the original prompt map? or does it have to be a region?

If background region is from the prompt map, does the normal lora mapping apply to it? Or is the new lora mapping used?

**Comment by s9roll7** [comment]
https://github.com/s9roll7/animatediff-cli-prompt-travel/issues/147#issuecomment-1793738585
