### ISSUE TITLE
help!!!

### ISSUE THREAD

**Issue by yangzz1125** [s9roll7/animatediff-cli-prompt-travel#161]
Enter animatediff generate -c projects\project-awpaint-01/prompt.json -W 256 -H 384 -L 128 -C 16.There's an error.
animatediff : 无法将“animatediff”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，
请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ animatediff generate -c projects\project-awpaint-01/prompt.json -W 25 ...
+ ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (animatediff:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by s9roll7** [comment]
The installation seems to have failed.
