### ISSUE TITLE
Controlnet suggest

### ISSUE THREAD

**Issue by alanhuang67** [s9roll7/animatediff-cli-prompt-travel#162]
Hi,
When running a project, it will produce controlnet preprocess everytime, do you think if it is possible to produce it once, and then we can refer a dir for those cn we already pre-prosess? Especially for openpose or canny which we may need to do some editing.
Thanks!

**Comment by hylarucoder** [comment]
You have the option to render your video at a smaller size. Additionally, don't forget to copy the 00_detectmap/controlnet_openpose for use in your subsequent projects or iterations.


<img width="731" alt="image" src="https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/5625783/19232d33-ce48-4499-8a41-52d8d8cc3afd">

**Comment by s9roll7** [comment]
```
    "controlnet_openpose":{
      "enable": true,
      "use_preprocessor":true,     #<-----------
      "guess_mode":false,
      "controlnet_conditioning_scale": 1.0,
      "control_guidance_start": 0.0,
      "control_guidance_end": 1.0,
      "control_scale_list":[0.5,0.4,0.3,0.2,0.1]
    },
```

**Comment by alanhuang67** [comment]
Thanks both!
Just wanna to confirm, if I do first time generation for openopse, I got a set of small openpose images
and I can setup se_preprocessor as "false"
and then when I start a new generation, it create a new folder,
and  I past the controlnet in to the new folder before it start randering

Why I'm asking is because I once do a test with above method, but put a totally different pose images, run 32 frames for testing, and found out it didn't work like that...

meanwhile, does openpose have "pixel perfecr" parameter I can use?

Thanks!!!

**Comment by s9roll7** [comment]
Put the original image in the directory for controlnet when it is generated the first time.
For the second and subsequent times, instead of the original images, put the preprocessed images generated in the directory "detectmap" and set "use_preprocessor": in the config to false.

**Comment by hylarucoder** [comment]
@alanhuang67 

"Pixel Perfect" is an option found within the A1111 WebUI.

By the way, would you mind sharing your prompt.json file? It seems there might be another issue, separate from the "Pixel Perfect" concern.

**Comment by alanhuang67** [comment]
@s9roll7 it's work, thanks!

@hylarucoder sure, please check attachment for reference.
[HAND-1111.json](https://github.com/s9roll7/animatediff-cli-prompt-travel/files/13333370/HAND-1111.json)

I already revised the code base on @s9roll7 comment...

**Comment by hylarucoder** [comment]
@alanhuang67 

Could you please attempt the following actions?

- Inspect your other ControlNet directories, such as the 'tile' folder.
- Modify the value in the picture from 1 to 0.

<img width="858" alt="image" src="https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/5625783/a8bf2ec9-a725-428c-b579-a7786d92e9cd">

**Comment by alanhuang67** [comment]
@hylarucoder 

Inspect your other ControlNet directories, such as the 'tile' folder.  -> I don't use tile so it should be empty
Modify the value in the picture from 1 to 0. -> I follow the insrtucion that set background for 0, and girl + mask as 1 in LoRA setuo session, if I set above as 0 as you said, not sure if that will be correcrt?

**Comment by hylarucoder** [comment]
Don't know, cannot see anything wrong except "region_map"
