### ISSUE TITLE
RuntimeError: The size of tensor a (5876) must match the size of tensor b (7232) at non-singleton dimension 1

### ISSUE THREAD

**Issue by liuzhao6322** [s9roll7/animatediff-cli-prompt-travel#165]
(venv) E:\animatediff\animatediff-cli-prompt-travel>animatediff stylize generate stylize\2023-11-14T22-38-10-sample-mistoonanime_v20
22:49:06 INFO     diffuser_ver='0.21.2'                                                                        cli.py:83
         INFO     Using generation config: stylize\2023-11-14T22-38-10-sample-mistoonanime_v20\prompt.json    cli.py:304
22:49:07 INFO     is_v2=True                                                                                 util.py:370
         INFO     Using base model: runwayml\stable-diffusion-v1-5                                            cli.py:322
         INFO     Will save outputs to                                                                        cli.py:330
                  ./stylize\2023-11-14T22-38-10-sample-mistoonanime_v20\2023-11-14T22-49-07-sample-3danimatio
                  ndiffusion_v10
         INFO     Checking motion module...                                                              generate.py:350
         INFO     Loading tokenizer...                                                                   generate.py:364
         INFO     Loading text encoder...                                                                generate.py:366
22:49:08 INFO     Loading VAE...                                                                         generate.py:368
         INFO     Loading UNet...                                                                        generate.py:370
22:49:19 INFO     Loaded 453.20928M-parameter motion module                                                  unet.py:578
22:49:20 INFO     Using scheduler "k_dpmpp_sde" (DPMSolverSinglestepScheduler)                           generate.py:382
         INFO     Loading weights from                                                                   generate.py:387
                  E:\animatediff\animatediff-cli-prompt-travel\data\models\sd\3dAnimationDiffusion_v10.s
                  afetensors
22:49:22 INFO     Merging weights into UNet...                                                           generate.py:404
22:49:23 INFO     Loading vae from                                                                       generate.py:419
                  E:\animatediff\animatediff-cli-prompt-travel\data\models\sd\vae-ft-mse-840000-ema-prun
                  ed.safetensors
         INFO     Creating AnimationPipeline...                                                          generate.py:451
         INFO     No TI embeddings found                                                                       ti.py:102
         INFO     Sending pipeline to device "cuda"                                                       pipeline.py:22
22:49:24 INFO     Selected data types: unet_dtype=torch.float16, tenc_dtype=torch.float16,                  device.py:90
                  vae_dtype=torch.bfloat16
         INFO     Using channels_last memory format for UNet and VAE                                       device.py:111
22:49:27 INFO     Saving prompt config to output directory                                                    cli.py:378
         INFO     Initialization complete!                                                                    cli.py:386
         INFO     Generating 1 animations                                                                     cli.py:387
         INFO     Running generation 1 of 1                                                                   cli.py:397
         INFO     Generation seed: 3180734008                                                                 cli.py:403
         INFO     len( region_condi_list )=1                                                            generate.py:1179
         INFO     len( region_list )=1                                                                  generate.py:1180
         INFO     multi_uncond_mode=False                                                              animation.py:2386
Token indices sequence length is longer than the specified maximum sequence length for this model (126 > 77). Running this sequence through the model will result in indexing errors
   0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/20  [ 0:00:01 < -:--:-- , ? it/s ]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ E:\animatediff\animatediff-cli-prompt-travel\src\animatediff\stylize.py:546 in generate          │
│                                                                                                  │
│    543 │   │   config_org = tmp_config_path                                                      │
│    544 │                                                                                         │
│    545 │                                                                                         │
│ ❱  546 │   output_0_dir = generate(                                                              │
│    547 │   │   config_path=config_org,                                                           │
│    548 │   │   width=model_config.stylize_config["0"]["width"],                                  │
│    549 │   │   height=model_config.stylize_config["0"]["height"],                                │
│                                                                                                  │
│ E:\animatediff\animatediff-cli-prompt-travel\src\animatediff\cli.py:406 in generate              │
│                                                                                                  │
│    403 │   │   │   logger.info(f"Generation seed: {seed}")                                       │
│    404 │   │   │                                                                                 │
│    405 │   │   │                                                                                 │
│ ❱  406 │   │   │   output = run_inference(                                                       │
│    407 │   │   │   │   pipeline=g_pipeline,                                                      │
│    408 │   │   │   │   n_prompt=n_prompt,                                                        │
│    409 │   │   │   │   seed=seed,                                                                │
│                                                                                                  │
│ E:\animatediff\animatediff-cli-prompt-travel\src\animatediff\generate.py:1182 in run_inference   │
│                                                                                                  │
│   1179 │   logger.info(f"{len( region_condi_list )=}")                                           │
│   1180 │   logger.info(f"{len( region_list )=}")                                                 │
│   1181 │                                                                                         │
│ ❱ 1182 │   pipeline_output = pipeline(                                                           │
│   1183 │   │   negative_prompt=n_prompt,                                                         │
│   1184 │   │   num_inference_steps=steps,                                                        │
│   1185 │   │   guidance_scale=guidance_scale,                                                    │
│                                                                                                  │
│ E:\animatediff\animatediff-cli-prompt-travel\venv\lib\site-packages\torch\utils\_contextlib.py:1 │
│ 15 in decorate_context                                                                           │
│                                                                                                  │
│   112 │   @functools.wraps(func)                                                                 │
│   113 │   def decorate_context(*args, **kwargs):                                                 │
│   114 │   │   with ctx_factory():                                                                │
│ ❱ 115 │   │   │   return func(*args, **kwargs)                                                   │
│   116 │                                                                                          │
│   117 │   return decorate_context                                                                │
│   118                                                                                            │
│                                                                                                  │
│ E:\animatediff\animatediff-cli-prompt-travel\src\animatediff\pipelines\animation.py:2954 in      │
│ __call__                                                                                         │
│                                                                                                  │
│   2951 │   │   │   │   │   │   __cur_prompt = cur_prompt[layer_index * context_frames:(layer_in  │
│   2952 │   │   │   │   │   │                                                                     │
│   2953 │   │   │   │   │   │   stopwatch_record("self.unet start")                               │
│ ❱ 2954 │   │   │   │   │   │   pred_layer = self.unet(                                           │
│   2955 │   │   │   │   │   │   │   __lat.to(self.unet.device, self.unet.dtype),                  │
│   2956 │   │   │   │   │   │   │   t,                                                            │
│   2957 │   │   │   │   │   │   │   encoder_hidden_states=__cur_prompt,                           │
│                                                                                                  │
│ E:\animatediff\animatediff-cli-prompt-travel\venv\lib\site-packages\torch\nn\modules\module.py:1 │
│ 518 in _wrapped_call_impl                                                                        │
│                                                                                                  │
│   1515 │   │   if self._compiled_call_impl is not None:                                          │
│   1516 │   │   │   return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]        │
│   1517 │   │   else:                                                                             │
│ ❱ 1518 │   │   │   return self._call_impl(*args, **kwargs)                                       │
│   1519 │                                                                                         │
│   1520 │   def _call_impl(self, *args, **kwargs):                                                │
│   1521 │   │   forward_call = (self._slow_forward if torch._C._get_tracing_state() else self.fo  │
│                                                                                                  │
│ E:\animatediff\animatediff-cli-prompt-travel\venv\lib\site-packages\torch\nn\modules\module.py:1 │
│ 527 in _call_impl                                                                                │
│                                                                                                  │
│   1524 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1525 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1526 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1527 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1528 │   │                                                                                     │
│   1529 │   │   try:                                                                              │
│   1530 │   │   │   result = None                                                                 │
│                                                                                                  │
│ E:\animatediff\animatediff-cli-prompt-travel\src\animatediff\models\unet.py:427 in forward       │
│                                                                                                  │
│   424 │   │   down_block_res_samples = (sample,)                                                 │
│   425 │   │   for downsample_block in self.down_blocks:                                          │
│   426 │   │   │   if hasattr(downsample_block, "has_cross_attention") and downsample_block.has   │
│ ❱ 427 │   │   │   │   sample, res_samples = downsample_block(                                    │
│   428 │   │   │   │   │   hidden_states=sample,                                                  │
│   429 │   │   │   │   │   temb=emb,                                                              │
│   430 │   │   │   │   │   encoder_hidden_states=encoder_hidden_states,                           │
│                                                                                                  │
│ E:\animatediff\animatediff-cli-prompt-travel\venv\lib\site-packages\torch\nn\modules\module.py:1 │
│ 518 in _wrapped_call_impl                                                                        │
│                                                                                                  │
│   1515 │   │   if self._compiled_call_impl is not None:                                          │
│   1516 │   │   │   return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]        │
│   1517 │   │   else:                                                                             │
│ ❱ 1518 │   │   │   return self._call_impl(*args, **kwargs)                                       │
│   1519 │                                                                                         │
│   1520 │   def _call_impl(self, *args, **kwargs):                                                │
│   1521 │   │   forward_call = (self._slow_forward if torch._C._get_tracing_state() else self.fo  │
│                                                                                                  │
│ E:\animatediff\animatediff-cli-prompt-travel\venv\lib\site-packages\torch\nn\modules\module.py:1 │
│ 527 in _call_impl                                                                                │
│                                                                                                  │
│   1524 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1525 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1526 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1527 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1528 │   │                                                                                     │
│   1529 │   │   try:                                                                              │
│   1530 │   │   │   result = None                                                                 │
│                                                                                                  │
│ E:\animatediff\animatediff-cli-prompt-travel\src\animatediff\models\unet_blocks.py:429 in        │
│ forward                                                                                          │
│                                                                                                  │
│   426 │   │   │                                                                                  │
│   427 │   │   │   else:                                                                          │
│   428 │   │   │   │   hidden_states = resnet(hidden_states, temb)                                │
│ ❱ 429 │   │   │   │   hidden_states = attn(                                                      │
│   430 │   │   │   │   │   hidden_states,                                                         │
│   431 │   │   │   │   │   encoder_hidden_states=encoder_hidden_states,                           │
│   432 │   │   │   │   │   cross_attention_kwargs=cross_attention_kwargs,                         │
│                                                                                                  │
│ E:\animatediff\animatediff-cli-prompt-travel\venv\lib\site-packages\torch\nn\modules\module.py:1 │
│ 518 in _wrapped_call_impl                                                                        │
│                                                                                                  │
│   1515 │   │   if self._compiled_call_impl is not None:                                          │
│   1516 │   │   │   return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]        │
│   1517 │   │   else:                                                                             │
│ ❱ 1518 │   │   │   return self._call_impl(*args, **kwargs)                                       │
│   1519 │                                                                                         │
│   1520 │   def _call_impl(self, *args, **kwargs):                                                │
│   1521 │   │   forward_call = (self._slow_forward if torch._C._get_tracing_state() else self.fo  │
│                                                                                                  │
│ E:\animatediff\animatediff-cli-prompt-travel\venv\lib\site-packages\torch\nn\modules\module.py:1 │
│ 527 in _call_impl                                                                                │
│                                                                                                  │
│   1524 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1525 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1526 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1527 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1528 │   │                                                                                     │
│   1529 │   │   try:                                                                              │
│   1530 │   │   │   result = None                                                                 │
│                                                                                                  │
│ E:\animatediff\animatediff-cli-prompt-travel\src\animatediff\models\attention.py:148 in forward  │
│                                                                                                  │
│   145 │   │                                                                                      │
│   146 │   │   # 2. Blocks                                                                        │
│   147 │   │   for block in self.transformer_blocks:                                              │
│ ❱ 148 │   │   │   hidden_states = block(                                                         │
│   149 │   │   │   │   hidden_states,                                                             │
│   150 │   │   │   │   attention_mask=attention_mask,                                             │
│   151 │   │   │   │   encoder_hidden_states=encoder_hidden_states,                               │
│                                                                                                  │
│ E:\animatediff\animatediff-cli-prompt-travel\venv\lib\site-packages\torch\nn\modules\module.py:1 │
│ 518 in _wrapped_call_impl                                                                        │
│                                                                                                  │
│   1515 │   │   if self._compiled_call_impl is not None:                                          │
│   1516 │   │   │   return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]        │
│   1517 │   │   else:                                                                             │
│ ❱ 1518 │   │   │   return self._call_impl(*args, **kwargs)                                       │
│   1519 │                                                                                         │
│   1520 │   def _call_impl(self, *args, **kwargs):                                                │
│   1521 │   │   forward_call = (self._slow_forward if torch._C._get_tracing_state() else self.fo  │
│                                                                                                  │
│ E:\animatediff\animatediff-cli-prompt-travel\venv\lib\site-packages\torch\nn\modules\module.py:1 │
│ 527 in _call_impl                                                                                │
│                                                                                                  │
│   1524 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1525 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1526 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1527 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1528 │   │                                                                                     │
│   1529 │   │   try:                                                                              │
│   1530 │   │   │   result = None                                                                 │
│                                                                                                  │
│ E:\animatediff\animatediff-cli-prompt-travel\src\animatediff\models\attention.py:309 in forward  │
│                                                                                                  │
│   306 │   │   │   │   attention_mask=encoder_attention_mask,                                     │
│   307 │   │   │   │   **cross_attention_kwargs,                                                  │
│   308 │   │   │   )                                                                              │
│ ❱ 309 │   │   │   hidden_states = attn_output + hidden_states                                    │
│   310 │   │                                                                                      │
│   311 │   │   # 3. Feed-forward                                                                  │
│   312 │   │   hidden_states = self.ff(self.norm3(hidden_states)) + hidden_states                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: The size of tensor a (5876) must match the size of tensor b (7232) at non-singleton dimension 1

**Comment by liuzhao6322** [comment]
I tested two sizes of videos, one is 512 * 904, and this is fine

But another 904 * 512 error occurred: RuntimeError: The size of tensor a (5876) must match the size of tensor b (7232) at non-singleton dimension 1   thanks

**Comment by liuzhao6322** [comment]
I seem to have found the reason today. Mov format videos are not suitable, while MP4 format is acceptable.

However, there will still be an error message stating 'Token indications sequence length is longer than the specified maximum sequence length for this model (100>77). Running this sequence through the model will result in indexing errors', but it does not affect program operation

**Comment by s9roll7** [comment]
Its error messages are completely harmless.
Don't worry about it.
