### ISSUE TITLE
Support for lcm lora

### ISSUE THREAD

**Issue by zboing** [s9roll7/animatediff-cli-prompt-travel#166]
Can you add support for the lcm lora?

https://huggingface.co/latent-consistency

**Comment by s9roll7** [comment]
7f3ca02

**Comment by alanhuang67** [comment]
This is so great!
do I need to import LCM lora in lora map? 
if yes, how do I apply LCM in the new format of lora map?

**Comment by s9roll7** [comment]
You might want to lower the lcm_lora_scale. Perhaps 1.0 is too high.
