### ISSUE TITLE
region LoRA seems not working

### ISSUE THREAD

**Issue by alanhuang67** [s9roll7/animatediff-cli-prompt-travel#169]
Hello,

when I use previously LoRA formatting, it work quite well, but when I try use new lora formatting the region LoRA didn't work, not sure why

for example I like to stylize the girl as low poly style, when I use previously lora formatting, it's work
![00000020](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/10071840/c812a1c6-288e-4283-9613-b8b7bb034283)

but it's not working for new formatting, result as below
![00000022](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/10071840/ed45de78-3624-40ab-ab24-010891a8bdd4)

here is the lora for example 1
[Dance-1114C.json](https://github.com/s9roll7/animatediff-cli-prompt-travel/files/13402568/Dance-1114C.json)

and here is example 2
[Dance-1114.json](https://github.com/s9roll7/animatediff-cli-prompt-travel/files/13402569/Dance-1114.json)

can you help to check is there is anything not set well? thansk!

@s9roll7

**Comment by s9roll7** [comment]
Relative paths are required

**Comment by alanhuang67** [comment]
Thanks,
when I modify to below, it still not working for region "1", 
actually, I feel like only ip-adapter work, but in the cmd, it shows both lora been loaded for both paths method


   "lora_map": {
		"models/sd/ARWCyberpunkInterior.safetensors": {
			"region" : ["0","background"], 
			"scale" : {
				"0": 0.8
			}
		},
		"models/sd/low.safetensors": {
			"region" : ["1"], 
			"scale" : {
				"0": 1
			}
		}
   },

**Comment by s9roll7** [comment]
I don't know if this is relevant, but I am concerned about the use of a non-existent region "0". I'm not debugging that sort of thing.

**Comment by alanhuang67** [comment]
I setup this by yoyr comment

https://github.com/s9roll7/animatediff-cli-prompt-travel/issues/147

And even if i remove region 0 and keep region 1 only, it still not working, only previously formatting works...

**Comment by alanhuang67** [comment]
actually I'm a little confused..

if I want to use a lora as background, and other lora for each region, how do I setup lora map?

**Comment by s9roll7** [comment]
Looks fine to me.

**Comment by alanhuang67** [comment]
Thank you for your patient reply!!!!

**Comment by JimLee4530** [comment]
@alanhuang67 hi, can you show a example for final work prompt.json? i have same problem. my person region lora not working too? can you give me some advise? thanks 
{
  "name": "sample",
  "path": "models/share/Stable-diffusion/aniverse_thxEd14Pruned.safetensors",
  "vae_path": "",
  "motion_module": "models/motion-module/mm_sd_v15_v2.ckpt",
  "lcm_map": {
    "enable": false,
    "start_scale": 0.15,
    "end_scale": 0.75,
    "gradient_start": 0.2,
    "gradient_end": 0.75
  },
  "gradual_latent_hires_fix_map": {
    "enable": true,
    "scale": {
      "0": 0.5,
      "0.7": 1.0
    },
    "reverse_steps": 5,
    "noise_add_count": 3
  },
  "compile": false,
  "tensor_interpolation_slerp": true,
  "seed": [
    -1
  ],
  "scheduler": "euler_a",
  "steps": 20,
  "guidance_scale": 7.0,
  "unet_batch_size": 1,
  "clip_skip": 2,
  "prompt_fixed_ratio": 0.5,
  "head_prompt": "no_humans, simple_background, green background",
  "prompt_map": {
    "0": ""
  },
  "tail_prompt": "",
  "n_prompt": [
    "fcNeg-neg, (worst quality, low quality:1.4),"
  ],
  "is_single_prompt_mode": false,
  "lora_map": {
    "models/share/GreenScreen_N.safetensors": {
      "region": [
        "background"
      ],
      "scale": {
        "0": 1.5
      }
    },
    "models/share/joyland-lora/Rem_ReZero_v1_1.safetensors": {
      "region": [
        "0"
      ],
      "scale": {
        "0": 1.0
      }
    }
  },
  "motion_lora_map": {},
  "ip_adapter_map": {
    "enable": false,
    "input_image_dir": "../stylize/2023-12-04T02-14-24-sample-mistoonanime_v20/00_ipadapter",
    "prompt_fixed_ratio": 0.5,
    "save_input_image": true,
    "resized_to_square": false,
    "scale": 0.5,
    "is_full_face": false,
    "is_plus_face": false,
    "is_plus": true,
    "is_light": false
  },
  "img2img_map": {
    "enable": false,
    "init_img_dir": "../stylize/2023-12-04T02-14-24-sample-mistoonanime_v20/00_img2img",
    "save_init_image": true,
    "denoising_strength": 0.7
  },
  "region_map": {
    "0": {
      "enable": true,
      "crop_generation_rate": 0.0,
      "mask_dir": "../stylize/2023-12-04T02-14-24-sample-mistoonanime_v20/r_fg_00_2023-12-04T02-42-03/00_mask",
      "save_mask": true,
      "is_init_img": false,
      "condition": {
        "prompt_fixed_ratio": 0.5,
        "head_prompt": "masterpiece, beautiful, 1girl",
        "prompt_map": {
          "0": ""
        },
        "tail_prompt": "",
        "ip_adapter_map": {
          "enable": false,
          "input_image_dir": "../stylize/2023-12-04T02-14-24-sample-mistoonanime_v20/r_fg_00_2023-12-04T02-42-03/00_ipadapter",
          "prompt_fixed_ratio": 0.5,
          "save_input_image": true,
          "resized_to_square": false
        }
      }
    },
    "background": {
      "is_init_img": false,
      "hint": "background's condition refers to the one in root"
    }
  },
  "controlnet_map": {
    "input_image_dir": "../stylize/2023-12-04T02-14-24-sample-mistoonanime_v20/00_controlnet_image",
    "max_samples_on_vram": 0,
    "max_models_on_vram": 0,
    "save_detectmap": true,
    "preprocess_on_gpu": true,
    "is_loop": false,
    "controlnet_tile": {
      "enable": true,
      "use_preprocessor": true,
      "preprocessor": {
        "type": "none",
        "param": {}
      },
      "guess_mode": false,
      "controlnet_conditioning_scale": 1.0,
      "control_guidance_start": 0.0,
      "control_guidance_end": 1.0,
      "control_scale_list": []
    },
    "controlnet_ip2p": {
      "enable": true,
      "use_preprocessor": true,
      "guess_mode": false,
      "controlnet_conditioning_scale": 0.5,
      "control_guidance_start": 0.0,
      "control_guidance_end": 1.0,
      "control_scale_list": []
    },
    "controlnet_lineart_anime": {
      "enable": true,
      "use_preprocessor": true,
      "guess_mode": false,
      "controlnet_conditioning_scale": 1.0,
      "control_guidance_start": 0.0,
      "control_guidance_end": 1.0,
      "control_scale_list": []
    },
    "controlnet_openpose": {
      "enable": true,
      "use_preprocessor": true,
      "guess_mode": false,
      "controlnet_conditioning_scale": 1.0,
      "control_guidance_start": 0.0,
      "control_guidance_end": 1.0,
      "control_scale_list": []
    },
    "controlnet_softedge": {
      "enable": true,
      "use_preprocessor": true,
      "preprocessor": {
        "type": "softedge_pidsafe",
        "param": {}
      },
      "guess_mode": false,
      "controlnet_conditioning_scale": 1.0,
      "control_guidance_start": 0.0,
      "control_guidance_end": 1.0,
      "control_scale_list": []
    },
    "controlnet_shuffle": {
      "enable": true,
      "use_preprocessor": true,
      "guess_mode": false,
      "controlnet_conditioning_scale": 1.0,
      "control_guidance_start": 0.0,
      "control_guidance_end": 1.0,
      "control_scale_list": []
    },
    "controlnet_depth": {
      "enable": true,
      "use_preprocessor": true,
      "guess_mode": false,
      "controlnet_conditioning_scale": 1.0,
      "control_guidance_start": 0.0,
      "control_guidance_end": 1.0,
      "control_scale_list": []
    },
    "controlnet_canny": {
      "enable": true,
      "use_preprocessor": true,
      "guess_mode": false,
      "controlnet_conditioning_scale": 1.0,
      "control_guidance_start": 0.0,
      "control_guidance_end": 1.0,
      "control_scale_list": []
    },
    "controlnet_inpaint": {
      "enable": true,
      "use_preprocessor": true,
      "guess_mode": false,
      "controlnet_conditioning_scale": 1.0,
      "control_guidance_start": 0.0,
      "control_guidance_end": 1.0,
      "control_scale_list": []
    },
    "controlnet_lineart": {
      "enable": true,
      "use_preprocessor": true,
      "guess_mode": false,
      "controlnet_conditioning_scale": 1.0,
      "control_guidance_start": 0.0,
      "control_guidance_end": 1.0,
      "control_scale_list": []
    },
    "controlnet_mlsd": {
      "enable": true,
      "use_preprocessor": true,
      "guess_mode": false,
      "controlnet_conditioning_scale": 1.0,
      "control_guidance_start": 0.0,
      "control_guidance_end": 1.0,
      "control_scale_list": []
    },
    "controlnet_normalbae": {
      "enable": true,
      "use_preprocessor": true,
      "guess_mode": false,
      "controlnet_conditioning_scale": 1.0,
      "control_guidance_start": 0.0,
      "control_guidance_end": 1.0,
      "control_scale_list": []
    },
    "controlnet_scribble": {
      "enable": true,
      "use_preprocessor": true,
      "guess_mode": false,
      "controlnet_conditioning_scale": 1.0,
      "control_guidance_start": 0.0,
      "control_guidance_end": 1.0,
      "control_scale_list": []
    },
    "controlnet_seg": {
      "enable": true,
      "use_preprocessor": true,
      "guess_mode": false,
      "controlnet_conditioning_scale": 1.0,
      "control_guidance_start": 0.0,
      "control_guidance_end": 1.0,
      "control_scale_list": []
    },
    "qr_code_monster_v1": {
      "enable": true,
      "use_preprocessor": true,
      "guess_mode": false,
      "controlnet_conditioning_scale": 1.0,
      "control_guidance_start": 0.0,
      "control_guidance_end": 1.0,
      "control_scale_list": []
    },
    "qr_code_monster_v2": {
      "enable": true,
      "use_preprocessor": true,
      "guess_mode": false,
      "controlnet_conditioning_scale": 1.0,
      "control_guidance_start": 0.0,
      "control_guidance_end": 1.0,
      "control_scale_list": []
    },
    "controlnet_mediapipe_face": {
      "enable": true,
      "use_preprocessor": true,
      "guess_mode": false,
      "controlnet_conditioning_scale": 1.0,
      "control_guidance_start": 0.0,
      "control_guidance_end": 1.0,
      "control_scale_list": []
    },
    "animatediff_controlnet": {
      "enable": true,
      "use_preprocessor": true,
      "guess_mode": false,
      "controlnet_conditioning_scale": 1.0,
      "control_guidance_start": 0.0,
      "control_guidance_end": 1.0,
      "control_scale_list": []
    },
    "controlnet_ref": {
      "enable": false,
      "ref_image": "ref_image/ref_sample.png",
      "attention_auto_machine_weight": 0.3,
      "gn_auto_machine_weight": 0.3,
      "style_fidelity": 0.5,
      "reference_attn": true,
      "reference_adain": false,
      "scale_pattern": [
        1.0
      ]
    }
  },
  "upscale_config": {
    "scheduler": "k_dpmpp_sde",
    "steps": 20,
    "strength": 0.5,
    "guidance_scale": 10,
    "controlnet_tile": {
      "enable": true,
      "controlnet_conditioning_scale": 1.0,
      "guess_mode": false,
      "control_guidance_start": 0.0,
      "control_guidance_end": 1.0
    },
    "controlnet_line_anime": {
      "enable": false,
      "controlnet_conditioning_scale": 1.0,
      "guess_mode": false,
      "control_guidance_start": 0.0,
      "control_guidance_end": 1.0
    },
    "controlnet_ip2p": {
      "enable": false,
      "controlnet_conditioning_scale": 0.5,
      "guess_mode": false,
      "control_guidance_start": 0.0,
      "control_guidance_end": 1.0
    },
    "controlnet_ref": {
      "enable": false,
      "use_frame_as_ref_image": false,
      "use_1st_frame_as_ref_image": false,
      "ref_image": "ref_image/path_to_your_ref_img.jpg",
      "attention_auto_machine_weight": 1.0,
      "gn_auto_machine_weight": 1.0,
      "style_fidelity": 0.25,
      "reference_attn": true,
      "reference_adain": false
    }
  },
  "stylize_config": {
    "original_video": {
      "path": "20231130-161845-file_v3_005m_05317eaa-57c8-4d27-b9fd-abbfd8b2a36g.mp4",
      "aspect_ratio": -1.0,
      "offset": 0
    },
    "create_mask": [
      "person"
    ],
    "composite": {
      "fg_list": [
        {
          "path": " absolute path to frame dir ",
          "mask_path": "/root/code/prompt-travel-1204/stylize/2023-12-04T02-14-24-sample-mistoonanime_v20/r_fg_00_2023-12-04T02-42-03/00_mask",
          "mask_prompt": "person"
        }
      ],
      "bg_frame_dir": "",
      "hint": ""
    },
    "0": {
      "width": 768,
      "height": 1184,
      "length": 20,
      "context": 16,
      "overlap": 4,
      "stride": 0
    }
  },
  "output": {
    "format": "mp4",
    "fps": 8,
    "encode_param": {
      "crf": 10
    }
  },
  "result": {}
}
