### ISSUE TITLE
Some questions about controlNET and LoRAs.

### ISSUE THREAD

**Issue by Atoli** [s9roll7/animatediff-cli-prompt-travel#17]
I have 6 punctual questions:

1. Which LoRAs are compatible and which are incompatible with animatediff-cli-prompt-travel? So far some LoRAs i have tried work great with this.

2. Do embeddings (textual inversion) work with this?

3. The main page says i have to change the 999 for another number here, any suggestion which number i should choose?

```
 "controlnet_map": {
    "input_image_dir" : "controlnet_image/test",
    "max_samples_on_vram": 999,
    "save_detectmap": true,
    "preprocess_on_gpu": true,
```

4. How do i make ControlNET work with this? I drag the PNG and rename them JUST like the example says, but they are not used in the generation. 

![img1](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/43733214/1699a103-d357-4bc9-ac0f-394fc8ee5a3f)

![Capture](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/43733214/e3358d04-7f06-4272-8b68-99811b94ba3d)

And they are enabled:

```
   "controlnet_openpose":{
      "enable": true,
      "use_preprocessor":true,
      "guess_mode":false,
      "controlnet_conditioning_scale": 1.0,
      "control_guidance_start": 0.0,
      "control_guidance_end": 1.0,
      "control_scale_list":[0.5,0.4,0.3,0.2,0.1]
    },

    "controlnet_canny": {
      "enable": true,
      "use_preprocessor":true,
      "guess_mode":false,
      "controlnet_conditioning_scale": 1.0,
      "control_guidance_start": 0.0,
      "control_guidance_end": 1.0,
      "control_scale_list":[0.5,0.4,0.3,0.2,0.1]
    },
```

I am putting the PNG on openpose and canny but they are completely ignored, even in the output they do not appear while the examples have a subfolder in the output to show the controlNET used.

5. How do i "order" the controlnet? I want canny as a background (so the entire animation has a stable background), and open pose as the pose of the subject, i suppose this is done automatically? Or i have to order the "layers" of controlNET?

6. Any way to remove that "shutterstock" text on the bottom? I tried to put `(watermark, text:1.5), logo, text` on the negative prompt but nothing, the text is still there.

**Comment by s9roll7** [comment]
> Which LoRAs are compatible and which are incompatible with animatediff-cli-prompt-travel? So far some LoRAs i have tried work great with this.

Only the most basic lora is available, not LyCORIS, etc.

> Do embeddings (textual inversion) work with this?

Yes. put in data/embeddings

> The main page says i have to change the 999 for another number here, any suggestion which number i should choose?

For example, if you put 100 pngs in canny and 100 pngs in depth, this parameter determines where to put the 200 pieces of data generated by controlnet.
If you want to save vram, set it to 0 and everything will be placed in cpu. 999 is fine until you run out of vram.

> How do i make ControlNET work with this? I drag the PNG and rename them JUST like the example says, but they are not used in the generation.

Maybe you have something in there that is not a png, or maybe the path is not specified correctly.
If that doesn't help, zip up the data/controlnet_image/test directory and the config file and paste it here.

> How do i "order" the controlnet? I want canny as a background (so the entire animation has a stable background), and open pose as the pose of the subject, i suppose this is done automatically? Or i have to order the "layers" of controlNET?

This might be helpful.
#6 

> Any way to remove that "shutterstock" text on the bottom? I tried to put (watermark, text:1.5), logo, text on the negative prompt but nothing, the text is still there.

It seems to be a problem with mm_sd_v15.ckpt. Perhaps it has overlearned the logo.
Try changing it to mm_sd_v14.ckpt.

**Comment by Atoli** [comment]
Thank you for answer.

> Maybe you have something in there that is not a png, or maybe the path is not specified correctly.
> If that doesn't help, zip up the data/controlnet_image/test directory and the config file and paste it here.

Oh, that was the mistake, most of my images were jpg but i didn't noticed.

When tried to run it with canny and openpose...canny could not load:

![Capture](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/43733214/89acc87e-5db3-4474-a2ea-2fa25e762a70)

It is always stuck at 1%.

I already have the controlnet models downloaded because of Automatic webUI, is there a way i can put them manually in animatediff-cli-prompt-travel folder? I cannot find where i could put the controlNET models.

**Comment by Atoli** [comment]
I see, thank you for answer.

Is there a meaning to the numbers on the files?

0000
0016
0032

Is this the frame where they "start"? I used canny with a background but it seems to not carry through the whole animation.

**Comment by s9roll7** [comment]
I think this explanation is easy to understand
#16

**Comment by xnmt9** [comment]
@s9roll7 do we have to adjust config file for an embedding?

**Comment by s9roll7** [comment]
this might works.
(embedding:1.4)
