### ISSUE TITLE
ValueError: path: 'openai/clip-vit-large-patch14'. 

### ISSUE THREAD

**Issue by dancemanUK** [s9roll7/animatediff-cli-prompt-travel#171]
(venv) G:\animatediff-cli-prompt-travel-other>animatediff generate -c  projects/project-awpaint-01/prompt.json  -W 512 -H 768 -L 128 -C 20
21:31:02 INFO     diffuser_ver='0.23.0'                                                                                                                              cli.py:100
21:31:03 INFO     Using generation config: projects\project-awpaint-01\prompt.json                                                                                   cli.py:313
         INFO     is_sdxl=False                                                                                                                                     util.py:540
         INFO     is_v2=True                                                                                                                                        util.py:518
         INFO     Using base model: runwayml\stable-diffusion-v1-5                                                                                                   cli.py:340
         INFO     Will save outputs to ./output\2023-11-22T21-31-03-sample-anythingv5_v5prtre                                                                        cli.py:348
         INFO     Checking motion module...                                                                                                                     generate.py:556
         INFO     Loading tokenizer...                                                                                                                          generate.py:580
         INFO     Loading text encoder...                                                                                                                       generate.py:582
21:31:04 INFO     Loading VAE...                                                                                                                                generate.py:584
         INFO     Loading UNet...                                                                                                                               generate.py:586
21:31:10 INFO     Loaded 453.20928M-parameter motion module                                                                                                         unet.py:578
         INFO     Using scheduler "k_dpmpp_sde" (DPMSolverSinglestepScheduler)                                                                                  generate.py:598
         INFO     Loading weights from G:\animatediff-cli-prompt-travel-other\data\models\sd\AnythingV5_v5PrtRE.safetensors                                     generate.py:603
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ G:\animatediff-cli-prompt-travel-other\venv\lib\site-packages\diffusers\pipelines\stable_diffusi │
│ on\convert_from_ckpt.py:1638 in download_from_original_stable_diffusion_ckpt                     │
│                                                                                                  │
│   1635 │   │   )                                                                                 │
│   1636 │   │   try:                                                                              │
│   1637 │   │   │   tokenizer = (                                                                 │
│ ❱ 1638 │   │   │   │   CLIPTokenizer.from_pretrained("openai/clip-vit-large-patch14", local_fil  │
│   1639 │   │   │   │   if tokenizer is None                                                      │
│   1640 │   │   │   │   else tokenizer                                                            │
│   1641 │   │   │   )                                                                             │
│                                                                                                  │
│ G:\animatediff-cli-prompt-travel-other\venv\lib\site-packages\transformers\tokenization_utils_ba │
│ se.py:2001 in from_pretrained                                                                    │
│                                                                                                  │
│   1998 │   │   │   )                                                                             │
│   1999 │   │                                                                                     │
│   2000 │   │   if all(full_file_name is None for full_file_name in resolved_vocab_files.values(  │
│ ❱ 2001 │   │   │   raise EnvironmentError(                                                       │
│   2002 │   │   │   │   f"Can't load tokenizer for '{pretrained_model_name_or_path}'. If you wer  │
│   2003 │   │   │   │   "'https://huggingface.co/models', make sure you don't have a local direc  │
│   2004 │   │   │   │   f"Otherwise, make sure '{pretrained_model_name_or_path}' is the correct   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OSError: Can't load tokenizer for 'openai/clip-vit-large-patch14'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local
directory with the same name. Otherwise, make sure 'openai/clip-vit-large-patch14' is the correct path to a directory containing all relevant files for a CLIPTokenizer
tokenizer.

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ G:\animatediff-cli-prompt-travel-other\src\animatediff\cli.py:358 in generate                    │
│                                                                                                  │
│    355 │   global last_model_path                                                                │
│    356 │   pipeline_already_loaded = False                                                       │
│    357 │   if g_pipeline is None or last_model_path != model_config.path.resolve():              │
│ ❱  358 │   │   g_pipeline = create_pipeline(                                                     │
│    359 │   │   │   base_model=base_model_path,                                                   │
│    360 │   │   │   model_config=model_config,                                                    │
│    361 │   │   │   infer_config=infer_config,                                                    │
│                                                                                                  │
│ G:\animatediff-cli-prompt-travel-other\src\animatediff\generate.py:606 in create_pipeline        │
│                                                                                                  │
│    603 │   │   logger.info(f"Loading weights from {model_path}")                                 │
│    604 │   │   if model_path.is_file():                                                          │
│    605 │   │   │   logger.debug("Loading from single checkpoint file")                           │
│ ❱  606 │   │   │   unet_state_dict, tenc_state_dict, vae_state_dict = get_checkpoint_weights(mo  │
│    607 │   │   elif model_path.is_dir():                                                         │
│    608 │   │   │   logger.debug("Loading from Diffusers model directory")                        │
│    609 │   │   │   temp_pipeline = StableDiffusionPipeline.from_pretrained(model_path)           │
│                                                                                                  │
│ G:\animatediff-cli-prompt-travel-other\src\animatediff\utils\model.py:162 in                     │
│ get_checkpoint_weights                                                                           │
│                                                                                                  │
│   159                                                                                            │
│   160 def get_checkpoint_weights(checkpoint: Path):                                              │
│   161 │   temp_pipeline: StableDiffusionPipeline                                                 │
│ ❱ 162 │   temp_pipeline, _ = checkpoint_to_pipeline(checkpoint, save=False)                      │
│   163 │   unet_state_dict = temp_pipeline.unet.state_dict()                                      │
│   164 │   tenc_state_dict = temp_pipeline.text_encoder.state_dict()                              │
│   165 │   vae_state_dict = temp_pipeline.vae.state_dict()                                        │
│                                                                                                  │
│ G:\animatediff-cli-prompt-travel-other\src\animatediff\utils\model.py:127 in                     │
│ checkpoint_to_pipeline                                                                           │
│                                                                                                  │
│   124 │   if target_dir is None:                                                                 │
│   125 │   │   target_dir = pipeline_dir.joinpath(checkpoint.stem)                                │
│   126 │                                                                                          │
│ ❱ 127 │   pipeline = StableDiffusionPipeline.from_single_file(                                   │
│   128 │   │   pretrained_model_link_or_path=str(checkpoint.absolute()),                          │
│   129 │   │   local_files_only=True,                                                             │
│   130 │   │   load_safety_checker=False,                                                         │
│                                                                                                  │
│ G:\animatediff-cli-prompt-travel-other\venv\lib\site-packages\diffusers\loaders.py:2822 in       │
│ from_single_file                                                                                 │
│                                                                                                  │
│   2819 │   │   │   │   force_download=force_download,                                            │
│   2820 │   │   │   )                                                                             │
│   2821 │   │                                                                                     │
│ ❱ 2822 │   │   pipe = download_from_original_stable_diffusion_ckpt(                              │
│   2823 │   │   │   pretrained_model_link_or_path,                                                │
│   2824 │   │   │   pipeline_class=cls,                                                           │
│   2825 │   │   │   model_type=model_type,                                                        │
│                                                                                                  │
│ G:\animatediff-cli-prompt-travel-other\venv\lib\site-packages\diffusers\pipelines\stable_diffusi │
│ on\convert_from_ckpt.py:1643 in download_from_original_stable_diffusion_ckpt                     │
│                                                                                                  │
│   1640 │   │   │   │   else tokenizer                                                            │
│   1641 │   │   │   )                                                                             │
│   1642 │   │   except Exception:                                                                 │
│ ❱ 1643 │   │   │   raise ValueError(                                                             │
│   1644 │   │   │   │   f"With local_files_only set to {local_files_only}, you must first locall  │
│   1645 │   │   │   )                                                                             │
│   1646                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: With local_files_only set to True, you must first locally save the tokenizer in the following path: 'openai/clip-vit-large-patch14'.

(venv) G:\animatediff-cli-prompt-travel-other>
![Uploading 微信图片_20231122213331.png…]()

**Comment by yukselyusuf** [comment]
same issue

**Comment by s9roll7** [comment]
ttps://github.com/Akegarasu/lora-scripts/issues/270

**Comment by s9roll7** [comment]
Not that it has anything to do with this issue.
The Anything series checkpoints are very incompatible with animatediff, so please use another checkpoint.

**Comment by dancemanUK** [comment]
> 并不是说它与这个问题有任何关系。 Anything 系列检查点与 animatediff 非常不兼容，因此请使用其他检查点。

thx ,I try  other ckp.

**Comment by dancemanUK** [comment]
I can modify  "G:\animatediff-cli-prompt-travel-other\src\animatediff\utils\model.py"
#128 
    pretrained_model_link_or_path=str(checkpoint.absolute()),
        ##local_files_only=True,
        local_files_only=False,
        load_safety_checker=False,

windows,drivers c: auto download 
.cache\huggingface\hub\models--openai--clip-vit-large-patch14

**Comment by s9roll7** [comment]
[6559395](https://github.com/s9roll7/animatediff-cli-prompt-travel/commit/655939563d9e623e88b66b77f833bbb2a014fc75)
