### ISSUE TITLE
lcm

### ISSUE THREAD

**Issue by willis** [s9roll7/animatediff-cli-prompt-travel#175]
I see lcm is already supported, how to use it?

**Comment by s9roll7** [comment]
https://github.com/s9roll7/animatediff-cli-prompt-travel/blob/main/config/prompts/sample_lcm.json

**Comment by Robert975** [comment]
is there any other configuration change I need to make?

**Comment by s9roll7** [comment]
```
    "start_scale":0.15,      
    "end_scale":0.75,
    "gradient_start":0.2,
    "gradient_end":0.75
```
This is an item that changes the intensity with which lora is applied.
In the example above
From 0% to 20% of the denoising step, it is applied at 0.15.
From 20% to 75% of the denoising step, the intensity is gradually increased.
From 75% to the end of the denoising step, it is applied at 0.75.

This value is set to my preference, so feel free to change it
