### ISSUE TITLE
Best way to update?

### ISSUE THREAD

**Issue by tnil25** [s9roll7/animatediff-cli-prompt-travel#177]
Is there a way to update to the current repo without having to do a fresh install?

**Comment by s9roll7** [comment]
I recently changed the version of the library depend on, so I think you should do a fresh install at least once.

**Comment by tnil25** [comment]
Ok, no problem. But for future updates is there a good way to update the repo without doing a whole new install?

**Comment by s9roll7** [comment]
For minor updates, just do a git pull.
`git pull`

**Comment by tnil25** [comment]
No that didnt seem to work.

This seems to fix the issue when ran in the venv:

pip uninstall torch
pip cache purge
pip install torch -f https://download.pytorch.org/whl/torch_stable.html
