### ISSUE TITLE
lora

### ISSUE THREAD

**Issue by chenwei20** [s9roll7/animatediff-cli-prompt-travel#178]
![2023-11-27_132807](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/74149343/8083d98a-224b-4782-a1d6-0a7be00922e5)
Once lora is used, something like this will appear ，There is no such thing without using lora

**Comment by s9roll7** [comment]
It is a log that also appears normal.
It does not indicate abnormality.
Don't worry about it.
