### ISSUE TITLE
traveling lora weights?

### ISSUE THREAD

**Issue by Cubey42** [s9roll7/animatediff-cli-prompt-travel#18]
First, thanks for this amazing repo, the potential is amazing already. I find myself using prompts to steer animatediff but using CN to design the frames. with lora, would it be possible to also let lora weights travel? like say I have a inference which has a scene change, I can use prompt travel to change the prompt to match, but being able to change which lora influences those frames would be huge.

**Comment by s9roll7** [comment]
I haven't tried it, but I think you can do something similar by varying the weight of the trigger word.

**Comment by Cubey42** [comment]
but doesn't adding it to lora map allow us to change the strength in the prompt? I didn't actually know that thank you.
