### ISSUE TITLE
lcm_map vs lcm scheduler

### ISSUE THREAD

**Issue by tnil25** [s9roll7/animatediff-cli-prompt-travel#185]
Hey @s9roll7,

Is there a difference between using the lcm scheduler and the lcm_map?

**Comment by s9roll7** [comment]
lcm lora is not applied if lcm scheduler is just selected.
enabling lcm_map applies lcm lora and forces the lcm scheduler to be selected

**Comment by tnil25** [comment]
Got it. Thanks!
