### ISSUE TITLE
use controlnet in different region

### ISSUE THREAD

**Issue by alanhuang67** [s9roll7/animatediff-cli-prompt-travel#191]
Hello,

just like to ask if it is possible to use different controlnet in different region?
for example, one controlnet for background only (says canny)
and another controlnet for region 1 (mask for person）with openpose + depth (only apply inside mask)?

Thanks!

**Comment by alanhuang67** [comment]
Thanks @s9roll7 and expect it happened in the feature!
and also it will be great if there is an option to use more than 2 LoRA in one region!

**Comment by s9roll7** [comment]
> if there is an option to use more than 2 LoRA in one region!

I think you can already do that.

**Comment by alanhuang67** [comment]
so use it just like below?

`
"lora_map": {
        "models/sd/link/Lora/SD1.5_style/LoRA001": {
            "region": ["1"],
            "scale": {"0": 1 }
        },
	"models/sd/link/Lora/SD1.5_style/LoRA001": {
			"region" : ["1"], 
			"scale" : {"0": 1}
		}
   },
`

**Comment by s9roll7** [comment]
That format should be fine.

**Comment by alanhuang67** [comment]
Thanks!!

**Comment by s9roll7** [comment]
6bf8bed
f4afca5

**Comment by s9roll7** [comment]
thnx for report
When using controlnet, there seems to be a bug that causes an error if a resolution other than a multiple of 64 is specified.
