### ISSUE TITLE
[error] gradual latent hires fix    TypeError: 'NoneType' object is not iterable 

### ISSUE THREAD

**Issue by dancemanUK** [s9roll7/animatediff-cli-prompt-travel#196]
G:\EasyPromptAnime\animatediff-cli-prompt-travel\venv\lib\site-packages\controlnet_aux\segment_anything\modeling\tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_512 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_512. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
02:00:58 INFO     diffuser_ver='0.23.0'                                                                                                                              cli.py:10002:00:59 INFO     Using generation config: sample_gradual_latent_hires_fix_1.json                                                                                    cli.py:313         INFO     is_sdxl=False                                                                                                                                     util.py:562         INFO     is_v2=True                                                                                                                                        util.py:540         INFO     Using base model: runwayml\stable-diffusion-v1-5                                                                                                   cli.py:340         INFO     Will save outputs to ./output\2023-12-10T02-00-59-simple-mistoonanime_v20                                                                          cli.py:348         INFO     Checking motion module...                                                                                                                     generate.py:610         INFO     Loading tokenizer...                                                                                                                          generate.py:634         INFO     Loading text encoder...                                                                                                                       generate.py:63602:01:00 INFO     Loading VAE...                                                                                                                                generate.py:638         INFO     Loading UNet...                                                                                                                               generate.py:64002:01:07 INFO     Loaded 453.20928M-parameter motion module                                                                                                         unet.py:578         INFO     Using scheduler "euler_a" (EulerAncestralDiscreteScheduler)                                                                                   generate.py:660         INFO     Loading weights from G:\EasyPromptAnime\animatediff-cli-prompt-travel\data\models\sd\mistoonAnime_v20.safetensors                             generate.py:66502:01:10 INFO     Merging weights into UNet...                                                                                                                  generate.py:682         INFO     Creating AnimationPipeline...                                                                                                                 generate.py:73202:01:11 INFO     No TI embeddings found                                                                                                                              ti.py:104         INFO     Sending pipeline to device "cuda"                                                                                                              pipeline.py:33         INFO     Selected data types: unet_dtype=torch.float16, tenc_dtype=torch.float16, vae_dtype=torch.bfloat16                                                device.py:90         INFO     Using channels_last memory format for UNet and VAE                                                                                              device.py:111╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ G:\EasyPromptAnime\animatediff-cli-prompt-travel\src\animatediff\cli.py:407 in generate          │
│                                                                                                  │
│    404 │   is_init_img_exist = img2img_map != None                                               │
│    405 │   region_condi_list, region_list, ip_adapter_config_map, region2index = region_preproc  │
│    406 │                                                                                         │
│ ❱  407 │   for c in controlnet_type_map:                                                         │
│    408 │   │   tmp_r = [region2index[r] for r in controlnet_type_map[c]["control_region_list"]]  │
│    409 │   │   controlnet_type_map[c]["control_region_list"] = [r for r in tmp_r if r != -1]     │
│    410 │   │   logger.info(f"{c=} / {controlnet_type_map[c]['control_region_list']}")            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: 'NoneType' object is not iterable

use your “gradual latent hires fix” demo,   sample_gradual_latent_hires_fix_1.mp4  prompt.json,  

00_123456_puparia-style_anime-screencap_1990s_style_masterpi.mp4 ,in 2023-12-03T18-48-40 ,it's  OK.

**Comment by dancemanUK** [comment]
"name": "simple",
    "path": "models/sd/mistoonAnime_v20.safetensors",
    "vae_path": "",
    "motion_module": "models\\motion-module\\improved3DMotion_improved3DV1.ckpt",
    "gradual_latent_hires_fix_map": {
        "enable": true,
        "scale": {
            "0": 0.5,
            "0.7": 1.0
        },
        "reverse_steps": 5,
        "noise_add_count": 3
    },
    "compile": false,
    "tensor_interpolation_slerp": true,
    "seed": [
        123456
    ],
    "scheduler": "euler_a",
    "steps": 20,
    "guidance_scale": 10.0,
    "unet_batch_size": 1,
    "clip_skip": 2,
    "prompt_fixed_ratio": 1.0,
    "head_prompt": "",

**Comment by s9roll7** [comment]
[b6fbe11](https://github.com/s9roll7/animatediff-cli-prompt-travel/commit/b6fbe11b47c5a86a33ca6e4e7546ec72222d5565)
