### ISSUE TITLE
Output  quality for img2img become lower

### ISSUE THREAD

**Issue by alanhuang67** [s9roll7/animatediff-cli-prompt-travel#199]
After updating to the latest bug fix version, the image quality of img2img becomes lower and blurry.

**Comment by s9roll7** [comment]
> After updating to the latest bug fix version, the image quality of img2img becomes lower and blurry.

can  you upload json file?

**Comment by alanhuang67** [comment]
b6fbe11b47c5a86a33ca6e4e7546ec72222d5565

json here
[1206_HAND.json](https://github.com/s9roll7/animatediff-cli-prompt-travel/files/13627442/1206_HAND.json)

output sample before update
![00000001](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/10071840/cd73cc2d-4af2-4504-9b1e-617c917758fb)

after update
![00000014](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/10071840/959f4c32-7c63-4823-8db3-52af78078899)

**Comment by s9roll7** [comment]
Thank you. I know what caused it.
The latest version is to reduce ram capacity and generation time.
The resolution of controlnet is reduced to (512,*) except for "controlnet_tile".
I thought that everything except "tile" would have no effect on the results, but I was wrong.

If you want to fix it now, the following should fix it

https://github.com/s9roll7/animatediff-cli-prompt-travel/blob/685903f39852f978337306bd1cd7bdcc0b29fb50/src/animatediff/pipelines/animation.py#L2780

` no_shrink_type = ["controlnet_tile", "controlnet_depth"] `

**Comment by alanhuang67** [comment]
Thanks so much!

do I need to add openpose if I use it?

**Comment by s9roll7** [comment]
Perhaps openpose doesn't affect the quality even if the resolution is low.

**Comment by alanhuang67** [comment]
@s9roll7 
hello, it still have blur situation after your update!

![00000007](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/10071840/4b0e44c8-5354-48cb-8baa-c26cb6d8bf5d)
