### ISSUE TITLE
Any tips for upscaling?

### ISSUE THREAD

**Issue by xnmt9** [s9roll7/animatediff-cli-prompt-travel#20]
Whenever I run an uspcale (usually with controlnet_tile) it seems to introduce a lot of jittering and variance frame to frame. Curious if anyone has had success with upscale settings to polish up generations

**Comment by s9roll7** [comment]
I am using tile + ip2p and there seems to be a flicker in the areas not affected by the lora.
In this video I am using lora on the characters and there is little to no flickering on the characters.
I have not tried it, but maybe I should have used lora in the background when generating it.


original
animatediff generate -c CONFIG_JSON_PATH -W 512 -H 768 -L 128 -C 16
<div><video controls src="https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/118420657/75a1e40a-7926-45e2-84bc-1dfe8ba6ad5a" muted="false"></video></div>
<br>

animatediff tile-upscale FRAME_DIR -W 768

```
    "upscale_config": {
        "scheduler": "k_dpmpp_sde",
        "steps": 20,
        "strength": 0.5,
        "guidance_scale": 10,
        "controlnet_tile": {
            "enable": true,
            "controlnet_conditioning_scale": 1.0,
            "guess_mode": false,
            "control_guidance_start": 0.0,
            "control_guidance_end": 1.0
        },
        "controlnet_line_anime": {
            "enable": false,
            "controlnet_conditioning_scale": 1.0,
            "guess_mode": false,
            "control_guidance_start": 0.0,
            "control_guidance_end": 1.0
        },
        "controlnet_ip2p": {
            "enable": true,
            "controlnet_conditioning_scale": 0.5,
            "guess_mode": false,
            "control_guidance_start": 0.0,
            "control_guidance_end": 1.0
        },
        "controlnet_ref": {
            "enable": false,
            "use_frame_as_ref_image": false,
            "use_1st_frame_as_ref_image": false,
            "ref_image": "ref_image/path_to_your_ref_img.jpg",
            "attention_auto_machine_weight": 1.0,
            "gn_auto_machine_weight": 1.0,
            "style_fidelity": 0.25,
            "reference_attn": true,
            "reference_adain": false
        }
    },
```

<div><video controls src="https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/118420657/0d81f9ed-3346-43cf-a09d-e0e25d3c54fe" muted="false"></video></div>
<br>

**Comment by xnmt9** [comment]
this is great thanks - I'll try it + also test out background loras to see if it helps
