### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by alanhuang67** [s9roll7/animatediff-cli-prompt-travel#203]
Hello!

My friend got the issue below, his VPN seems good and able to access huggingface but not sure how this happend, any suggestion he can slove this?

SSLError: HTTpsConnectionpooldhost='rawgithubusercontentcom  oort-443): Maxretries exceeded with url:
/huggingface/diffusers/main/examples/community/lpw stable diffusion.py (Causecby SLError(ssLCertVerificationError(1,[SSL: CERTIFICATE VERIFY FAILED]certificate verify failed: certificate has expired ( ssl.c:997)')))Generator process exited with code 1

or

SSLError: HTTPsConnectionPool(host='raw.githubusercontent.com', port-443): Max retries exceeded with url:Compvis/stable-diffusion/main/configs/stable-diffusion/v1-inference.yaml (Caused by SSLError(SSLEOFError(8，'E0Poccurred in violation of protocol (_ssl.c:997)1)))

Thanks!

**Comment by s9roll7** [comment]
ttps://github.com/huggingface/transformers/issues/17611
this?

**Comment by alanhuang67** [comment]
Yes! Thanks!
