### ISSUE TITLE
Improving likeness with controlnet_ref

### ISSUE THREAD

**Issue by runshouse** [s9roll7/animatediff-cli-prompt-travel#212]
I'd like to use an initial image and have the first frame of the video be nearly identical to that image. I've played with different controlnet_ref settings and none seem to get likeness to 100% even at max settings. Any tips?

**Comment by toshi4556** [comment]
ValueError: controlnet_ref is not available in this configuration. unet_batch_size=1 < 2

I don't understand what the error means

Someone please tell me
