### ISSUE TITLE
No consistency between frames and bad images

### ISSUE THREAD

**Issue by DaLizardWizard** [s9roll7/animatediff-cli-prompt-travel#238]
This is what the frames look like in my outputs folder when using the example images provided 

<img width="732" alt="image" src="https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/75072026/3669198c-beb5-457b-89b8-b00941331bc7">

I am using stable diffusion v 1.5, with the motion 1.5v2 model along with canny edge detection.

Has anyone seen this before? 

[prompt_travel.json](https://github.com/s9roll7/animatediff-cli-prompt-travel/files/14351007/prompt_travel.json)

**Comment by DaLizardWizard** [comment]
![00_341774366206100_masterpiece_best-quality_a-beautiful-and-detailed-](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/75072026/af51c149-aa2d-41c1-ace0-c65934a9aac3)
This is what I get as an output where there is no smooth frames

**Comment by threelab** [comment]
I don't understand what you're saying. Do you need to create images with continuous changes

**Comment by DaLizardWizard** [comment]
No I want the frames to be smooth, but I seem to be getting no smoothness or latent space interpolation using the command. I am using the motion module 1.5v2. I have disabled all controlnet options apart from canny edge.

`animatediff generate -c config/prompts/prompt_travel.json -W 512 -H 768 -L 128 -C 16`

**Comment by DaLizardWizard** [comment]
Solved, Both a mixture of using the wrong motion module. Now using the correct motion module v2
