### ISSUE TITLE
'animatediff' is an internal or external command, It is not recognized as an operable program or batch file.

### ISSUE THREAD

**Issue by k-a-s-o-u** [s9roll7/animatediff-cli-prompt-travel#25]
Hi, perhaps this is silly question but please help.
I followed the instructions of installation but this error came out.
Do I have to combine this library with original [Animatediff](https://github.com/guoyww/AnimateDiff) to run?

(venv) D:\animatediff-cli-prompt-travel>animatediff generate -c config/prompts/prompt_travel.json -W 256 -H 384 -L 128 -C 16
'animatediff' is an internal or external command,
It is not recognized as an operable program or batch file.

(venv) D:\animatediff-cli-prompt-travel>animatediff --help
'animatediff' is an internal or external command,
It is not recognized as an operable program or batch file.

**Comment by s9roll7** [comment]
> Do I have to combine this library with original [Animatediff](https://github.com/guoyww/AnimateDiff) to run?

no need.
Did you perform the installation completely with these exact commands?
https://github.com/s9roll7/animatediff-cli-prompt-travel#installationfor-windows

**Comment by k-a-s-o-u** [comment]
It looks like python -m pip install -e .
has not completed at last time I've done.
After that I run 
animatediff generate -c config/prompts/prompt_travel.json -W 256 -H 384 -L 128 -C 16

but this error came out.
ModuleNotFoundError: No module named 'controlnet_aux.processor'

pip install controlnet_aux
animatediff generate -c config/prompts/prompt_travel.json -W 256 -H 384 -L 128 -C 16

and then this error came out...
I completely followed this instruction but why only I got these complex error?
https://github.com/s9roll7/animatediff-cli-prompt-travel#installationfor-windows


===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
D:\Python\Python310\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
CUDA SETUP: Loading binary D:\Python\Python310\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.0.1+cpu)
    Python  3.10.11 (you have 3.10.6)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
D:\Python\Python310\lib\site-packages\controlnet_aux\mediapipe_face\mediapipe_face_common.py:7: UserWarning: The module 'mediapipe' is not installed. The package will have limited functionality. Please install it using the command: pip install 'mediapipe'
  warnings.warn(
23:42:16 INFO     Using generation config: config\prompts\prompt_travel.json                                 cli.py:269
┌─────────────────────────────── Traceback (most recent call last) ────────────────────────────────┐
│ D:\animatediff-cli-prompt-travel\src\animatediff\cli.py:270 in generate                          │
│                                                                                                  │
│   267 │                                                                                          │
│   268 │   config_path = config_path.absolute()                                                   │
│   269 │   logger.info(f"Using generation config: {path_from_cwd(config_path)}")                  │
│ > 270 │   model_config: ModelConfig = get_model_config(config_path)                              │
│   271 │   infer_config: InferenceConfig = get_infer_config()                                     │
│   272 │                                                                                          │
│   273 │   # set sane defaults for context, overlap, and stride if not supplied                   │
│                                                                                                  │
│ D:\animatediff-cli-prompt-travel\src\animatediff\settings.py:124 in get_model_config             │
│                                                                                                  │
│   121                                                                                            │
│   122 @lru_cache(maxsize=2)                                                                      │
│   123 def get_model_config(config_path: Path) -> ModelConfig:                                    │
│ > 124 │   settings = ModelConfig(json_config_path=config_path)                                   │
│   125 │   return settings                                                                        │
│   126                                                                                            │
│                                                                                                  │
│ in pydantic.env_settings.BaseSettings.__init__:40                                                │
│                                                                                                  │
│ in pydantic.env_settings.BaseSettings._build_values:75                                           │
│                                                                                                  │
│ D:\animatediff-cli-prompt-travel\src\animatediff\settings.py:44 in __call__                      │
│                                                                                                  │
│    41 │   │   for idx, path in enumerate(self.json_config_path):                                 │
│    42 │   │   │   if path.exists() and path.is_file():  # check if the path exists and is a fi   │
│    43 │   │   │   │   logger.debug(f"{classname}: loading config #{idx+1} from {path}")          │
│ >  44 │   │   │   │   merged_config.update(json.loads(path.read_text(encoding=encoding)))        │
│    45 │   │   │   │   logger.debug(f"{classname}: config state #{idx+1}: {merged_config}")       │
│    46 │   │   │   else:                                                                          │
│    47 │   │   │   │   raise FileNotFoundError(f"{classname}: config #{idx+1} at {path} not fou   │
│                                                                                                  │
│ D:\Python\Python310\lib\json\__init__.py:346 in loads                                            │
│                                                                                                  │
│   343 │   if (cls is None and object_hook is None and                                            │
│   344 │   │   │   parse_int is None and parse_float is None and                                  │
│   345 │   │   │   parse_constant is None and object_pairs_hook is None and not kw):              │
│ > 346 │   │   return _default_decoder.decode(s)                                                  │
│   347 │   if cls is None:                                                                        │
│   348 │   │   cls = JSONDecoder                                                                  │
│   349 │   if object_hook is not None:                                                            │
│                                                                                                  │
│ D:\Python\Python310\lib\json\decoder.py:337 in decode                                            │
│                                                                                                  │
│   334 │   │   containing a JSON document).                                                       │
│   335 │   │                                                                                      │
│   336 │   │   """                                                                                │
│ > 337 │   │   obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                  │
│   338 │   │   end = _w(s, end).end()                                                             │
│   339 │   │   if end != len(s):                                                                  │
│   340 │   │   │   raise JSONDecodeError("Extra data", s, end)                                    │
│                                                                                                  │
│ D:\Python\Python310\lib\json\decoder.py:355 in raw_decode                                        │
│                                                                                                  │
│   352 │   │   try:                                                                               │
│   353 │   │   │   obj, end = self.scan_once(s, idx)                                              │
│   354 │   │   except StopIteration as err:                                                       │
│ > 355 │   │   │   raise JSONDecodeError("Expecting value", s, err.value) from None               │
│   356 │   │   return obj, end                                                                    │
│   357                                                                                            │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by s9roll7** [comment]
If the installation was successful, controlnet_aux should have been installed automatically, 
so the installation seems to have failed.

```
install_requires =
    accelerate >= 0.20.3
    colorama >= 0.4.3, < 0.5.0
    cmake >= 3.25.0
    diffusers == 0.18.2
    einops >= 0.6.1
    gdown >= 4.6.6
    ninja >= 1.11.0
    numpy >= 1.22.4
    omegaconf >= 2.3.0
    pillow >= 9.4.0, < 10.0.0
    pydantic >= 1.10.0, < 2.0.0
    rich >= 13.0.0, < 14.0.0
    safetensors >= 0.3.1
    sentencepiece >= 0.1.99
    shellingham >= 1.5.0, < 2.0.0
    torch >= 2.0.0, < 2.2.0
    torchaudio
    torchvision
    transformers >= 4.30.2
    typer >= 0.9.0, < 1.0.0
    controlnet_aux
    matplotlib
```

**Comment by k-a-s-o-u** [comment]
I deleted venv folder and recreated it. also some other errors occurred and fixed them all then finally worked!
Thank you for your help!

**Comment by screan** [comment]
getting this same error 

WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.0.1+cpu)
