### ISSUE TITLE
The video program has frozen or become unresponsive

### ISSUE THREAD

**Issue by Gg811218** [s9roll7/animatediff-cli-prompt-travel#31]
The images can be extracted, but the configuration file cannot be generated, and the program continues to run indefinitely without completing. I have to force close it.
    Only the model and prompts were changed in the settings, everything else remained unchanged

![1](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/144506146/ca173bf3-4dfe-4b80-a5c7-0746f69757a3)
![2](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/144506146/9b286b88-cbc6-43d6-be0f-adc66fb2ce32)

**Comment by s9roll7** [comment]
What happens if you rename a checkpoint so that it does not contain "."?
xxmix_9realistic_v4.0.safetensors -> xxmix_9realistic_v40.safetensors

**Comment by Gg811218** [comment]
Thank you for the response. The issue has been resolved after setting up a new environment.
