### ISSUE TITLE
Question: Is there a preview mode to review some keyframes?

### ISSUE THREAD

**Issue by hylarucoder** [s9roll7/animatediff-cli-prompt-travel#35]
I really enjoyed make videos on this project, but sometimes I feel a bit lost when trying to preview specific keyframes. For example, when I need to review the frames at 00:05, 00:10, 00:15… those moments are critical for ensuring the quality of the videos.

For now, i must produce and upscaled , retry, retry, retry till some frames looks good.

**Comment by s9roll7** [comment]
Because of the way animatediff works, all frames are generated gradually, so no frame is ever complete until it is finished.
There is a debugging option in stylize to generate only 16 frames from a specific location.

```
# generate(test run)
# 16 frames
animatediff stylize generate STYLYZE_DIR -L 16
# 16 frames from the 200th frame
animatediff stylize generate STYLYZE_DIR -L 16 -FO 200
```
