### ISSUE TITLE
can I change the number of steps in the upscale stylize?

### ISSUE THREAD

**Issue by Cubey42** [s9roll7/animatediff-cli-prompt-travel#36]
I'm curious if it really needs the equal number of steps, I'm just comparing to hires.fix process and don't really know, but I tried to add steps to the config and it didn't work.

**Comment by s9roll7** [comment]
93b6437

```
        "1": {
            "steps": 15,
            "guidance_scale": 8.0,
            "width": 768,
            "height": 768,
            "length": 136,
            "context": 8,

```

**Comment by Cubey42** [comment]
doesn't seem to still be taking effect

**Comment by Cubey42** [comment]
disregard, skill issue

**Comment by s9roll7** [comment]
f42d385
😅

**Comment by Cubey42** [comment]
thanks, I didn't wanna open something else to ask, but do you think different controlnet imagedir is possible? (like one for lineart, one for openpose)?

**Comment by s9roll7** [comment]
Hmmm. I don't know what you want to do.
Are you saying you want to do something else, not upscale with the second generation?

**Comment by Cubey42** [comment]
oh sorry not related to the upscale, but 0. I want blend multiple images together. like have lineart_anime reference a different frame dataset, while open_pose uses another using unique guidance strategies.

**Comment by s9roll7** [comment]
If you want to do something special like that,
you will need to do the preprocessing yourself.

```
        "controlnet_lineart": {
            "enable": true,
            "use_preprocessor": false,      <------------
            "guess_mode": false,
            "controlnet_conditioning_scale": 1.0,
            "control_guidance_start": 0.0,
            "control_guidance_end": 1.0,
            "control_scale_list": [
            ]
        },
```

**Comment by Cubey42** [comment]
but I can only have one directory for images, the idea was I could have 2 0000.png's for a frame. but maybe that isn't possible...

**Comment by s9roll7** [comment]
https://github.com/s9roll7/animatediff-cli-prompt-travel/issues/6#issuecomment-1694406432

Don't you want to do something like this 19.mp4?
You can use it as is by preparing a preprocessed image yourself and setting "use_preprocessor": false,.

**Comment by Cubey42** [comment]
Yeah I'll look into it, thank you.
also, there is a discord with alot of the people working with repos for animatediff, including Neggles who made the CLI refactor on https://discord.gg/8XPKnPkq , you should stop by!

**Comment by Cubey42** [comment]
also, could you add repeat to stylize as well?

**Comment by Cubey42** [comment]
Apologies again, when I set the preprocessor to false, it doesn't seem to be activating the controlnets.
