### ISSUE TITLE
OpenPose preprocessing halts indefinitely on step 0

### ISSUE THREAD

**Issue by advo-kat** [s9roll7/animatediff-cli-prompt-travel#37]
As described in the title. Not sure what is going on. Had a similar issue with stylize as well just halting. This is on Windows.

**Comment by advo-kat** [comment]
The required model files didn't copy to data/models/DWPose

I downloaded "dw-ll_ucoco_384.onnx"," yolox_l.onnx", manually from https://huggingface.co/yzd-v/DWPose/tree/main and put them in the above path and it works now. There's a similar issue with stylize, it's likely to be a problem on Windows only, maybe with the way the Python copy file or dir command is used?

**Comment by advo-kat** [comment]
It'll be this line probably that's the culprit on Windows

`hf_hub_download(
            repo_id="yzd-v/DWPose", subfolder=PurePosixPath(path.parent), filename=PurePosixPath(path.name), local_dir="data/models/DWPose"`

**Comment by s9roll7** [comment]
I have never run this program outside of windows.
Are you able to download it to the cache of huggingface? Or is the download itself not working?

**Comment by advo-kat** [comment]
The files download, but don't end up in the created directories for some reason. Re-running the command simply hangs the CLI without further downloads. When I manually download to the created directories the commands work. Is the downloader perhaps creating a symlink or something, because those aren't supported on non-admin accounts which is what I'm using.

**Comment by s9roll7** [comment]
The specification seems to be to create or not to create symbolic links depending on the size.

Can it be fixed by modifying it as follows?
```
        hf_hub_download(
            repo_id="yzd-v/DWPose", subfolder=PurePosixPath(path.parent), filename=PurePosixPath(path.name), local_dir="data/models/DWPose", local_dir_use_symlinks=False
        )
```

**Comment by s9roll7** [comment]
animatediff-cli\data\models\DWPose

C:\Users\your_user_name\.cache\huggingface\hub\models--yzd-v--DWPose

**Comment by s9roll7** [comment]
#42
