### ISSUE TITLE
First try, AttributeError: 'Attention' object has no attribute 'to_to_k'

### ISSUE THREAD

**Issue by GuruVirus** [s9roll7/animatediff-cli-prompt-travel#38]
Run command: **animatediff generate -c config\prompts\prompt_travel.json**
In prompt_travel.json I only changed the model and the motion paths. What else do I need to change?
Beyond the "win setup" readme instructions, I had an error at first which said to run pip install mediapipe
I have not copied over any controlnet models and haven't toggled any of the fields to disable, just looking for defaults that work.

> ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
> │ C:\a\animatediff-cli-prompt-travel\src\animatediff\cli.py:322 in generate     │
> │                                                                                                  │
> │    319 │   global g_pipeline                                                                     │
> │    320 │   global last_model_path                                                                │
> │    321 │   if g_pipeline is None or last_model_path != model_config.path.resolve():              │
> │ ❱  322 │   │   g_pipeline = create_pipeline(                                                     │
> │    323 │   │   │   base_model=base_model_path,                                                   │
> │    324 │   │   │   model_config=model_config,                                                    │
> │    325 │   │   │   infer_config=infer_config,                                                    │
> │                                                                                                  │
> │ C:\a\animatediff-cli-prompt-travel\src\animatediff\generate.py:321 in         │
> │ create_pipeline                                                                                  │
> │                                                                                                  │
> │    318 │   │   logger.info(f"Loading weights from {model_path}")                                 │
> │    319 │   │   if model_path.is_file():                                                          │
> │    320 │   │   │   logger.debug("Loading from single checkpoint file")                           │
> │ ❱  321 │   │   │   unet_state_dict, tenc_state_dict, vae_state_dict = get_checkpoint_weights(mo  │
> │    322 │   │   elif model_path.is_dir():                                                         │
> │    323 │   │   │   logger.debug("Loading from Diffusers model directory")                        │
> │    324 │   │   │   temp_pipeline = StableDiffusionPipeline.from_pretrained(model_path)           │
> │                                                                                                  │
> │ C:\a\animatediff-cli-prompt-travel\src\animatediff\utils\model.py:73 in       │
> │ get_checkpoint_weights                                                                           │
> │                                                                                                  │
> │    70                                                                                            │
> │    71 def get_checkpoint_weights(checkpoint: Path):                                              │
> │    72 │   temp_pipeline: StableDiffusionPipeline                                                 │
> │ ❱  73 │   temp_pipeline, _ = checkpoint_to_pipeline(checkpoint, save=False)                      │
> │    74 │   unet_state_dict = temp_pipeline.unet.state_dict()                                      │
> │    75 │   tenc_state_dict = temp_pipeline.text_encoder.state_dict()                              │
> │    76 │   vae_state_dict = temp_pipeline.vae.state_dict()                                        │
> │                                                                                                  │
> │ C:\a\animatediff-cli-prompt-travel\src\animatediff\utils\model.py:58 in       │
> │ checkpoint_to_pipeline                                                                           │
> │                                                                                                  │
> │    55 │   if target_dir is None:                                                                 │
> │    56 │   │   target_dir = pipeline_dir.joinpath(checkpoint.stem)                                │
> │    57 │                                                                                          │
> │ ❱  58 │   pipeline = StableDiffusionPipeline.from_single_file(                                   │
> │    59 │   │   pretrained_model_link_or_path=str(checkpoint.absolute()),                          │
> │    60 │   │   local_files_only=True,                                                             │
> │    61 │   │   load_safety_checker=False,                                                         │
> │                                                                                                  │
> │ c:\a\animatediff-cli-prompt-travel\venv\lib\site-packages\diffusers\loaders.p │
> │ y:1471 in from_single_file                                                                       │
> │                                                                                                  │
> │   1468 │   │   │   │   force_download=force_download,                                            │
> │   1469 │   │   │   )                                                                             │
> │   1470 │   │                                                                                     │
> │ ❱ 1471 │   │   pipe = download_from_original_stable_diffusion_ckpt(                              │
> │   1472 │   │   │   pretrained_model_link_or_path,                                                │
> │   1473 │   │   │   pipeline_class=cls,                                                           │
> │   1474 │   │   │   model_type=model_type,                                                        │
> │                                                                                                  │
> │ c:\a\animatediff-cli-prompt-travel\venv\lib\site-packages\diffusers\pipelines │
> │ \stable_diffusion\convert_from_ckpt.py:1374 in download_from_original_stable_diffusion_ckpt      │
> │                                                                                                  │
> │   1371 │   │   │   vae = AutoencoderKL(**vae_config)                                             │
> │   1372 │   │                                                                                     │
> │   1373 │   │   for param_name, param in converted_vae_checkpoint.items():                        │
> │ ❱ 1374 │   │   │   set_module_tensor_to_device(vae, param_name, "cpu", value=param)              │
> │   1375 │   else:                                                                                 │
> │   1376 │   │   vae = AutoencoderKL.from_pretrained(vae_path)                                     │
> │   1377                                                                                           │
> │                                                                                                  │
> │ c:\a\animatediff-cli-prompt-travel\venv\lib\site-packages\accelerate\utils\mo │
> │ deling.py:269 in set_module_tensor_to_device                                                     │
> │                                                                                                  │
> │    266 │   if "." in tensor_name:                                                                │
> │    267 │   │   splits = tensor_name.split(".")                                                   │
> │    268 │   │   for split in splits[:-1]:                                                         │
> │ ❱  269 │   │   │   new_module = getattr(module, split)                                           │
> │    270 │   │   │   if new_module is None:                                                        │
> │    271 │   │   │   │   raise ValueError(f"{module} has no attribute {split}.")                   │
> │    272 │   │   │   module = new_module                                                           │
> │                                                                                                  │
> │ c:\a\animatediff-cli-prompt-travel\venv\lib\site-packages\torch\nn\modules\mo │
> │ dule.py:1614 in __getattr__                                                                      │
> │                                                                                                  │
> │   1611 │   │   │   modules = self.__dict__['_modules']                                           │
> │   1612 │   │   │   if name in modules:                                                           │
> │   1613 │   │   │   │   return modules[name]                                                      │
> │ ❱ 1614 │   │   raise AttributeError("'{}' object has no attribute '{}'".format(                  │
> │   1615 │   │   │   type(self).__name__, name))                                                   │
> │   1616 │                                                                                         │
> │   1617 │   def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:             │
> ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
> AttributeError: 'Attention' object has no attribute 'to_to_k'

**Comment by s9roll7** [comment]
can you try this checkpoint?
https://civitai.com/models/24149/mistoonanime

**Comment by GuruVirus** [comment]
It ran and gave me an output. What's with the model specificity?

**Comment by s9roll7** [comment]
Only SD15 checkpoints are supported by animatediff

**Comment by GuruVirus** [comment]
Here's a SD15 one that breaks for me. The thing that stands out is it is a much larger file size, maybe a full model and not ema-only: https://civitai.com/models/107842/aniverse

**Comment by s9roll7** [comment]
https://github.com/huggingface/diffusers/issues/4790

**Comment by s9roll7** [comment]
I found the cause.
I'm going to add a command to fix checkpoint.

**Comment by s9roll7** [comment]
7a95642

**Comment by GuruVirus** [comment]
I updated, but am still getting the same thing.

 INFO     Loading weights from                                                                   generate.py:318
                  C:\animatediff-cli-prompt-travel\data\models\sd\aniverse_THXEd14.
                  safetensors
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\animatediff-cli-prompt-travel\src\animatediff\cli.py:323 in generate     │
│                                                                                                  │
│    320 │   global g_pipeline                                                                     │
│    321 │   global last_model_path                                                                │
│    322 │   if g_pipeline is None or last_model_path != model_config.path.resolve():              │
│ ❱  323 │   │   g_pipeline = create_pipeline(                                                     │
│    324 │   │   │   base_model=base_model_path,                                                   │
│    325 │   │   │   model_config=model_config,                                                    │
│    326 │   │   │   infer_config=infer_config,                                                    │
│                                                                                                  │
│ C:\animatediff-cli-prompt-travel\src\animatediff\generate.py:321 in         │
│ create_pipeline                                                                                  │
│                                                                                                  │
│    318 │   │   logger.info(f"Loading weights from {model_path}")                                 │
│    319 │   │   if model_path.is_file():                                                          │
│    320 │   │   │   logger.debug("Loading from single checkpoint file")                           │
│ ❱  321 │   │   │   unet_state_dict, tenc_state_dict, vae_state_dict = get_checkpoint_weights(mo  │
│    322 │   │   elif model_path.is_dir():                                                         │
│    323 │   │   │   logger.debug("Loading from Diffusers model directory")                        │
│    324 │   │   │   temp_pipeline = StableDiffusionPipeline.from_pretrained(model_path)           │
│                                                                                                  │
│ C:\animatediff-cli-prompt-travel\src\animatediff\utils\model.py:139 in      │
│ get_checkpoint_weights                                                                           │
│                                                                                                  │
│   136                                                                                            │
│   137 def get_checkpoint_weights(checkpoint: Path):                                              │
│   138 │   temp_pipeline: StableDiffusionPipeline                                                 │
│ ❱ 139 │   temp_pipeline, _ = checkpoint_to_pipeline(checkpoint, save=False)                      │
│   140 │   unet_state_dict = temp_pipeline.unet.state_dict()                                      │
│   141 │   tenc_state_dict = temp_pipeline.text_encoder.state_dict()                              │
│   142 │   vae_state_dict = temp_pipeline.vae.state_dict()                                        │
│                                                                                                  │
│ C:\animatediff-cli-prompt-travel\src\animatediff\utils\model.py:124 in      │
│ checkpoint_to_pipeline                                                                           │
│                                                                                                  │
│   121 │   if target_dir is None:                                                                 │
│   122 │   │   target_dir = pipeline_dir.joinpath(checkpoint.stem)                                │
│   123 │                                                                                          │
│ ❱ 124 │   pipeline = StableDiffusionPipeline.from_single_file(                                   │
│   125 │   │   pretrained_model_link_or_path=str(checkpoint.absolute()),                          │
│   126 │   │   local_files_only=True,                                                             │
│   127 │   │   load_safety_checker=False,                                                         │
│                                                                                                  │
│ c:\animatediff-cli-prompt-travel\venv\lib\site-packages\diffusers\loaders.p │
│ y:1471 in from_single_file                                                                       │
│                                                                                                  │
│   1468 │   │   │   │   force_download=force_download,                                            │
│   1469 │   │   │   )                                                                             │
│   1470 │   │                                                                                     │
│ ❱ 1471 │   │   pipe = download_from_original_stable_diffusion_ckpt(                              │
│   1472 │   │   │   pretrained_model_link_or_path,                                                │
│   1473 │   │   │   pipeline_class=cls,                                                           │
│   1474 │   │   │   model_type=model_type,                                                        │
│                                                                                                  │
│ c:\animatediff-cli-prompt-travel\venv\lib\site-packages\diffusers\pipelines │
│ \stable_diffusion\convert_from_ckpt.py:1374 in download_from_original_stable_diffusion_ckpt      │
│                                                                                                  │
│   1371 │   │   │   vae = AutoencoderKL(**vae_config)                                             │
│   1372 │   │                                                                                     │
│   1373 │   │   for param_name, param in converted_vae_checkpoint.items():                        │
│ ❱ 1374 │   │   │   set_module_tensor_to_device(vae, param_name, "cpu", value=param)              │
│   1375 │   else:                                                                                 │
│   1376 │   │   vae = AutoencoderKL.from_pretrained(vae_path)                                     │
│   1377                                                                                           │
│                                                                                                  │
│ c:\animatediff-cli-prompt-travel\venv\lib\site-packages\accelerate\utils\mo │
│ deling.py:269 in set_module_tensor_to_device                                                     │
│                                                                                                  │
│    266 │   if "." in tensor_name:                                                                │
│    267 │   │   splits = tensor_name.split(".")                                                   │
│    268 │   │   for split in splits[:-1]:                                                         │
│ ❱  269 │   │   │   new_module = getattr(module, split)                                           │
│    270 │   │   │   if new_module is None:                                                        │
│    271 │   │   │   │   raise ValueError(f"{module} has no attribute {split}.")                   │
│    272 │   │   │   module = new_module                                                           │
│                                                                                                  │
│ c:\animatediff-cli-prompt-travel\venv\lib\site-packages\torch\nn\modules\mo │
│ dule.py:1614 in __getattr__                                                                      │
│                                                                                                  │
│   1611 │   │   │   modules = self.__dict__['_modules']                                           │
│   1612 │   │   │   if name in modules:                                                           │
│   1613 │   │   │   │   return modules[name]                                                      │
│ ❱ 1614 │   │   raise AttributeError("'{}' object has no attribute '{}'".format(                  │
│   1615 │   │   │   type(self).__name__, name))                                                   │
│   1616 │                                                                                         │
│   1617 │   def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Attention' object has no attribute 'to_to_k'

**Comment by GuruVirus** [comment]
For the record, it's just that model type (pruned vs ema-only). I was able to run the config using another model with similar size to mistoon.
If you wanted to compare model weights for testing maybe use SD1.5 pruned and ema: https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main

**Comment by s9roll7** [comment]
use this command first
`animatediff fix-checkpoint aniverse_THXEd14.safetensors`
then, use aniverse_THXEd14_fixed.safetensors instead

**Comment by GuruVirus** [comment]
Command completed only when using the absolute path in format "C:\animatediff-cli-prompt-travel\data\models\sd\model\aniverse_THXEd14.safetensors"

I was able to run inference.

I noticed another issue related to models: no VAE specification. Mistoon works well because it has an embedded VAE. Please add a VAE parameter (should I make a new issue?).

I can tell other models are not using a VAE causing low quality, washed out results (grayscaling, desaturation).

**Comment by s9roll7** [comment]
I don't have a model that doesn't have vae embedded in it.
Can you post a link?

**Comment by GuruVirus** [comment]
Here's dreamshaper 6 no vae: https://civitai.com/models/4384?modelVersionId=80261

**Comment by GuruVirus** [comment]
In general, all this repo would need to do is download the official most recent VAE: https://huggingface.co/stabilityai/sd-vae-ft-mse-original/resolve/main/vae-ft-mse-840000-ema-pruned.ckpt into /data/models/vae (new folder)
And then apply it by default if the model doesn't have one. Or have a -V flag for it to toggle on.

**Comment by GuruVirus** [comment]
Just a heads up there's something strange either with the inference here or with the fixed safetensors model. It continues to basically give me the same output (character portrait and a similar background) every time no matter what I change in the prompt.

I exited venv and re-ran activate.bat just in case.

I reset my prompt to 1 token in positive, no negatives. This time I actually got a noticeable variation (different face, clothes, and background) but still nothing similar to what I would get out of a normal SD1.5 inference in A1111's (which I'm using to fine tune the prompt and select a test seed).

**Comment by s9roll7** [comment]
4006314

```
{
  "name": "simple",
  "path": "share/Stable-diffusion/dreamshaper_6NoVae.safetensors",
  "vae_path": "models/huggingface/runwayml/stable-diffusion-v1-5/vae",       # <-------------
  "motion_module": "models/motion-module/mm_sd_v15_v2.ckpt",
  "compile": false,
```

you need diffusers format vae, so you need to convert your own pt files.
https://github.com/huggingface/diffusers/blob/main/scripts/convert_vae_pt_to_diffusers.py

**Comment by GuruVirus** [comment]
I put the script and the vae into the venv folder.
Created venv/dump
Ran the script, it put a json file in the dump folder and the converted model named as "diffusion_pytorch_model.bin"
I copied that over to and renamed as data/vae/vae-ft-mse-840000-ema-pruned.bin
I updated the prompt config with the vae_path parameter.

`ValidationError: 1 validation error for ModelConfig
vae_path
  extra fields not permitted (type=value_error.extra)`

**Comment by s9roll7** [comment]
[4b262a0](https://github.com/s9roll7/animatediff-cli-prompt-travel/commit/4b262a025684f6364a5e5bb53a93c5949456330d)
