### ISSUE TITLE
mm_sd_v15_v2.safetensors does not exist or is  not a file!

### ISSUE THREAD

**Issue by entrpn** [s9roll7/animatediff-cli-prompt-travel#40]
In `generate.py`, I am getting this error

Motion module /home/foo/apps/animatediff-cli-prompt-travel/data/models/Motion_Module/mm_sd_v15_v2.safetensors does not exist or is  not a file!

Coming from this line of code:

```python
            if not (motion_module.exists() and motion_module.is_file()):
                # this should never happen, but just in case...
                raise FileNotFoundError(f"Motion module {motion_module} does not exist or is not a file!")
```

Looks like the logic is checking for the file to be safetensors but I have a ckpt file. Thanks

**Comment by s9roll7** [comment]
Are you sure you have set the correct path for "motion_module"?
```
# prompt_travel.json
{
  "name": "sample",
  "path": "share/Stable-diffusion/mistoonAnime_v20.safetensors",  # Specify Checkpoint as a path relative to /animatediff-cli/data
  "motion_module": "models/motion-module/mm_sd_v14.ckpt",         # Specify motion module as a path relative to /animatediff-cli/data
  "compile": false,

```

**Comment by entrpn** [comment]
Thanks, I got it to work. I don't know why but my motion module folder name was `Motion_Module` and I had to rename it to `motion-module`.
