### ISSUE TITLE
Running Openpose and other CNs in tile-upscale

### ISSUE THREAD

**Issue by ManuelMultiverse** [s9roll7/animatediff-cli-prompt-travel#41]
Hi! I have set openpose in tile-upscale but its not being applied or it doesnt appear in console.
Any ideas?

**Comment by s9roll7** [comment]
tile-upscale is intended for simple upscaling purposes only. It only supports things that are useful to combine with controlnet_tile when upscaling.

**Comment by ManuelMultiverse** [comment]
Gotcha. Is there another script that I can use as an i2i upscale for input openpose?
