### ISSUE TITLE
Frozen when trying stylize command

### ISSUE THREAD

**Issue by iamgoret** [s9roll7/animatediff-cli-prompt-travel#42]
Getting stuck after running the command:
`animatediff stylize create-config stylize/snaptik.mp4`
![image](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/7312075/6056660d-246f-4731-939b-aa14d1e76a6a)

Looks similar to issue https://github.com/s9roll7/animatediff-cli-prompt-travel/issues/31, however I don't have a '.' in my model name so I believe the path should be valid.

Running a standard txt2vid works fine, just seems to be a problem with stylize (vid2vid).

In the output folder is several controlnet folders with some generated frames (around 400 or so), but the number of files doesn't appear to increase even though Powershell>Python shows about 7% CPU usage and 0% GPU.

**Comment by s9roll7** [comment]
Maybe the download fails is probably something related to account permissions.
Please download manually.
You will need model.onnx and selected_tags.csv
https://huggingface.co/SmilingWolf/wd-v1-4-moat-tagger-v2/tree/main

animatediff-cli/data/models/WD14tagger/model.onnx
animatediff-cli/data/models/WD14tagger/selected_tags.csv

**Comment by iamgoret** [comment]
100% related to account permissions, I fixed it by running it as powershell as admin. Sometimes it's the simple fixes you forget.

**Comment by nathanshipley** [comment]
Running powershell as administrator fixed this for me too - for me it was hanging on:

`Preprocessing images (controlnet_openpose)   0% ━━━━━━━━━━━━━━ 0/3  [ 0:00:00 < -:--:-- , ? it/s ]`
