### ISSUE TITLE
Question : Out of memory in colab ?

### ISSUE THREAD

**Issue by x4080** [s9roll7/animatediff-cli-prompt-travel#43]
Hi, I'm running example :
```
!animatediff generate -c /content/animatediff-cli-prompt-travel/config/prompts/prompt_travel.json -W 256 -H 384 -L 128 -C 16
```

and it stop by itself, maybe out of memory, the last log :

```
...
Downloading mm_sd_v15_v2.ckpt: 100% 1.82G/1.82G [00:17<00:00, 102MB/s]
Loading tokenizer...
Loading text encoder...
Loading VAE...
Loading UNet...
Loaded 417.1376M-parameter motion module
Using scheduler "k_dpmpp_sde" (DPMSolverSinglestepScheduler)
Loading weights from /content/animatediff-cli-prompt-travel/data/share/Stable-diffusion/mistoonAnime_v20.safetensors
^C
```

Is 12GB RAM is not enough ? Tried to set -L to 64 and still same result

TIA

**Comment by s9roll7** [comment]
Is it ram, not vram?
Never cared for it before.
-L 16 doesn't work either?

**Comment by x4080** [comment]
@s9roll7 Thanks for answering, I thing its RAM, because in the graph right after crashed, the memory hit near 13GB, I'll try your suggestion

**Comment by s9roll7** [comment]
I haven't tried it though, I found a colab that someone made.
I heard this one works.
https://colab.research.google.com/drive/1QVxBjAamxOIAAlSohQklZltRPx8WsxEN

**Comment by x4080** [comment]
Thanks @s9roll7 I'll check it out

**Comment by almfahd41** [comment]
> Hi, I'm running example :
> 
> ```
> !animatediff generate -c /content/animatediff-cli-prompt-travel/config/prompts/prompt_travel.json -W 256 -H 384 -L 128 -C 16
> ```
> 
> and it stop by itself, maybe out of memory, the last log :
> 
> ```
> ...
> Downloading mm_sd_v15_v2.ckpt: 100% 1.82G/1.82G [00:17<00:00, 102MB/s]
> Loading tokenizer...
> Loading text encoder...
> Loading VAE...
> Loading UNet...
> Loaded 417.1376M-parameter motion module
> Using scheduler "k_dpmpp_sde" (DPMSolverSinglestepScheduler)
> Loading weights from /content/animatediff-cli-prompt-travel/data/share/Stable-diffusion/mistoonAnime_v20.safetensors
> ^C
> ```
> 
> Is 12GB RAM is not enough ? Tried to set -L to 64 and still same result
> 
> TIA

do you have the link for that colab ?

**Comment by PattAtk** [comment]
> I haven't tried it though, I found a colab that someone made. I heard this one works. https://colab.research.google.com/drive/1QVxBjAamxOIAAlSohQklZltRPx8WsxEN

Thanks for all your work. That colab is cool but is missing key features your repo offers like controlnet and the ability to loop videos. I'm not a coder and got stuck trying to activate venv to work with my uploaded files to google drive. Looked into the issue and venv seems pretty tricky to work with from a notebook. Would be very interested to see if someone figures it out.

**Comment by almfahd41** [comment]
> > I haven't tried it though, I found a colab that someone made. I heard this one works. https://colab.research.google.com/drive/1QVxBjAamxOIAAlSohQklZltRPx8WsxEN
> 
> Thanks for all your work. That colab is cool but is missing key features your repo offers like controlnet and the ability to loop videos. I'm not a coder and got stuck trying to activate venv to work with my uploaded files of your repo to google drive. Looked into the issue and venv seems pretty tricky to work with from a notebook. Would be very interested to see if someone figures it out.


do you have the link for that colab ?

**Comment by PattAtk** [comment]
> > > I haven't tried it though, I found a colab that someone made. I heard this one works. https://colab.research.google.com/drive/1QVxBjAamxOIAAlSohQklZltRPx8WsxEN
> > 
> > 
> > Thanks for all your work. That colab is cool but is missing key features your repo offers like controlnet and the ability to loop videos. I'm not a coder and got stuck trying to activate venv to work with my uploaded files of your repo to google drive. Looked into the issue and venv seems pretty tricky to work with from a notebook. Would be very interested to see if someone figures it out.
> 
> @PattAtk do you have the link for that colab ?

I was referring to the one s9roll7 linked. https://colab.research.google.com/drive/1QVxBjAamxOIAAlSohQklZltRPx8WsxEN
