### ISSUE TITLE
Using openpose and tile causes the result color to be strange

### ISSUE THREAD

**Issue by sdqq1234** [s9roll7/animatediff-cli-prompt-travel#45]
I used same sd model
I have 3 key frame in tile:
![image](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/6040274/191eec2f-de00-4e9e-8593-7d79a5bda263)
and 3 key frame in openpose:
![image](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/6040274/fec47dd1-b99a-4b8e-8de1-31c6f6fc0d55)
but the result color is strange such like no VAE being used,and background is not black:
![image](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/6040274/229478bb-677a-47b5-90d6-73a26165b7d8)

every frame such like this:
![00000027](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/6040274/4445b239-a0a3-4cdb-bd08-9d2a9b4b31d7)

How can I generate result like tile keyframes
this is my prompt:
my command is  animatediff generate -c config/prompts/prompt.json -W 448 -H 640 -L 30 -C 16
[prompt.zip](https://github.com/s9roll7/animatediff-cli-prompt-travel/files/12712436/prompt.zip)

**Comment by s9roll7** [comment]
4006314

```
{
  "name": "simple",
  "path": "share/Stable-diffusion/dreamshaper_6NoVae.safetensors",
  "vae_path": "models/huggingface/runwayml/stable-diffusion-v1-5/vae",       # <-------------
  "motion_module": "models/motion-module/mm_sd_v15_v2.ckpt",
  "compile": false,
```
you need diffusers format vae, so you need to convert your own pt files.
https://github.com/huggingface/diffusers/blob/main/scripts/convert_vae_pt_to_diffusers.py

**Comment by sdqq1234** [comment]
> [4006314](https://github.com/s9roll7/animatediff-cli-prompt-travel/commit/4006314f05d958814f5d7b9165de6eee1219b48a)
> 
> ```
> {
>   "name": "simple",
>   "path": "share/Stable-diffusion/dreamshaper_6NoVae.safetensors",
>   "vae_path": "models/huggingface/runwayml/stable-diffusion-v1-5/vae",       # <-------------
>   "motion_module": "models/motion-module/mm_sd_v15_v2.ckpt",
>   "compile": false,
> ```
> 
> you need diffusers format vae, so you need to convert your own pt files. https://github.com/huggingface/diffusers/blob/main/scripts/convert_vae_pt_to_diffusers.py

I converted my vae file vae-ft-mse-840000-ema-pruned.safetensors using convert_vae_pt_to_diffusers.py
![image](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/6040274/ff93700c-d6b2-49bf-8bbe-0234af47c107)
But the result are not much different from before. I should have applied the new VAE correctly.
[prompt.zip](https://github.com/s9roll7/animatediff-cli-prompt-travel/files/12725746/prompt.zip)

before   
![00000002](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/6040274/f1ba83db-fbef-4654-bb92-2c6351b4daa3)

now
![00000003](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/6040274/3cddab32-bc16-46cf-a019-1752a1667c4a)

**Comment by s9roll7** [comment]
can you try this checkpoint?
https://civitai.com/models/24149/mistoonanime

I don't know why, but when I used anything-* family checkpoints in the past, the quality of the generation was poor, so I don't use them.

**Comment by sdqq1234** [comment]
> can you try this checkpoint? https://civitai.com/models/24149/mistoonanime
> 
> I don't know why, but when I used anything-* family checkpoints in the past, the quality of the generation was poor, so I don't use them.

ok,it looks work well,thank you 
![00000000](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/6040274/d45d2e5d-70ae-41bb-9dd8-999704a0e823)
