### ISSUE TITLE
New motion lora support?

### ISSUE THREAD

**Issue by xnmt9** [s9roll7/animatediff-cli-prompt-travel#47]
Curious if anyone's taking a stab at implementing the new motion LoRas for camera movements? It strikes me that this project may handle those movements even better than base repo since you could in theory transition from camera movement to camera movement

**Comment by s9roll7** [comment]
[4b262a0](https://github.com/s9roll7/animatediff-cli-prompt-travel/commit/4b262a025684f6364a5e5bb53a93c5949456330d)
