### ISSUE TITLE
Hello, what should I do if I encounter this problem?

### ISSUE THREAD

**Issue by shenshen246** [s9roll7/animatediff-cli-prompt-travel#48]
PS F:\diff\animatediff-cli-prompt-travel-main>  animatediff generate -c config/prompts/000sb.json -W 256 -H 384 -L 128 -C 16
Error in sitecustomize; set PYTHONVERBOSE for traceback:
TypeError: expected str, bytes or os.PathLike object, not NoneType
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in _run_module_as_main:196                                                                       │
│                                                                                                  │
│ in _run_code:86                                                                                  │
│                                                                                                  │
│ in <module>:4                                                                                    │
│                                                                                                  │
│   1 # -*- coding: utf-8 -*-                                                                      │
│   2 import re                                                                                    │
│   3 import sys                                                                                   │
│ ❱ 4 from animatediff.cli import cli                                                              │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│   7 │   sys.exit(cli())                                                                          │
│                                                                                                  │
│ F:\diff\animatediff-cli-prompt-travel-main\src\animatediff\cli.py:15 in <module>                 │
│                                                                                                  │
│     12 from rich.logging import RichHandler                                                      │
│     13                                                                                           │
│     14 from animatediff import __version__, console, get_dir                                     │
│ ❱   15 from animatediff.generate import (controlnet_preprocess, create_pipeline,                 │
│     16 │   │   │   │   │   │   │   │     create_us_pipeline, ip_adapter_preprocess,              │
│     17 │   │   │   │   │   │   │   │     load_controlnet_models, run_inference,                  │
│     18 │   │   │   │   │   │   │   │     run_upscale, save_output,                               │
│                                                                                                  │
│ F:\diff\animatediff-cli-prompt-travel-main\src\animatediff\generate.py:21 in <module>            │
│                                                                                                  │
│     18 │   │   │   │   │      StableDiffusionPipeline)                                           │
│     19 from PIL import Image                                                                     │
│     20 from tqdm.rich import tqdm                                                                │
│ ❱   21 from transformers import (AutoImageProcessor, CLIPImageProcessor,                         │
│     22 │   │   │   │   │   │     CLIPTextModel, CLIPTokenizer,                                   │
│     23 │   │   │   │   │   │     UperNetForSemanticSegmentation)                                 │
│     24                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'UperNetForSemanticSegmentation' from 'transformers' (F:\SD\sd-webui-aki\1sd-webui-aki-v4\py310\lib\site-packages\transformers\__init__.py)

**Comment by s9roll7** [comment]
Please redo the installation.
