### ISSUE TITLE
Usable LoRA

### ISSUE THREAD

**Issue by UknowSth** [s9roll7/animatediff-cli-prompt-travel#49]
Sorry to bother you. Can you provide me some publicly available LoRA model ? I have tried my LoRA model (trained based on mistoonAnime_v20) but it doesn't work.
I'd like to confirm if the problem is with my lora model or if the code needs to be modified.

**Comment by s9roll7** [comment]
https://civitai.com/models/44278/street-fighter-ii-the-animated-movie-art-style

https://github.com/s9roll7/animatediff-cli-prompt-travel/issues/29#issue-1892308913

**Comment by UknowSth** [comment]
I get this when loading the lora:
<img width="549" alt="image" src="https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/105185510/42f2c677-6835-4b12-bf37-059cf6ea9dd2">
Is it OK? My own lora model and the model above both lead to this info. And the quality of the generated videos are poor.

**Comment by s9roll7** [comment]
That log will appear every time. Don't worry about it.

**Comment by UknowSth** [comment]
OK, thanks! I also want to know that if I need to fill in the values of "preprocessor"of the used controlnet module in config file.
like this : 
<img width="334" alt="image" src="https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/105185510/d8264449-7705-489c-9c89-7cafdbeeefd2">
I find that if I only use stylize command (stylize create_config + stylize generate) , in the generated dir "00_controlnet_image", pngs are all original images instead of preprocessed images. After checking the code ,that may be caused by the None value of "preprocessor" in config file. But in the default config the value is None....

In a word, now after I load the LoRA, the quality of the videos are poor. If the lora_map is blank, the videos are of high quality. I don't know what's wrong with it. 
Some details are as followed..
<img width="275" alt="屏幕截图 2023-09-26 182347" src="https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/105185510/dfd8acff-f8cb-4627-9ca5-9eb65e654076">

**Comment by s9roll7** [comment]
To be honest, I am not familiar with the quality of lora.
But. I think that using an overlearned lora in conjunction with animatediff often destroys the picture.

**Comment by UknowSth** [comment]
OK, thank you very much!
