### ISSUE TITLE
help!How to stylize video?

### ISSUE THREAD

**Issue by tbxmh** [s9roll7/animatediff-cli-prompt-travel#50]
Can you please come up with a more detailed tutorial on stylize video? For some reason I can't seem to link huggingface online to download the model. So I would like to know what models need to be downloaded and the path to where they are stored. Also, I'd like to know the steps to stylize video in more detail, the current steps seem a bit obscure. But that doesn't stop it from being a wonderful job. It's just that I'd like to know in more detail. Thanks!

**Comment by s9roll7** [comment]
https://github.com/s9roll7/animatediff-cli-prompt-travel/issues/42

**Comment by tbxmh** [comment]
> [第42章](https://github.com/s9roll7/animatediff-cli-prompt-travel/issues/42)
!
![image](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/143077425/e37aa330-4a44-4e7f-b068-bbf429ef06fe)

I think I've downloaded both files and put them under the path you mentioned. But there is still a problem.
![image](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/143077425/1c8e0de3-d4e6-434e-948f-2321851885a4)
For example an error like the one in the picture above. This has been bugging me all day and would love your help!
