### ISSUE TITLE
Feature request: image2image + upscale pipeline (a.k.a. Highrez Fix in A1111)

### ISSUE THREAD

**Issue by GuruVirus** [s9roll7/animatediff-cli-prompt-travel#56]
Function: increases resolution and sharpens images, also produces higher quality faces.

This thread appears to have the code necessary to reproduce this feature using diffusers:
https://github.com/huggingface/diffusers/issues/3429

**Comment by s9roll7** [comment]
Similar features have already been implemented.
```
# upscale using controlnet (tile, line anime, ip2p, ref)
# specify the directory of the frame generated in the above step
# default config path is 'frames_dir/../prompt.json'
# here, width=512 is specified, but even if the original size is 512, it is effective in increasing detail
animatediff tile-upscale PATH_TO_TARGET_FRAME_DIRECTORY -c config/prompts/prompt_travel.json -W 512

# upscale width to 768 (smoother than tile-upscale)
animatediff refine PATH_TO_TARGET_FRAME_DIRECTORY -W 768
# If generation takes an unusually long time, there is not enough vram.
# Give up large size or reduce the size of the context.
animatediff refine PATH_TO_TARGET_FRAME_DIRECTORY -W 1024 -C 6
```

**Comment by GuruVirus** [comment]
Problems with controlnet in this case:
1) you have to have a source frame (what, we have to run this as a separate command on the output frame folder from the initial gen?), which I don't have or want, and 2) it doesn't use ESRGAN models which have specific effects.

I prefer to do a single generation pipeline with no post-processing.
