### ISSUE TITLE
how to do this?

### ISSUE THREAD

**Issue by yishuaidu** [s9roll7/animatediff-cli-prompt-travel#57]
your work is great! I also get nice video. 

https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/21111758/11bc2cc6-1d27-4fd8-8e5b-be5abe8a73f3

however, how do you get this? 

![image](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/21111758/954108e8-9608-4b60-ae68-77f2225e1b3c)

**Comment by dragan2023** [comment]
How to do this?

**Comment by yishuaidu** [comment]
> How to do this?

![](https://user-images.githubusercontent.com/21111758/270856863-954108e8-9608-4b60-ae68-77f2225e1b3c.png)

this one, very close with input img.

**Comment by s9roll7** [comment]
```
Numbered from left to right.
1.prompt + lora
2.prompt + lora + IP-Adapter(scale 0.5)
3.prompt + lora + IP-Adapter Plus(scale 0.5)
4.prompt + lora + Controlnet Reference Only(style_fidelity 0)
```

**Comment by yishuaidu** [comment]
could you plz a little more detail about that?  say, what prompt stuffs.
