### ISSUE TITLE
These two errors occurred during the final run

### ISSUE THREAD

**Issue by dragan2023** [s9roll7/animatediff-cli-prompt-travel#59]
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
ImportError: cannot import name 'allow_ops_in_compiled_graph' from 'einops._torch_specific' (E:\sd-webui-aki-v4.2\python\lib\site-packages\einops\_torch_specific.py)

**Comment by s9roll7** [comment]
Perhaps the installation failed or is running without venv enabled.
