### ISSUE TITLE
help!please

### ISSUE THREAD

**Issue by tbxmh** [s9roll7/animatediff-cli-prompt-travel#60]
I can run animatediff generate -c config/prompts/prompt_travel.json -W 256 -H 384 -L 128 -C 16 normally, but when I try to implement the video stylization I get the problem in the picture below?
![image](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/143077425/9406ec3b-6150-4f69-afe7-7df774075100)

**Comment by tbxmh** [comment]
> 您是否以管理员权限运行？

It's not. It was run with the command you gave.

**Comment by s9roll7** [comment]
https://github.com/s9roll7/animatediff-cli-prompt-travel/issues/42

**Comment by tbxmh** [comment]
> #42
![image](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/143077425/c16e670c-588f-49c2-88a2-61580abf6e5d)

I think I'm running with administrator privileges here, but it still reports the same error. Is this related to the fact that I can't connect to huggingface?
