### ISSUE TITLE
Help with the installation of the models

### ISSUE THREAD

**Issue by ShmuelRonen** [s9roll7/animatediff-cli-prompt-travel#61]
I did the installation. But there is no mention of which models I should be installed and where. 
Can you specify which models I should be added and where to put them?

**Comment by PattAtk** [comment]
> I did the installation. But there is no mention of which models I should be installed and where. Can you specify which models I should be added and where to put them?

Your normal stable diffusion goes in animatediff-cli-prompt-travel\data\models\sd
Your motion module goes in animatediff-cli-prompt-travel\data\models\motion-module

You can also use absolute paths for everything except the stable diffusion model

**Comment by ShmuelRonen** [comment]
Your normal stable diffusion goes in animatediff-cli-prompt-travel\data\models\sd 
Do you mean automatic1111?

**Comment by PattAtk** [comment]
> Your normal stable diffusion goes in animatediff-cli-prompt-travel\data\models\sd Do you mean automatic1111?
> 
> To put the contents of stable-diffusion-webui inside the SD folder?

No, keep all automatic1111 stuff the way it is. Make a copy of whatever model you want to use from stable-diffusion-webui\models\Stable-diffusion and put it in animatediff-cli-prompt-travel\data\models\sd

**Comment by ShmuelRonen** [comment]
so I can put here absulute paths of where the models in automatic1111:



# prompt_travel.json
{
  "name": "sample",
  "path": "share/Stable-diffusion/mistoonAnime_v20.safetensors",  # Specify Checkpoint as a path relative to /animatediff-cli/data
  "vae_path":"share/VAE/vae-ft-mse-840000-ema-pruned.ckpt",       # Specify vae as a path relative to /animatediff-cli/data
  "motion_module": "models/motion-module/mm_sd_v14.ckpt",         # Specify motion module as a path relative to /animatediff-cli/data
  "compile": false,

**Comment by ShmuelRonen** [comment]
Are you thinking about adding a GUI?

**Comment by PattAtk** [comment]
> so I can put here absulute paths of where the models in automatic1111? path": "W:\stable-diffusion-webui/models/Stable-diffusion/mistoonAnime_v20.safetensors"
> 
> or:
> 
> "path": "data/models/sd/mistoonAnime_v20.safetensors"
> 
> # prompt_travel.json
> { "name": "sample", "path": "share/Stable-diffusion/mistoonAnime_v20.safetensors", # Specify Checkpoint as a path relative to /animatediff-cli/data "vae_path":"share/VAE/vae-ft-mse-840000-ema-pruned.ckpt", # Specify vae as a path relative to /animatediff-cli/data "motion_module": "models/motion-module/mm_sd_v14.ckpt", # Specify motion module as a path relative to /animatediff-cli/data "compile": false,

I tried absolute path for the SD model itself (the mistoonAnime_v20.safetensors) but it didn't play nice with the rest of the code. The share/Stable-diffusion folder didn't exist for me so I just used models/sd/ (it's relative to the data folder) However, I was able to use absolute path for all else like motion module and LORAs. 

Mine would look something like this:
  "name": "sample",
  "path": "models/sd/mistoonAnime_v20.safetensors",
  "motion_module": "F:/stable-diffusion-webui/extensions/sd-webui-animatediff/model/animatediffMotion_v15V2.ckpt",
  "compile": false,

**Comment by kaosbeat** [comment]
I had some issues with my models being on another drive.
I ended up changing

util.py line 57:

```
def path_from_cwd(path: PathLike) -> str:
    path = Path(path)
    # return str(path.absolute().relative_to(Path.cwd()))
    return str(path.absolute())

```
making it return absolute paths on linux.
probably not the most elegant solution, but it works

**Comment by s9roll7** [comment]
I use symbolic links.
https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/mklink
