### ISSUE TITLE
Frozen when doing Openpose preprocess - last version.

### ISSUE THREAD

**Issue by ManuelMultiverse** [s9roll7/animatediff-cli-prompt-travel#62]
It stays as 0/ XXX forever when trying to preprocess openpose folder images. Images are 512. Working on a 4090.

**Comment by ManuelMultiverse** [comment]
Its the dw preprocessor, not installing propperly, how can I disable it - uninstall?

**Comment by s9roll7** [comment]
Are you running with administrator privileges?

**Comment by ManuelMultiverse** [comment]
Ill try that, I could input preprocessed frames and run other controlnets without any issue. But still frozen when pre- with controlnet.

**Comment by s9roll7** [comment]
https://github.com/s9roll7/animatediff-cli-prompt-travel/issues/42

**Comment by appliedintelligencelab** [comment]
42 is always the answer. Run Powershell in admin mode. That fixed it for me.
