### ISSUE TITLE
Support for SDXL?

### ISSUE THREAD

**Issue by Gitterman69** [s9roll7/animatediff-cli-prompt-travel#64]
Support for the new models would be amazing!!!!!

**Comment by JCBrouwer** [comment]
This requires a new motion module trained from scratch to match the SDXL architecture, it's not just a case of copy-paste in the SDXL code and go...

**Comment by waldmannly** [comment]
https://github.com/guoyww/AnimateDiff/tree/sdxl

sdxl has motion module and animated diff beta as of 11/9/2023.

**Comment by s9roll7** [comment]
40e2a9a
