### ISSUE TITLE
Max lenght of the movies limited to 16 seconds/220 frames?

### ISSUE THREAD

**Issue by Gitterman69** [s9roll7/animatediff-cli-prompt-travel#65]
I love your program a lot but i wonder, if there is a hard limit of 220 frames in total? i cant seem to get more to generate....

**Comment by Gitterman69** [comment]
![SCR-20230928-3nz](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/113683801/d5be349b-efd6-4514-89da-0d844a3d22e7)

**Comment by Gitterman69** [comment]
![SCR-20230928-3ov](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/113683801/2be27484-6793-4016-9d8a-e9a75a4c1def)

as you can see the config should include up to over 1000 frames....

**Comment by SoftologyPro** [comment]
Can you explain the -L parameter?  For example if I have these prompts
```
"0":  "red paint splashing",
"50":  "orange paint splashing",
"100":  "yellow paint splashing",
"150":  "green paint splashing",
"200":  "blue paint splashing",
"250":  "indigo paint splashing",
"300":  "violet paint splashing"
```
and I set the length to 350.  Then when I start running it shows 750 total frames being calculated.  In that case I want the last prompt to last another 50 frames.  What settings do we need to use for that?

**Comment by s9roll7** [comment]
Are you talking about the numbers in the progress display?
That number is a value that has nothing to do with the number of frames. It is a unit of internal processing.

**Comment by SoftologyPro** [comment]
> Are you talking about the numbers in the progress display? That number is a value that has nothing to do with the number of frames. It is a unit of internal processing.

Yes, thanks, I worked that out after I posted.  Output movies total frames match the -L length parameter.
