### ISSUE TITLE
Freezing Windows system

### ISSUE THREAD

**Issue by szriru** [s9roll7/animatediff-cli-prompt-travel#67]
I don't exactly why but working around "stylize" things causes freezing Windows System.
Especially, when I try to configure files inside "stylize" folder  like deleting or moving a file with file explorer, even after every process are done, the entire screen excepet the mouse movement goes freeze. All I can do is just forcing shut down the system by pressing a physical power button and restart the system to use my computer again.

I think there's some inappropriate process or missing process for GPU memory.

I didn't try original animatediff-cli, so I don't know this problem is specific for this repo.

my environment:
OS: windows 11
CPU: 12900K
GPU: RTX 4090 24GB

**Comment by s9roll7** [comment]
Are you running out of vram by entering large widths and heights?
