### ISSUE TITLE
BadZipFile: Bad CRC-32 for file 'torch/lib/cublasLt64_11.dll'

### ISSUE THREAD

**Issue by steploff** [s9roll7/animatediff-cli-prompt-travel#69]
I'm following the installation instructions and keep getting this error when I do the python installation. anyone else getting this?

**Comment by jfranecki** [comment]
Yeah that happens a lot to me. You have to add --no-cache to the end of that line, whether that be in a file or command prompt. For this project during installation I remember I had to put it here:
`python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 --no-cache`

**Comment by steploff** [comment]
hey, thanks so much for the help. it worked.

> Yeah that happens a lot to me. You have to add --no-cache to the end of that line, whether that be in a file or command prompt. For this project during installation I remember I had to put it here: `python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 --no-cache`
