### ISSUE TITLE
Install with no errors, but after activating venv in order to test demo...

### ISSUE THREAD

**Issue by GastonSan79** [s9roll7/animatediff-cli-prompt-travel#70]
... the command
`animatediff generate -c config\prompts\prompt_travel.json -W 256 -H 384 -L 128 -C 16"` 
keeps showing the message:
`Invalid value for '--config-path' / '-c': File 'config\\prompts\\prompt_travel.json' does not exist.`

My install of animatediff is inside two folders (AI\ADIFF), can this be the issue?
Thanks in advance.

**Comment by Lylo01** [comment]
I would just cd AI\ADIFF and git pull to make sure it's up to date, then, have you tried using the full path to the config file just to see if it reads it?
e.g:
animatediff generate -c C\Apps\AI\ADIFF\:config\prompts\prompt_travel.json -W 256 -H 384 -L 128 -C 16

Also make sure you have that .json file in config\prompts

**Comment by GastonSan79** [comment]
Thanks for your answer. Git pull shows that is up to date. And writing the full path give as a result:
```
ValueError: 'H:\\AI\\ADIFF\\animatediff-cli-prompt-travel\\config\\prompts\\prompt_travel.json' is not in the subpath of
'H:\\AI\\ADIFF\\animatediff-cli-prompt-travel\\venv\\Scripts' OR one path is relative and the other is absolute.
```
Double checked the .json, is there where is supposed to be. It must be some very basic thing I'm not seeing and is a little infuriating.

**Comment by GastonSan79** [comment]
Reinstalling the repo and dependencies in hard drive root (not inside another folder) appear to have solved the problem. Demo is now downloading the models needed. I'm closing the issue.
