### ISSUE TITLE
Controlnet_Tile Visual artifacts during stylize

### ISSUE THREAD

**Issue by Lylo01** [s9roll7/animatediff-cli-prompt-travel#72]
Hi,
Thank you so much for your work on this! I'm running into a weird issue, specifically, after stylizing a video and it gets to the upscale part, I get a lot of weird visual artifacts.
Example original stylize vs c-net tile:
![00000028](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/141736975/e92d39d9-d2f1-45e5-8a2a-157bbb92dc78)

![00000028](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/141736975/62e09b9f-b1f5-48a9-997c-9615fbf2dd49)

[prompt.txt](https://github.com/s9roll7/animatediff-cli-prompt-travel/files/12774081/prompt.txt)

Tried using the same tile cnet on webui and it works well with the same settings..Any help would be greatly appreciated!

**Comment by s9roll7** [comment]
```
        "1": {
            "steps": 20,
            "guidance_scale": 3.0,        # This is indeed too low, isn't it?
            "width": 768,
            "height": 960,
            "length": 36,
            "context": 8,
            "overlap": 0,                # Use the number of contexts divided by 4. If it is 0, will it cause quality problems?
            "stride": 0,
            "controlnet_tile": {
                "enable": true,
                "use_preprocessor": true,
                "guess_mode": false,
                "controlnet_conditioning_scale": 0.5,   # I think the main cause of the problem is that this value was lowered from 1. There's no advantage to setting it to 0.5 at the time of the upscale.
                "control_guidance_start": 0.0,
                "control_guidance_end": 1.0,
                "control_scale_list": []
            },
            "controlnet_ip2p": {
                "enable": false,
                "use_preprocessor": true,
                "guess_mode": false,
                "controlnet_conditioning_scale": 0.5,
                "control_guidance_start": 0.0,
                "control_guidance_end": 1.0,
                "control_scale_list": []
            },
            "ip_adapter": false,
            "reference": false,
            "interpolation_multiplier": 1
        }
```

**Comment by Cubey42** [comment]
I find that controlnet_condition_scale to be 0.8 to get slightly better results.



> Hi, Thank you so much for your work on this! I'm running into a weird issue, specifically, after stylizing a video and it gets to the upscale part, I get a lot of weird visual artifacts. Example original stylize vs c-net tile: ![00000028](https://user-images.githubusercontent.com/141736975/271756789-e92d39d9-d2f1-45e5-8a2a-157bbb92dc78.png)
> 
> ![00000028](https://user-images.githubusercontent.com/141736975/271756848-62e09b9f-b1f5-48a9-997c-9615fbf2dd49.png)
> 
> [prompt.txt](https://github.com/s9roll7/animatediff-cli-prompt-travel/files/12774081/prompt.txt)
> 
> Tried using the same tile cnet on webui and it works well with the same settings..Any help would be greatly appreciated!

You need to consider the ratios of your upscale, you need to stick to 1x,1.5x,2x within the same ratio resolution.

**Comment by Lylo01** [comment]
Thank you both @s9roll7 @Cubey42. After changing guidance_scale to 10, overlap so it's context/4 and controlnet_conditioning_scale to 0.8/1 it seemed to be pretty much the same (mostly), but once i've made sure to also keep the aspect ratio altogether it seems to be pretty much back on track:
![00000000](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/141736975/bc08cd93-5c11-458d-a35c-268d3e5dc7b7)

![00000000](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/141736975/e4377e79-b949-4034-992c-0a10a3526946)

There seem to still be some visual artifacts but at this point this could very much be the cnet/model/mm/cfg but I am still experimenting and looking for that sweet spot and will share once I've found it!
![image](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/141736975/6e28675b-61ac-44cc-b3cd-e2e3ff943278)

Much appreciated, thanks again!
