### ISSUE TITLE
Some models do not apply vae when upscaling

### ISSUE THREAD

**Issue by rena0408** [s9roll7/animatediff-cli-prompt-travel#74]
Hi, First of all, great work!
My model has no problem with normal generate, but only when upscaling.
Realistic Vision , XXMix_9realistic, etc. also succeed when upscaling.

test-L10-C16-W384-H512-T768-T1152.json
![r300000009](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/146616176/50ec422d-f315-4e92-957e-e452c2421f2b)

Can it be resolved? thanks.

**Comment by s9roll7** [comment]
I don't know why, but there is a checkpoint where the color fades when used in animatediff.
