### ISSUE TITLE
Please merge this fork into the main AnimateDiff-CLI

### ISSUE THREAD

**Issue by advo-kat** [s9roll7/animatediff-cli-prompt-travel#8]
It would be great if you could submit a PR for the main repo so it could be integrated into the root repo so we can stay put to date with new features and fixes while being able to use your wonderful work. 🙏

**Comment by s9roll7** [comment]
While experimenting with various things in this fork,
I have changed the format of the config file and the prompt, as well as the version of the diffusers on which it depends, and I think I have lost some of the functionality that the original code had.

Could you submit the necessary parts as a PR on my behalf?

**Comment by advo-kat** [comment]
Thank you for your reply and your hard work! 🙏

I’ll look into it and do that, along with contacting the main repo author.
