### ISSUE TITLE
UnboundLocalError: local variable 'final_boxes' referenced before assignment

### ISSUE THREAD

**Issue by RReyes04** [s9roll7/animatediff-cli-prompt-travel#82]
Getting error message about a 'final boxes'

Everything works fine when I generate 34 and below frames (-L 34) but when I remove -L or simply put -L 35 on the command I get that error.
The ref video is a 13 second long video which has a total of 131 frames generated by the command `animatediff stylize create-config` which the PNGs I cut and pasted into the Controlnet-openpose and Controlnet-ip2p folders.

`(venv) F:\stable-diffusion-webui\animatediff-cli-prompt-travel>animatediff stylize generate .\stylize\2023-10-03T00-03-26-sample-foxyansfw_v4\

02:39:45 INFO     Using generation config: stylize\2023-10-03T00-03-26-sample-foxyansfw_v4\prompt.json        cli.py:288
02:39:46 INFO     is_v2=True                                                                                 util.py:323
         INFO     Using base model: runwayml\stable-diffusion-v1-5                                            cli.py:306
         INFO     Will save outputs to                                                                        cli.py:314
                  ./stylize\2023-10-03T00-03-26-sample-foxyansfw_v4\2023-10-03T02-39-46-sample-foxyansfw_v4
Preprocessing images (controlnet_ip2p)  96% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━ 126/131  [ 0:00:01 < 0:00:01 , 88 it/s ]
Saving Preprocessed images (controlnet_ip2p)  99% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 129/130  [ 0:00:01 < 0:00:01 , 77 it/s ]
F:\stable-diffusion-webui\animatediff-cli-prompt-travel\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_co
llection.py:69: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available
providers: 'AzureExecutionProvider, CPUExecutionProvider'
  warnings.warn(
Preprocessing images (controlnet_openpose)  26% ━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━ 34/131  [ 0:00:17 < 0:00:43 , 2 it/s ]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ F:\stable-diffusion-webui\animatediff-cli-prompt-travel\src\animatediff\stylize.py:401 in        │
│ generate                                                                                         │
│                                                                                                  │
│   398 │   │   config_org = tmp_config_path                                                       │
│   399 │                                                                                          │
│   400 │                                                                                          │
│ ❱ 401 │   output_0_dir = generate(                                                               │
│   402 │   │   config_path=config_org,                                                            │
│   403 │   │   width=model_config.stylize_config["0"]["width"],                                   │
│   404 │   │   height=model_config.stylize_config["0"]["height"],                                 │
│                                                                                                  │
│ F:\stable-diffusion-webui\animatediff-cli-prompt-travel\src\animatediff\cli.py:316 in generate   │
│                                                                                                  │
│    313 │   save_dir.mkdir(parents=True, exist_ok=True)                                           │
│    314 │   logger.info(f"Will save outputs to ./{path_from_cwd(save_dir)}")                      │
│    315 │                                                                                         │
│ ❱  316 │   controlnet_image_map, controlnet_type_map, controlnet_ref_map = controlnet_preproces  │
│    317 │   ip_adapter_map = ip_adapter_preprocess(model_config.ip_adapter_map, width, height, l  │
│    318 │                                                                                         │
│    319 │   # beware the pipeline                                                                 │
│                                                                                                  │
│ F:\stable-diffusion-webui\animatediff-cli-prompt-travel\src\animatediff\generate.py:644 in       │
│ controlnet_preprocess                                                                            │
│                                                                                                  │
│    641 │   │   │   │   │   │   if frame_no < duration:                                           │
│    642 │   │   │   │   │   │   │   if frame_no not in controlnet_image_map:                      │
│    643 │   │   │   │   │   │   │   │   controlnet_image_map[frame_no] = {}                       │
│ ❱  644 │   │   │   │   │   │   │   controlnet_image_map[frame_no][c] = get_preprocessed_img( c,  │
│    645 │   │   │   │   │   │   │   processed = True                                              │
│    646 │   │                                                                                     │
│    647 │   │   if save_detectmap and processed:                                                  │
│                                                                                                  │
│ F:\stable-diffusion-webui\animatediff-cli-prompt-travel\src\animatediff\generate.py:306 in       │
│ get_preprocessed_img                                                                             │
│                                                                                                  │
│    303 │   │   param = {}                                                                        │
│    304 │   │   if preprocessor_map:                                                              │
│    305 │   │   │   param = preprocessor_map["param"] if "param" in preprocessor_map else {}      │
│ ❱  306 │   │   return get_preprocessor(type_str, device_str, preprocessor_map)(img, **param)     │
│    307 │   else:                                                                                 │
│    308 │   │   return img                                                                        │
│    309                                                                                           │
│                                                                                                  │
│ F:\stable-diffusion-webui\animatediff-cli-prompt-travel\src\animatediff\dwpose\__init__.py:53 in │
│ __call__                                                                                         │
│                                                                                                  │
│   50 │   │   input_image = resize_image(input_image, detect_resolution)                          │
│   51 │   │   H, W, C = input_image.shape                                                         │
│   52 │   │   with torch.no_grad():                                                               │
│ ❱ 53 │   │   │   candidate, subset = self.pose_estimation(input_image)                           │
│   54 │   │   │   nums, keys, locs = candidate.shape                                              │
│   55 │   │   │   candidate[..., 0] /= float(W)                                                   │
│   56 │   │   │   candidate[..., 1] /= float(H)                                                   │
│                                                                                                  │
│ F:\stable-diffusion-webui\animatediff-cli-prompt-travel\src\animatediff\dwpose\wholebody.py:21   │
│ in __call__                                                                                      │
│                                                                                                  │
│   18 │   │   self.session_pose = ort.InferenceSession(path_or_bytes=onnx_pose, providers=prov    │
│   19 │                                                                                           │
│   20 │   def __call__(self, oriImg):                                                             │
│ ❱ 21 │   │   det_result = inference_detector(self.session_det, oriImg)                           │
│   22 │   │   keypoints, scores = inference_pose(self.session_pose, det_result, oriImg)           │
│   23 │   │                                                                                       │
│   24 │   │   keypoints_info = np.concatenate(                                                    │
│                                                                                                  │
│ F:\stable-diffusion-webui\animatediff-cli-prompt-travel\src\animatediff\dwpose\onnxdet.py:124 in │
│ inference_detector                                                                               │
│                                                                                                  │
│   121 │   │   isbbox = [ i and j for (i, j) in zip(isscore, iscat)]                              │
│   122 │   │   final_boxes = final_boxes[isbbox]                                                  │
│   123 │                                                                                          │
│ ❱ 124 │   return final_boxes                                                                     │
│   125                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
UnboundLocalError: local variable 'final_boxes' referenced before assignment`

**Comment by s9roll7** [comment]
Thanks for the report.
Looks like the undetected case is no good.

**Comment by RReyes04** [comment]
This issue seems to only show when I enable openpose. Enabling other controlnet models doesn't have issues as far I can see.

**Comment by s9roll7** [comment]
454b4a0
