### ISSUE TITLE
Duplicated method?

### ISSUE THREAD

**Issue by LWprogramming** [s9roll7/animatediff-cli-prompt-travel#83]
We have [_encode_prompt](https://github.com/s9roll7/animatediff-cli-prompt-travel/blob/f67dfdc138b93dce96e5e32d7b3e932d3ab7a3f5/src/animatediff/pipelines/animation.py#L247) and [__encode_prompt](https://github.com/s9roll7/animatediff-cli-prompt-travel/blob/f67dfdc138b93dce96e5e32d7b3e932d3ab7a3f5/src/animatediff/pipelines/animation.py#L328C9-L328C24). The latter isn't used as far as I can see, but maybe there's some more context behind why it's there. Just checking if the latter is still a useful function?

**Comment by s9roll7** [comment]
The unused one is probably the original implementation.
I just forgot to erase it.
