### ISSUE TITLE
QUESTION ABOUT SEED

### ISSUE THREAD

**Issue by alanhuang67** [s9roll7/animatediff-cli-prompt-travel#85]
Hello, I got question about the fix seed or not, if I fix seed number, can I always get the same face without change? thanks!

**Comment by PattAtk** [comment]
> Hello, I got question about the fix seed or not, if I fix seed number, can I always get the same face without change? thanks!

No, you need some form of ControlNet to instruct some consistency. The seed alone will give you consistency only if all other aspects like prompts, dimensions, guidance scale, clip skip, etc. stay exactly the same or with very minor changes.
