### ISSUE TITLE
New pytorch 2.1 and Xformer

### ISSUE THREAD

**Issue by MSVstudios** [s9roll7/animatediff-cli-prompt-travel#87]
Because Xformer<=0.23 doesn't support yet PyTorch v2.1 you must force using PyTorch version 2.01 on install
`pip3 install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cu118`
i hope that can help others

**Comment by boombbo** [comment]
you don't need update PyTorch v2.1 !

**Comment by s9roll7** [comment]
At this time I recommend xformers 0.0.22.post7 + torch 2.1.0. I think you will need it, especially if you use sdxl

**Comment by hcorn82** [comment]
I had this problem but now I get 

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xformers 0.0.22.post7 requires torch==2.1.0, but you have torch 2.0.1+cu118 which is incompatible.
```
