### ISSUE TITLE
video stylize always generate the same style video?

### ISSUE THREAD

**Issue by paragone** [s9roll7/animatediff-cli-prompt-travel#88]
hi and thanks for ur great work,

    First Step:
    _animatediff stylize create-config YOUR_SRC_MOVIE_FILE.mp4_
    Second Step:
    I've try about 10 checkpoints by edit  'path' in prompt.json, then 
    _animatediff stylize generate STYLYZE_DIR -L 16_
    
    but animatediff seems always generate the same style video,
Can you help me think about where the problem might be?

thanks

**Comment by paragone** [comment]
yes sure!
you can see logs  below:

13:39:13 INFO     Using generation config: stylize\2023-10-05T23-05-50-sample-mistoonanime_v20\prompt_tmp.json                                                                                                                                                                                                                        cli.py:288
         INFO     is_v2=True                                                                                                                                                                                                                                                                                                         util.py:346
         INFO     Using base model: runwayml\stable-diffusion-v1-5                                                                                                                                                                                                                                                                    cli.py:306
         INFO     Will save outputs to ./stylize\2023-10-05T23-05-50-sample-mistoonanime_v20\2023-10-07T13-39-13-hangzhou-xxmix9realistic_v40                                                                                                                                                                                         cli.py:314
Preprocessing images (controlnet_tile)  94% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━ 15/16  [ 0:00:00 < 0:00:01 , 26 it/s ]
Saving Preprocessed images (controlnet_tile) 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16/16  [ 0:00:01 < 0:00:00 , 8 it/s ]
Preprocessing images (controlnet_ip2p)  94% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━ 15/16  [ 0:00:00 < 0:00:01 , 27 it/s ]
Saving Preprocessed images (controlnet_ip2p) 100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16/16  [ 0:00:01 < 0:00:00 , 8 it/s ]
13:39:18 INFO     Checking motion module...                                                                                                                                                                                                                                                                                      generate.py:321
         INFO     Loading tokenizer...                                                                                                                                                                                                                                                                                           generate.py:335
         INFO     Loading text encoder...                                                                                                                                                                                                                                                                                        generate.py:337
13:39:19 INFO     Loading VAE...                                                                                                                                                                                                                                                                                                 generate.py:339
         INFO     Loading UNet...                                                                                                                                                                                                                                                                                                generate.py:341
13:39:23 INFO     Loaded 453.20928M-parameter motion module                                                                                                                                                                                                                                                                          unet.py:578
13:39:24 INFO     Using scheduler "k_dpmpp_sde" (DPMSolverSinglestepScheduler)                                                                                                                                                                                                                                                   generate.py:353
         INFO     Loading weights from E:\animatediff-cli-prompt-travel\data\models\sd\xxmix9realistic_v40.safetensors                                                                                                                                                                                                           generate.py:358
13:39:28 INFO     Merging weights into UNet...                                                                                                                                                                                                                                                                                   generate.py:375
         INFO     Creating AnimationPipeline...                                                                                                                                                                                                                                                                                  generate.py:421
         INFO     No TI embeddings found                                                                                                                                                                                                                                                                                               ti.py:102
         INFO     loading c='controlnet_tile' model                                                                                                                                                                                                                                                                              generate.py:450
13:39:30 INFO     loading c='controlnet_ip2p' model                                                                                                                                                                                                                                                                              generate.py:450
13:39:31 INFO     Sending pipeline to device "cuda"                                                                                                                                                                                                                                                                               pipeline.py:22
         INFO     Selected data types: unet_dtype=torch.float16, tenc_dtype=torch.float16, vae_dtype=torch.bfloat16                                                                                                                                                                                                                 device.py:90
         INFO     Using channels_last memory format for UNet and VAE                                                                                                                                                                                                                                                               device.py:111
13:39:34 INFO     Saving prompt config to output directory                                                                                                                                                                                                                                                                            cli.py:367
         INFO     Initialization complete!                                                                                                                                                                                                                                                                                            cli.py:375
         INFO     Generating 1 animations                                                                                                                                                                                                                                                                                             cli.py:376
         INFO     Running generation 1 of 1                                                                                                                                                                                                                                                                                           cli.py:386
         INFO     Generation seed: 341774366206100

**Comment by paragone** [comment]
xxmix9realistic_v40.safetensors：
https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/9162812/3468adb7-2f31-45f5-86dd-38b799c4f80b

darkSushiMixMix_225D.safetensors：
https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/9162812/8f1dd255-0868-4f0a-b4a5-77783219625f

**Comment by s9roll7** [comment]
https://www.reddit.com/r/StableDiffusion/comments/16vlk9j/guide_to_creating_videos_with/

**Comment by s9roll7** [comment]
By default, controlnet_tile is set to 1.0 and controlnet_ip2p to 0.5 strength,
This is a setting that outputs a picture that looks exactly like the original picture, so if you want to change it, you should replace the tile with another controlnet.

**Comment by paragone** [comment]
> https://www.reddit.com/r/StableDiffusion/comments/16vlk9j/guide_to_creating_videos_with/

very nice! I solve this issue follow the steps writing in reddit.
