### ISSUE TITLE
QUESTION: how do I use contrnet to guide base on prompt?

### ISSUE THREAD

**Issue by alanhuang67** [s9roll7/animatediff-cli-prompt-travel#95]
Hi, may I ask how do I use contrnet to guide base on prompt?
for example, there is 3 prompt, and I like to use 01.PNG for prompt 1, 02.PNG for prompt, can I do this?
        "8": "((fire magic spell, fire background))",
        "16": "((ice magic spell, ice background))",
        "24": "((thunder magic spell, thunder background))",
Thank you so much!

**Comment by PattAtk** [comment]
You place the images matched with the frame # in data/controlnet_images/your-folder-name/whichever-controlnet-type-you're-using. Also make sure the settings are set to true in your .json file. File naming structure isn't strict, just relative to each other to properly set order, so something like 0008.png, 0016.png, 0024.png

**Comment by alanhuang67** [comment]
if the number over 100, is the file named as 0102.png? or I need to rename all file to 00016.png ~ 00102.png?
because it seems like 0102.png doesn't work.
