### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by thoughtformer** [s9roll7/animatediff-cli-prompt-travel#96]
Hi there
I tried to install AnimateDiff via the instructions provied on my Razer Naga 15, but I keep getting the error "Torch not compiled with CUDA enabled".

I know most laptops aren't suited to run Stable Diffusion, but I did manage to run Stable Diffusion through Automatic a few months ago. However, for some reason, none of the AI tools seem to be working (Automatic1111, ComfyUI, AnimateDiff, ...)

I followed the exact instructions from the repo and even installed the CUDA-drivers from nVIDIA + did a clean install, but to no avail.

Any tips?

**Comment by s9roll7** [comment]
https://www.reddit.com/r/StableDiffusion/comments/16vlk9j/guide_to_creating_videos_with/

**Comment by WDJJJJJ** [comment]
I have the same problem, tried many times, but still cannot solve it
