### ISSUE TITLE
How to make output gifs not auto-loop?

### ISSUE THREAD

**Issue by SoftologyPro** [s9roll7/animatediff-cli-prompt-travel#97]
Is there a setting other than the "is_loop" in the json?  To be clear, so the end of the output movie is not wrapped around to match the start.  It helps in some cases, but not in other movies you do not want the end to match the start.
```
    "controlnet_map": {
        "input_image_dir": "",
        "max_samples_on_vram": 200,
        "max_models_on_vram": 3,
        "save_detectmap": true,
        "preprocess_on_gpu": true,
        "is_loop": false,
        "controlnet_tile": {
```
My output gifs loop if "is_loop" is true or false.

**Comment by SoftologyPro** [comment]
Maybe this did not make sense?
Say you have prompts that go from "water" to "fire" to "rock".
What happens now is the resulting gif animates smoothly and repeats.  So water morphs to fire then morphs to rock and then morphs back to the start frame fire again.
The problem is the first frame will have some rock w
hen I only want water.
If you are making a movie you want to loop then this is OK, but in the case of other prompts you do not want the last prompt bleeding into the first.

Here is an example.
```
"0": "fire",
"16": "water",
"32": "rock"
```
![00_573668030_fire](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/47686889/cb276919-cbbc-459d-9a1a-4e35563e6144)
You can see the start of the video has rock with the fire.  I only want rock at the end of the video.
Is there a way to disable this looping behavior?

**Comment by SoftologyPro** [comment]
Is this issue understood?
Can it be fixed?

**Comment by s9roll7** [comment]
Nothing that can't be fixed, but the process is simplified by making it a loop, so I don't want to do anything to it.

**Comment by SoftologyPro** [comment]
OK, thanks for responding.
