### ISSUE TITLE
Stuck at "Saving Preprocessed Images"

### ISSUE THREAD

**Issue by thoughtformer** [s9roll7/animatediff-cli-prompt-travel#98]
Hi there again

I've encountered an issue where a ControlNet prompt keeps getting stuck at "Saving Preprocessed Images". 

As you can see in the screenshot below, the only thing that works is the Preprocessing of the images, but after that, nothing happens.

![image](https://github.com/s9roll7/animatediff-cli-prompt-travel/assets/96227163/b7963647-1f30-4558-9ccf-cfb5610f81ec)

Here's my prompt;

`{
    "name": "lenka-toonyou_beta6",
    "path": "models\\sd\\toonyou_beta6.safetensors",
    "vae_path": "",
    "motion_module": "models\\motion-module\\mm_sd_v15_v2.ckpt",
    "compile": false,
    "tensor_interpolation_slerp": true,
    "seed": [
        1965956569
    ],
    "scheduler": "euler_a",
    "steps": 50,
    "guidance_scale": 4.0,
    "clip_skip": 2,
    "prompt_fixed_ratio": 0.8,
    "head_prompt": "illustration of (dark skin:1.3), 1girl, masterpiece, matte painting, concept art, wide shot of a single beautiful black African woman with afro hair wearing a white dress, bokeh, motion blur",
    "prompt_map": {
        "0": "smile sitting, open eyes,",
        "8": "smile sitting, open eyes, wide shot",
        "16": "(((walking))), open eyes, wide shot, walking inside a museum full with paintings",
        "32": "(((walking)))face,looking at viewer, wearing an astronaut outfit, open_eyes, closed_mouth",
        "48": "(full body, shy, from_side) wearing a summer hat, walking inside a beautiful forest with autumn leaves, closed_eyes, laughing",
        "64": "(upper_body, smile, from_below) face, looking away from viewer, dancing at Burning Man festival in the desert, smiling",
        "80": "(full_body) (((walking))), liquid paint vortex, face,looking at viewer, open_eyes, closed_mouth",
        "88": "(((smiling))) face,looking at viewer, open_eyes, smile, wearing hiking outift, glowing fireflies",
        "96": "face,looking at viewer, surface of Mars, red desert sand"
    },
    "tail_prompt": "(dark skin:1.3), (afro hair:1.2), detailed face+black eyes, dark skinned female, realistic eyes, beautiful face,  very dark skin:1.3",
    "n_prompt": [
        "deformed faces, robot eyes, nsfw, nudity, easynegative, verybadimagenegative_v13, deformed face, robot eyes, (worst quality, low quality, letterboxed), (watermark), immature,"
    ],
    "is_single_prompt_mode": false,
    "lora_map": {
        "lora/add_detail.safetensors": 1.0
    },
    "motion_lora_map": {},
    "ip_adapter_map": {
        "enable": true,
        "input_image_dir": "ip_adapter_image/test",
        "save_input_image": true,
        "scale": 0.5,
        "is_plus_face": true,
        "is_plus": true
    },
    "controlnet_map": {
        "input_image_dir": "controlnet_image/test-4",
        "max_samples_on_vram": 200,
        "max_models_on_vram": 3,
        "save_detectmap": true,
        "preprocess_on_gpu": true,
        "is_loop": true,
        "controlnet_tile": {
            "enable": false,
            "use_preprocessor": true,
            "preprocessor": {
                "type": "tile_resample",
                "param": {
                    "down_sampling_rate": 2.0
                }
            },
            "guess_mode": false,
            "controlnet_conditioning_scale": 1.0,
            "control_guidance_start": 0.0,
            "control_guidance_end": 1.0,
            "control_scale_list": [
                1
            ]
        },
        "controlnet_ip2p": {
            "enable": false,
            "use_preprocessor": true,
            "guess_mode": false,
            "controlnet_conditioning_scale": 1.0,
            "control_guidance_start": 0.0,
            "control_guidance_end": 1.0,
            "control_scale_list": [
                0.5,
                0.4,
                0.3,
                0.2,
                0.1
            ]
        },
        "controlnet_canny": {
            "enable": false,
            "use_preprocessor": true,
            "guess_mode": false,
            "controlnet_conditioning_scale": 1.0,
            "control_guidance_start": 0.0,
            "control_guidance_end": 1.0,
            "control_scale_list": [
                0.5,
                0.4,
                0.3,
                0.2,
                0.1
            ]
        },
        "controlnet_depth": {
            "enable": false,
            "use_preprocessor": true,
            "guess_mode": false,
            "controlnet_conditioning_scale": 1.0,
            "control_guidance_start": 0.0,
            "control_guidance_end": 1.0,
            "control_scale_list": [
                0.5,
                0.4,
                0.3,
                0.2,
                0.1
            ]
        },
        "controlnet_lineart": {
            "enable": false,
            "use_preprocessor": true,
            "guess_mode": false,
            "controlnet_conditioning_scale": 1.0,
            "control_guidance_start": 0.0,
            "control_guidance_end": 1.0,
            "control_scale_list": [
                0.5,
                0.4,
                0.3,
                0.2,
                0.1
            ]
        },
        "controlnet_openpose": {
            "enable": true,
            "use_preprocessor": true,
            "guess_mode": false,
            "controlnet_conditioning_scale": 1.0,
            "control_guidance_start": 0.0,
            "control_guidance_end": 1.0,
            "control_scale_list": [
                0.5,
                0.4,
                0.3,
                0.2,
                0.1
            ]
        },
        "controlnet_softedge": {
            "enable": true,
            "use_preprocessor": true,
            "preprocessor": {
                "type": "softedge_pidsafe",
                "param": {}
            },
            "guess_mode": false,
            "controlnet_conditioning_scale": 1.0,
            "control_guidance_start": 0.0,
            "control_guidance_end": 1.0,
            "control_scale_list": [
                0.5,
                0.4,
                0.3,
                0.2,
                0.1
            ]
        },
        "controlnet_ref": {
            "enable": false,
            "ref_image": "ref_image/ref_sample.png",
            "attention_auto_machine_weight": 1.0,
            "gn_auto_machine_weight": 1.0,
            "style_fidelity": 0.5,
            "reference_attn": true,
            "reference_adain": false,
            "scale_pattern": [
                0.5
            ]
        }
    },
    "upscale_config": {
        "scheduler": "ddim",
        "steps": 20,
        "strength": 0.5,
        "guidance_scale": 10,
        "controlnet_tile": {
            "enable": true,
            "controlnet_conditioning_scale": 1.0,
            "guess_mode": false,
            "control_guidance_start": 0.0,
            "control_guidance_end": 1.0
        },
        "controlnet_line_anime": {
            "enable": false,
            "controlnet_conditioning_scale": 1.0,
            "guess_mode": false,
            "control_guidance_start": 0.0,
            "control_guidance_end": 1.0
        },
        "controlnet_ip2p": {
            "enable": false,
            "controlnet_conditioning_scale": 0.5,
            "guess_mode": false,
            "control_guidance_start": 0.0,
            "control_guidance_end": 1.0
        },
        "controlnet_ref": {
            "enable": false,
            "use_frame_as_ref_image": false,
            "use_1st_frame_as_ref_image": false,
            "ref_image": "ref_image/path_to_your_ref_img.jpg",
            "attention_auto_machine_weight": 1.0,
            "gn_auto_machine_weight": 1.0,
            "style_fidelity": 0.25,
            "reference_attn": true,
            "reference_adain": false
        }
    },
    "stylize_config": {},
    "output": {
        "format": "mp4",
        "fps": 8,
        "encode_param": {
            "crf": 10
        }
    },
    "result": {}
}`

Any advice? 

Thanks!

**Comment by s9roll7** [comment]
I don't know if this is the cause,
You shouldn't put spaces in directory names.

**Comment by SoftologyPro** [comment]
Run "as admin" the first time.  That allows it to download the required models.  Once you have run it fully once you no longer need admin privs.
