### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by Gcode808** [s9roll7/animatediff-cli-prompt-travel#99]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\animatediff-cli-prompt-travel\src\animatediff\cli.py:341 in generate                          │
│                                                                                                  │
│    338 │   if g_pipeline.device == device:                                                       │
│    339 │   │   logger.info("Pipeline already on the correct device, skipping device transfer")   │
│    340 │   else:                                                                                 │
│ ❱  341 │   │   g_pipeline = send_to_device(                                                      │
│    342 │   │   │   g_pipeline, device, freeze=True, force_half=force_half_vae, compile=model_co  │
│    343 │   │   )                                                                                 │
│    344                                                                                           │
│                                                                                                  │
│ D:\animatediff-cli-prompt-travel\src\animatediff\utils\pipeline.py:38 in send_to_device          │
│                                                                                                  │
│   35 │   │   pipeline.vae.train = nop_train                                                      │
│   36 │   │   pipeline.text_encoder.train = nop_train                                             │
│   37 │                                                                                           │
│ ❱ 38 │   unet_dtype, tenc_dtype, vae_dtype = get_model_dtypes(device, force_half)                │
│   39 │   model_memory_format = get_memory_format(device)                                         │
│   40 │                                                                                           │
│   41 │   if hasattr(pipeline, 'controlnet'):                                                     │
│                                                                                                  │
│ D:\animatediff-cli-prompt-travel\src\animatediff\utils\device.py:70 in get_model_dtypes          │
│                                                                                                  │
│    67 │   device = torch.device(device)  # make sure device is a torch.device                    │
│    68 │   unet_dtype = dtype_for_model("unet", device)                                           │
│    69 │   tenc_dtype = dtype_for_model("tenc", device)                                           │
│ ❱  70 │   vae_dtype = dtype_for_model("vae", device)                                             │
│    71 │                                                                                          │
│    72 │   if device.type == "cpu":                                                               │
│    73 │   │   logger.warn("Device explicitly set to CPU, will run everything in fp32")           │
│                                                                                                  │
│ D:\animatediff-cli-prompt-travel\src\animatediff\utils\device.py:58 in dtype_for_model           │
│                                                                                                  │
│    55 │   │   case "tenc":                                                                       │
│    56 │   │   │   return torch.float32 if device.type == "cpu" else torch.float16                │
│    57 │   │   case "vae":                                                                        │
│ ❱  58 │   │   │   return maybe_bfloat16(device, fallback=torch.float32)                          │
│    59 │   │   case unknown:                                                                      │
│    60 │   │   │   raise ValueError(f"Invalid model {unknown}")                                   │
│    61                                                                                            │
│                                                                                                  │
│ D:\animatediff-cli-prompt-travel\src\animatediff\utils\device.py:48 in maybe_bfloat16            │
│                                                                                                  │
│    45 ) -> torch.dtype:                                                                          │
│    46 │   """Returns torch.bfloat16 if available, otherwise the fallback dtype (default float3   │
│    47 │   device = torch.device(device)  # make sure device is a torch.device                    │
│ ❱  48 │   return torch.bfloat16 if supports_bfloat16(device) else fallback                       │
│    49                                                                                            │
│    50                                                                                            │
│    51 def dtype_for_model(model: str, device: torch.device) -> torch.dtype:                      │
│                                                                                                  │
│ D:\animatediff-cli-prompt-travel\src\animatediff\utils\device.py:31 in supports_bfloat16         │
│                                                                                                  │
│    28 │   │   │   ret = False                                                                    │
│    29 │   │   case "cuda":                                                                       │
│    30 │   │   │   with device:                                                                   │
│ ❱  31 │   │   │   │   ret = torch.cuda.is_bf16_supported()                                       │
│    32 │   │   case "xla":                                                                        │
│    33 │   │   │   ret = True                                                                     │
│    34 │   │   case "mps":                                                                        │
│                                                                                                  │
│ D:\animatediff-cli-prompt-travel\venv\lib\site-packages\torch\cuda\__init__.py:122 in            │
│ is_bf16_supported                                                                                │
│                                                                                                  │
│    119 │   │   cuda_maj_decide = int(cu_vers.split('.')[0]) >= 11                                │
│    120 │   else:                                                                                 │
│    121 │   │   cuda_maj_decide = False                                                           │
│ ❱  122 │   return torch.cuda.get_device_properties(torch.cuda.current_device()).major >= 8 and   │
│    123                                                                                           │
│    124 def _sleep(cycles):                                                                       │
│    125 │   torch._C._cuda_sleep(cycles)                                                          │
│                                                                                                  │
│ D:\animatediff-cli-prompt-travel\venv\lib\site-packages\torch\cuda\__init__.py:674 in            │
│ current_device                                                                                   │
│                                                                                                  │
│    671                                                                                           │
│    672 def current_device() -> int:                                                              │
│    673 │   r"""Returns the index of a currently selected device."""                              │
│ ❱  674 │   _lazy_init()                                                                          │
│    675 │   return torch._C._cuda_getDevice()                                                     │
│    676                                                                                           │
│    677                                                                                           │
│                                                                                                  │
│ D:\animatediff-cli-prompt-travel\venv\lib\site-packages\torch\cuda\__init__.py:239 in _lazy_init │
│                                                                                                  │
│    236 │   │   │   │   "Cannot re-initialize CUDA in forked subprocess. To use CUDA with "       │
│    237 │   │   │   │   "multiprocessing, you must use the 'spawn' start method")                 │
│    238 │   │   if not hasattr(torch._C, '_cuda_getDeviceCount'):                                 │
│ ❱  239 │   │   │   raise AssertionError("Torch not compiled with CUDA enabled")                  │
│    240 │   │   if _cudart is None:                                                               │
│    241 │   │   │   raise AssertionError(                                                         │
│    242 │   │   │   │   "libcudart functions unavailable. It looks like you have a broken build?  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError: Torch not compiled with CUDA enabled

**Comment by cppong1117** [comment]
i have same problem ,some one can tell us how to fix that ?

**Comment by cppong1117** [comment]
python -m pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cu118

run this line reinstall is working 
for me
